---
permalink: protect-scsql/concept_how_long_to_retain_transaction_log_backups_on_the_source_storage_system.html 
sidebar: sidebar 
keywords:  
summary: Das SnapCenter Plug-in für Microsoft SQL Server benötigt Transaktions-Log-Backups, um minutengenaue Restore-Vorgänge durchzuführen, bei denen Ihre Datenbank zwischen zwei vollständigen Backups wiederhergestellt wird. 
---
= Wie lange werden Transaktions-Log-Backups auf dem Quell-Storage-System aufbewahrt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SnapCenter Plug-in für Microsoft SQL Server benötigt Transaktions-Log-Backups, um minutengenaue Restore-Vorgänge durchzuführen, bei denen Ihre Datenbank zwischen zwei vollständigen Backups wiederhergestellt wird.

Wenn z. B. ein Plug-in für SQL Server um 8:00 Uhr ein komplettes Backup erstellt hat Zusammen mit einem weiteren vollständigen Backup um 5:00 Uhr konnte die Datenbank jederzeit zwischen 8:00 Uhr und nach dem letzten Transaktions-Log-Backup wiederhergestellt werden Und um 5:00 Uhr Wenn keine Transaktionsprotokolle verfügbar sind, kann das Plug-in für SQL Server nur zeitpunktgenaue Restore-Vorgänge durchführen, die eine Datenbank so lange wiederherstellen, wie das Plug-in für SQL Server ein komplettes Backup abgeschlossen hat.

In der Regel erfordern Sie minutengenaue Restore-Vorgänge nur für einen oder zwei Tage. SnapCenter speichert standardmäßig mindestens zwei Tage.
