---
permalink: protect-scsql/quick-start-to-prepare-for-snapcenter-plug-in-install-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: Enthält Anweisungen zur Vorbereitung der Installation des SnapCenter-Servers und des SnapCenter-Plug-ins für Microsoft SQL Server. 
---
= Vorbereiten der Installation von SnapCenter Server und Plug-in
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Enthält einen zusammengefassten Satz von Vorbereitungsanweisungen für die Installation des SnapCenter-Servers und des SnapCenter-Plug-ins für Microsoft SQL Server.



== Anforderungen an Domäne und Arbeitsgruppe

SnapCenter Server kann auf Systemen installiert werden, die sich entweder in einer Domäne oder in einer Arbeitsgruppe befinden.

Wenn Sie eine Active Directory-Domäne verwenden, sollten Sie einen Domänenbenutzer mit lokalen Administratorrechten verwenden. Der Domänenbenutzer sollte Mitglied der lokalen Administratorgruppe auf dem Windows-Host sein.

Wenn Sie Arbeitsgruppen verwenden, sollten Sie ein lokales Konto mit lokalen Administratorrechten verwenden.



== Lizenzanforderungen

Die Art der Lizenzen, die Sie installieren, hängt von Ihrer Umgebung ab.

[cols="1,3"]
|===
| Lizenz | Bei Bedarf 


 a| 
SnapCenter Standard Controller-basiert
 a| 
Für FAS oder AFF Storage Controller erforderlich

Bei der SnapCenter Standard Lizenz handelt es sich um eine Controller-basierte Lizenz und ist im Rahmen des Premium Bundle enthalten. Wenn Sie die Lizenz für die SnapManager Suite besitzen, erhalten Sie auch die Standardlizenz von SnapCenter. Wenn Sie SnapCenter auf Testbasis mit FAS oder AFF Storage installieren möchten, wenden Sie sich an den Vertriebsmitarbeiter, um eine Evaluierungslizenz für das Premium Bundle zu erhalten.



 a| 
SnapMirror oder SnapVault
 a| 
ONTAP

Wenn die Replizierung in SnapCenter aktiviert ist, ist entweder eine SnapMirror oder eine SnapVault Lizenz erforderlich.



 a| 
Zusätzliche Lizenzen (optional)
 a| 
Siehe link:../install/concept_snapcenter_licenses.html["SnapCenter-Lizenzen"^].



 a| 
SnapCenter-Standardlizenzen (optional)
 a| 
Sekundäre Ziele


NOTE: Es wird empfohlen, aber nicht erforderlich, dass Sie SnapCenter Standard-Lizenzen zu sekundären Zielen hinzufügen. Wenn SnapCenter Standardlizenzen nicht für sekundäre Ziele aktiviert sind, können Sie nach einem Failover-Vorgang SnapCenter nicht für ein Backup von Ressourcen auf dem sekundären Ziel verwenden. Allerdings ist eine FlexClone Lizenz für sekundäre Ziele erforderlich, um Klon- und Verifizierungsvorgänge durchzuführen.

|===


== Anforderungen an Host und Port

Für die Mindestanforderungen des ONTAP und Applikations-Plug-ins siehe https://imt.netapp.com/matrix/imt.jsp?components=117008;&solution=1259&isHWU&src=IMT["Interoperabilitäts-Matrix-Tool"^].

[cols="1,3"]
|===
| Hosts | Mindestanforderungen 


 a| 
Betriebssystem (64 Bit)
 a| 
Siehe https://imt.netapp.com/matrix/imt.jsp?components=117008;&solution=1259&isHWU&src=IMT["Interoperabilitäts-Matrix-Tool"^]



 a| 
CPU
 a| 
* Server-Host: 4 Kerne
* Plug-in-Host: 4 Kerne




 a| 
RAM
 a| 
* Server-Host: 8 GB
* Plug-in-Host: 4 GB




 a| 
Festplattenspeicherplatz
 a| 
Server-Host:

* 7 GB für SnapCenter-Serversoftware und -Protokolle
* 8 GB für SnapCenter-Repository
* Jeder Plug-in-Host: 2 GB für Plug-in-Installationen und -Logs, dies ist nur erforderlich, wenn Plug-in auf einem dedizierten Host installiert ist.




 a| 
Bibliotheken von anderen Anbietern
 a| 
Erforderlich auf Host und Plug-in-Host des SnapCenter Servers:

* Microsoft .NET Framework 4.7.2 oder höher
* ASP: NET Core Hosting Bundle (8.0.5 oder höher)
* PowerShell 7.4.2 oder höher




 a| 
Browser
 a| 
Chrome, Internet Explorer und Microsoft Edge

|===
[cols="1,3"]
|===
| Porttyp | Standardport 


 a| 
SnapCenter-Port
 a| 
8146 (HTTPS), bidirektional, anpassbar, wie unter der URL _\https://server:8146_



 a| 
SnapCenter SMCore-Kommunikations-Port
 a| 
8145 (HTTPS), bidirektional, anpassbar



 a| 
Repository-Datenbank
 a| 
3306 (HTTPS), bidirektional



 a| 
Windows Plug-in-Hosts
 a| 
135, 445 (TCP)

Neben den Ports 135 und 445 sollte auch der von Microsoft festgelegte dynamische Portbereich geöffnet sein. Remote-Installationsvorgänge verwenden den Windows Management Instrumentation (WMI)-Dienst, der diesen Portbereich dynamisch durchsucht.

Informationen zum unterstützten dynamischen Portbereich finden Sie unter https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Serviceübersicht und Netzwerkanschlussanforderungen für Windows"^].



 a| 
SnapCenter Plug-in für Windows
 a| 
8145 (HTTPS), bidirektional, anpassbar



 a| 
ONTAP-Cluster oder SVM-Kommunikations-Port
 a| 
443 (HTTPS), bidirektional; 80 (HTTP), bidirektional

Der Port wird für die Kommunikation zwischen dem SnapCenter-Serverhost, dem Plug-in-Host und der SVM oder dem ONTAP-Cluster verwendet.

|===


== Anforderungen des SnapCenter Plug-ins für Microsoft SQL Server

Sie sollten einen Benutzer mit lokalen Administratorrechten mit lokalen Anmeldeberechtigungen auf dem Remote-Host haben. Wenn Sie Cluster-Nodes verwalten, benötigen Sie einen Benutzer mit Administratorrechten für alle Nodes im Cluster.

Sie sollten einen Benutzer mit sysadmin-Berechtigungen auf dem SQL Server haben. Das Plug-in verwendet Microsoft VDI Framework, für das ein Sysadmin-Zugriff erforderlich ist.

Wenn Sie SnapManager für Microsoft SQL Server verwenden und Daten von SnapManager für Microsoft SQL Server in SnapCenter importieren möchten, lesen Sie link:../protect-scsql/concept_import_archived_backups_from_snapmanager_for_sql_to_snapcenter.html["Importieren Sie archivierte Backups"^]
