---
permalink: protect-scsql/task_disaster_recovery_scsql.html 
sidebar: sidebar 
keywords: disaster recovery 
summary: Wenn das SnapCenter-Plug-in für SQL Server ausgefallen ist, führen Sie die folgenden manuellen Schritte aus, um das Plug-in wiederherzustellen. 
---
= Wiederherstellung des SnapCenter Plug-in für SQL Server nach einem Desaster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn das SnapCenter-Plug-in für SQL Server ausfällt, führen Sie die folgenden Schritte aus, um zu einem anderen SQL-Host zu wechseln und die Daten wiederherzustellen.

.Bevor Sie beginnen
* Der sekundäre Host sollte das gleiche Betriebssystem, die gleiche Anwendung und den gleichen Hostnamen wie der primäre Host haben.
* Das SnapCenter Plug-in für SQL Server kann mithilfe der Seite *Host hinzufügen* oder *Host ändern* auf einen alternativen Host verschoben werden. Siehe link:https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_hosts.html["Hosts in SnapCenter verwalten"] für weitere Informationen.


.Schritte
. Wählen Sie den Host auf der Seite *Hosts* aus, um das SnapCenter-Plug-in für SQL Server zu ändern und zu installieren.
. (Optional) Ersetzen Sie das SnapCenter-Plug-in für SQL Server-Konfigurationsdateien vom Disaster Recovery-Backup (DR) auf die neue Maschine.
. Importieren Sie Windows- und SQL-Zeitpläne aus dem SnapCenter-Plug-in für SQL Server-Ordner aus dem DR-Backup.


.Verwandte Informationen
Video ansehen link:https://www.youtube.com/watch?v=_8NG-tTGy8k&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["Disaster Recovery-APIs"^] .
