---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter verwendet Zugangsdaten, um Benutzer für SnapCenter-Vorgänge zu authentifizieren. Sie sollten Anmeldedaten für die Installation von SnapCenter-Plug-ins und zusätzliche Anmeldedaten für die Durchführung von Datenschutzvorgängen in Datenbanken oder Windows-Dateisystemen erstellen. 
---
= Richten Sie die Anmeldeinformationen für das SnapCenter-Plug-ins-Paket für Windows ein
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter verwendet Zugangsdaten, um Benutzer für SnapCenter-Vorgänge zu authentifizieren. Sie sollten Anmeldedaten für die Installation von SnapCenter-Plug-ins und zusätzliche Anmeldedaten für die Durchführung von Datenschutzvorgängen in Datenbanken oder Windows-Dateisystemen erstellen.

*Was Sie brauchen*

* Sie müssen Windows-Anmeldeinformationen einrichten, bevor Sie Plug-ins installieren.
* Sie müssen die Anmeldedaten mit Administratorrechten einrichten, einschließlich Administratorrechten auf dem Remote-Host.
* SQL-Authentifizierung auf Windows Hosts
+
Nach der Installation von Plug-ins müssen Sie SQL-Anmeldedaten einrichten.

+
Wenn Sie SnapCenter-Plug-in für Microsoft SQL Server bereitstellen, müssen Sie nach der Installation von Plug-ins SQL-Anmeldedaten einrichten. Richten Sie eine Anmeldedaten für einen Benutzer mit den sysadmin-Berechtigungen von SQL Server ein.

+
Die SQL-Authentifizierungsmethode authentifiziert sich anhand einer SQL Server-Instanz. Das bedeutet, dass eine SQL Server-Instanz in SnapCenter erkannt werden muss. Daher müssen Sie vor dem Hinzufügen von SQL-Anmeldeinformationen einen Host hinzufügen, Plug-in-Pakete installieren und Ressourcen aktualisieren. Sie benötigen die SQL Server-Authentifizierung für Vorgänge wie Planung oder Ermittlung von Ressourcen.



*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite Einstellungen auf *Credential*.
. Klicken Sie Auf *Neu*.
. Geben Sie auf der Seite Credential die Informationen an, die zum Konfigurieren von Anmeldeinformationen erforderlich sind:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Name der Anmeldeinformationen
 a| 
Geben Sie einen Namen für die Anmeldedaten ein.



 a| 
Benutzername/Passwort
 a| 
Geben Sie den Benutzernamen und das Kennwort ein, die zur Authentifizierung verwendet werden sollen.

** Domain-Administrator
+
Geben Sie den Domänenadministrator auf dem System an, auf dem Sie das SnapCenter-Plug-in installieren. Gültige Formate für das Feld Benutzername sind:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Lokaler Administrator (nur für Arbeitsgruppen)
+
Geben Sie bei Systemen, die zu einer Arbeitsgruppe gehören, den integrierten lokalen Administrator auf dem System an, auf dem Sie das SnapCenter-Plug-in installieren. Sie können ein lokales Benutzerkonto angeben, das zur lokalen Administratorengruppe gehört, wenn das Benutzerkonto über erhöhte Berechtigungen verfügt oder die Benutzerzugriffssteuerungsfunktion auf dem Hostsystem deaktiviert ist. Das zulässige Format für das Feld Benutzername lautet: `UserName`

+
Verwenden Sie keine Doppelzitate (") oder Rückkreuzzeichen (`) in den Kennwörtern. Sie sollten nicht das weniger als (<) und Ausrufezeichen (!) verwenden. Symbole in Kennwörtern. Zum Beispiel lessthan<!10, lessthan10<!, backtick`12.





 a| 
Authentifizierungsmodus
 a| 
Wählen Sie den Authentifizierungsmodus aus, den Sie verwenden möchten. Wenn Sie den SQL-Authentifizierungsmodus auswählen, müssen Sie auch die SQL-Serverinstanz und den Host angeben, auf dem sich die SQL-Instanz befindet.

|===
. Klicken Sie auf *OK*.


Nachdem Sie die Anmeldeinformationen eingerichtet haben, möchten Sie einem Benutzer oder einer Gruppe von Benutzern auf der Seite Benutzer und Zugriff die Wartung der Anmeldeinformationen zuweisen.
