---
permalink: protect-sce/concept_snapcenter_plug_in_for_exchange_server_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Exchange Server 
summary: Das SnapCenter Plug-in für Microsoft Exchange Server ist eine Host-seitige Komponente der NetAppSnapCenter Software, die das applikationsspezifische Datensicherungsmanagement von Exchange Datenbanken ermöglicht. Das Plug-in für Exchange automatisiert Backup und Restore von Exchange Datenbanken in Ihrer SnapCenter Umgebung. 
---
= Übersicht über das SnapCenter Plug-in für Microsoft Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SnapCenter Plug-in für Microsoft Exchange Server ist eine Host-seitige Komponente der NetApp SnapCenter Software, die das Management der applikationsspezifischen Datensicherung von Exchange Datenbanken ermöglicht. Das Plug-in für Exchange automatisiert Backup und Restore von Exchange Datenbanken in Ihrer SnapCenter Umgebung.

Wenn das Plug-in für Exchange installiert ist, können Sie mithilfe von SnapCenter mit NetApp SnapMirror Technologie gespiegelte Kopien von Backups auf einem anderen Volume erstellen. In diesem Fall ermöglicht NetApp SnapVault Technologie eine Disk-to-Disk-Backup-Replizierung, um Standard-Compliance- oder Archivierungszwecke zu erfüllen.

Wenn Sie E-Mails oder Mailboxen statt der gesamten Exchange Datenbank wiederherstellen möchten, können Sie die Single Mailbox Recovery (SMBR) Software verwenden.
