---
permalink: protect-sce/reference_granular_recovery_of_mails_and_mailbox.html 
sidebar: sidebar 
keywords: SMBR, Single Mailbox recovery, Exchange database 
summary: 'Die Single Mailbox Recovery Software (SMBR) ermöglicht es Ihnen, Mails oder Postfächer anstelle der gesamten Exchange Datenbank wiederherzustellen.' 
---
= Granulares Recovery von Mails und Mailboxen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Single Mailbox Recovery Software (SMBR) ermöglicht es Ihnen, Mails oder Postfächer anstelle der gesamten Exchange Datenbank wiederherzustellen.

Das Wiederherstellen einer vollständigen Datenbank für die Wiederherstellung einer einzelnen Mail benötigt viel Zeit und Ressourcen. SMBR hilft bei der schnellen Wiederherstellung der Mails durch die Erstellung von Klonkopien des Snapshots und dann mit Microsoft APIs, um die Mailbox in SMBR zu mounten. Weitere Informationen zur Verwendung von SMBR finden Sie unter https://library.netapp.com/ecm/ecm_download_file/ECMLP2871407["SMBR – Administratorhandbuch"^].

*Weitere Informationen*

* link:../install/concept_snapcenter_licenses.html#single-mailbox-recovery-smbr-licenses["SMBR-Lizenzen"^]
* https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30035["SMBR-Dokumentationsbibliothek"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Single_Mailbox_Recovery_(SMBR)/How_to_restore_from_secondary_storage_in_SMBR_with_SnapCenter["Wiederherstellung aus dem sekundären Storage in SMBR mit SnapCenter"^]
* https://www.youtube.com/watch?v=fOMuaaXrreI&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg&index=3["Wiederherstellung von Microsoft Exchange Mail über SnapVault mit SMBR"^]

