---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter verwendet Zugangsdaten, um Benutzer für SnapCenter-Vorgänge zu authentifizieren. Sie sollten Anmeldedaten für die Installation des Plug-in-Pakets und zusätzliche Anmeldedaten für die Durchführung von Datenschutzvorgängen in Datenbanken erstellen. 
---
= Richten Sie die Anmeldeinformationen für das SnapCenter-Plug-in für Windows ein
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter verwendet Zugangsdaten, um Benutzer für SnapCenter-Vorgänge zu authentifizieren. Sie sollten Anmeldedaten für die Installation des Plug-in-Pakets und zusätzliche Anmeldedaten für die Durchführung von Datenschutzvorgängen in Datenbanken erstellen.

*Über diese Aufgabe*

Sie müssen Anmeldedaten für die Installation von Plug-ins auf Windows-Hosts einrichten. Obwohl Sie nach der Implementierung von Hosts und der Installation von Plug-ins Anmeldedaten für Windows erstellen können, sollten Sie vor der Implementierung von Hosts und Plug-ins zunächst die Anmeldedaten nach dem Hinzufügen von SVMs erstellen.

Richten Sie die Anmeldedaten mit Administratorrechten ein, einschließlich Administratorrechten auf dem Remote-Host.

Wenn Sie Anmeldedaten für einzelne Ressourcengruppen einrichten und der Benutzername nicht über vollständige Administratorrechte verfügt, müssen Sie dem Benutzernamen mindestens die Ressourcengruppe und die Sicherungsberechtigungen zuweisen.

*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite Einstellungen auf *Credential*.
. Klicken Sie Auf *Neu*.
+
Das Fenster Credential wird angezeigt.

. Gehen Sie auf der Seite Credential wie folgt vor:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Name der Anmeldeinformationen
 a| 
Geben Sie einen Namen für die Anmeldedaten ein.



 a| 
Benutzername
 a| 
Geben Sie den Benutzernamen ein, der für die Authentifizierung verwendet wird.

** Domänenadministrator oder ein beliebiges Mitglied der Administratorgruppe
+
Geben Sie den Domänenadministrator oder ein Mitglied der Administratorgruppe auf dem System an, auf dem Sie das SnapCenter-Plug-in installieren. Gültige Formate für das Feld Benutzername sind:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Lokaler Administrator (nur für Arbeitsgruppen)
+
Geben Sie bei Systemen, die zu einer Arbeitsgruppe gehören, den integrierten lokalen Administrator auf dem System an, auf dem Sie das SnapCenter-Plug-in installieren. Sie können ein lokales Benutzerkonto angeben, das zur lokalen Administratorengruppe gehört, wenn das Benutzerkonto über erhöhte Berechtigungen verfügt oder die Benutzerzugriffssteuerungsfunktion auf dem Hostsystem deaktiviert ist. Das zulässige Format für das Feld Benutzername lautet: `UserName`





 a| 
Passwort
 a| 
Geben Sie das für die Authentifizierung verwendete Passwort ein.



 a| 
Authentifizierung
 a| 
Wählen Sie Windows als Authentifizierungsmodus aus.

|===
. Klicken Sie auf *OK*.

