---
permalink: protect-sce/task_add_hosts_and_install_plug_in_for_exchange.html 
sidebar: sidebar 
keywords:  
summary: Sie können die Seite SnapCenterAdd Host verwenden, um Windows-Hosts hinzuzufügen. Das Plug-in für Exchange wird automatisch auf dem angegebenen Host installiert. Dies ist die empfohlene Methode zum Installieren von Plug-ins. Sie können einen Host hinzufügen und ein Plug-in entweder für einen einzelnen Host oder ein Cluster installieren. 
---
= Fügen Sie Hosts hinzu und installieren Sie das Plug-in für Exchange
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Seite SnapCenter Add Host verwenden, um Windows Hosts hinzuzufügen. Das Plug-in für Exchange wird automatisch auf dem angegebenen Host installiert. Dies ist die empfohlene Methode zum Installieren von Plug-ins. Sie können einen Host hinzufügen und ein Plug-in entweder für einen einzelnen Host oder ein Cluster installieren.

*Was Sie brauchen*

* Sie müssen ein Benutzer sein, der einer Rolle zugewiesen ist, die über die Plug-in-Installations- und Deinstallationsberechtigungen verfügt, wie z. B. die SnapCenter-Admin
* Wenn Sie ein Plug-in auf einem Windows-Host installieren, wenn Sie keine Anmeldedaten angeben oder der Benutzer zu einem lokalen Workgroup-Benutzer gehört, müssen Sie UAC auf dem Host deaktivieren.
* Der Nachrichtenwarteschlange-Service muss ausgeführt werden.
* Wenn Sie Group Managed Service Account (gMSA) verwenden, sollten Sie gMSA mit Administratorrechten konfigurieren. Weitere Informationen finden Sie unterlink:task_configure_gMSA_on_windows_server_2012_or_later.html["Konfigurieren Sie das Gruppenkonto für Managed Services unter Windows Server 2012 oder höher für Microsoft Exchange Server"^].


*Über diese Aufgabe*

* Sie können einen SnapCenter-Server nicht als Plug-in-Host zu einem anderen SnapCenter-Server hinzufügen.
* Sie können einen Host hinzufügen und Plug-in-Pakete für einen einzelnen Host oder Cluster installieren.
* Ist ein Exchange-Knoten Teil einer DAG, kann der SnapCenter-Server nicht nur einen Knoten hinzufügen.
* Wenn Sie Plug-ins auf einem Cluster (Exchange DAG) installieren, werden sie auf allen Knoten des Clusters installiert, selbst wenn einige Knoten keine Datenbanken auf NetApp LUNs haben.


Ab SnapCenter 4.6 unterstützt SCE die Mandantenfähigkeit und Sie können einen Host über die folgenden Methoden hinzufügen:

|===
| Fügen Sie einen Host-Vorgang hinzu | 4.5 und früher | 4.6 und höher 


| Fügen Sie IP-lose DAG in einer anderen Domäne oder anderen Domäne hinzu | Nicht unterstützt | Unterstützt 


| Fügen Sie mehrere IP-DAGs mit eindeutigen Namen hinzu. Diese befinden sich in derselben oder in mehreren Domänen | Unterstützt | Unterstützt 


| Fügen Sie mehrere IP- oder IP-lose DAGs mit denselben Host-Namen und/oder DB-Namen in Cross-Domain hinzu | Nicht unterstützt | Unterstützt 


| Hinzufügen mehrerer IP/IP-loser DAGs mit demselben Namen und domänenübergreifender | Nicht unterstützt | Unterstützt 


| Fügen Sie mehrere Standalone-Hosts mit demselben Namen und domänenübergreifender Infrastruktur hinzu | Nicht unterstützt | Unterstützt 
|===
Plug-in für Exchange hängt vom SnapCenter Plug-ins-Paket für Windows ab, die Versionen müssen identisch sein. Während der Installation von Plug-in für Exchange wird das SnapCenter Plug-ins Paket für Windows standardmäßig ausgewählt und zusammen mit dem VSS-Hardwareanbieter installiert.

Falls SnapManager für Microsoft Exchange Server und SnapDrive für Windows bereits installiert sind, Und Sie möchten Plug-in für Exchange auf demselben Exchange-Server installieren, müssen Sie den von SnapDrive für Windows verwendeten VSS Hardware-Anbieter deaktivieren, da er mit dem VSS Hardware Provider, der mit Plug-in für Exchange und SnapCenter Plug-ins Package für Windows installiert ist, nicht kompatibel ist. Weitere Informationen finden Sie unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_manually_register_the_Data_ONTAP_VSS_Hardware_Provider["So registrieren Sie den Data ONTAP VSS Hardware Provider manuell"].

*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Hosts*.
. Vergewissern Sie sich, dass *verwaltete Hosts* oben ausgewählt ist.
. Klicken Sie Auf *Hinzufügen*.
. Gehen Sie auf der Seite Hosts wie folgt vor:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Host-Typ
 a| 
Wählen Sie als Hosttyp * Windows* aus.

SnapCenter Server fügt den Host hinzu und installiert dann auf dem Host das Plug-in für Windows und das Plug-in für Exchange, falls sie nicht bereits installiert sind.

Plug-in für Windows und Plug-in für Exchange müssen die gleiche Version sein. Wenn zuvor eine andere Version des Plug-ins für Windows installiert wurde, aktualisiert SnapCenter die Version als Teil der Installation.



 a| 
Host-Name
 a| 
Geben Sie den vollständig qualifizierten Domänennamen (FQDN) oder die IP-Adresse des Hosts ein.

SnapCenter hängt von der richtigen Konfiguration des DNS ab. Daher empfiehlt es sich, den vollständig qualifizierten Domänennamen (FQDN) einzugeben.

Eine IP-Adresse wird nur für nicht vertrauenswürdige Domänenhosts unterstützt, wenn sie auf den FQDN auflöst.

Wenn Sie einen Host mit SnapCenter hinzufügen und dieser Teil einer Unterdomäne ist, müssen Sie den FQDN angeben.

Sie können IP-Adressen oder den FQDN einer der folgenden Adressen eingeben:

** Eigenständiger Host
** Exchange DAG
+
Vorteile einer Exchange DAG:

+
*** Fügen Sie eine DAG hinzu, indem Sie den DAG-Namen, die DAG-IP-Adresse, den Node-Namen oder die Node-IP-Adresse angeben.
*** Fügen Sie den DAG-Cluster ohne IP hinzu, indem Sie die IP-Adresse oder den FQDN eines der DAG-Cluster-Nodes angeben.
*** Fügen Sie IP-lose DAG hinzu, die sich in derselben Domäne oder einer anderen Domäne befindet. Sie können auch mehrere IP/IP-basierte DAGs mit demselben Namen und aber verschiedenen Domänen hinzufügen.





NOTE: Für einen eigenständigen Host oder eine Exchange-DAG (domänenübergreifend oder gleiche Domäne) wird empfohlen, FQDN oder die IP-Adresse des Hosts oder der DAG bereitzustellen.



 a| 
Anmeldedaten
 a| 
Wählen Sie den von Ihnen erstellten Anmeldeinformationsnamen aus, oder erstellen Sie die neuen Anmeldeinformationen.

Die Anmeldeinformationen müssen über Administratorrechte auf dem Remote-Host verfügen. Weitere Informationen finden Sie unter Informationen zum Erstellen von Anmeldeinformationen.

Sie können Details zu den Anmeldeinformationen anzeigen, indem Sie den Cursor über den von Ihnen angegebenen Anmeldeinformationsnamen positionieren.


NOTE: Der Authentifizierungsmodus für die Anmeldeinformationen wird durch den Hosttyp bestimmt, den Sie im Assistenten zum Hinzufügen von Hosts angeben.

|===
. Wählen Sie im Abschnitt Plug-ins zum Installieren auswählen die zu installierenden Plug-ins aus.
+
Wenn Sie Plug-in für Exchange auswählen, wird das SnapCenter-Plug-in für Microsoft SQL Server automatisch deaktiviert. Microsoft empfiehlt, dass SQL Server und Exchange-Server aufgrund der verwendeten Speichermenge und anderer von Exchange benötigten Ressourcen nicht auf demselben System installiert werden.

. (Optional) Klicken Sie Auf *Weitere Optionen*.
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Port
 a| 
Behalten Sie die Standard-Port-Nummer bei oder geben Sie die Port-Nummer an.

Die Standardanschlussnummer ist 8145. Wenn der SnapCenter-Server auf einem benutzerdefinierten Port installiert wurde, wird diese Portnummer als Standardport angezeigt.


NOTE: Wenn Sie die Plug-ins manuell installiert und einen benutzerdefinierten Port angegeben haben, müssen Sie denselben Port angeben. Andernfalls schlägt der Vorgang fehl.



 a| 
Installationspfad
 a| 
Der Standardpfad lautet `C:\Program Files\NetApp\SnapCenter`.

Optional können Sie den Pfad anpassen.



 a| 
Fügen Sie alle Hosts in der DAG hinzu
 a| 
Aktivieren Sie dieses Kontrollkästchen, wenn Sie eine DAG hinzufügen.



 a| 
Überspringen Sie die Prüfungen vor der Installation
 a| 
Aktivieren Sie dieses Kontrollkästchen, wenn Sie die Plug-ins bereits manuell installiert haben und nicht überprüfen möchten, ob der Host die Anforderungen für die Installation des Plug-ins erfüllt.



 a| 
Verwenden Sie Group Managed Service Account (gMSA), um die Plug-in-Dienste auszuführen
 a| 
Aktivieren Sie dieses Kontrollkästchen, wenn Sie die Plug-in-Dienste über das Group Managed Service Account (gMSA) ausführen möchten.

Geben Sie den gMSA-Namen in folgendem Format an: _Domainname\AccountName€_.


NOTE: GSSA wird nur für den SnapCenter-Plug-in für Windows-Dienst als Anmelde-Dienstkonto verwendet.

|===
. Klicken Sie Auf *Absenden*.
+
Wenn Sie das Kontrollkästchen Vorabprüfungen nicht aktiviert haben, wird der Host validiert, um festzustellen, ob es die Anforderungen für die Installation des Plug-ins erfüllt. Wenn die Mindestanforderungen nicht erfüllt werden, werden die entsprechenden Fehler- oder Warnmeldungen angezeigt.

+
Wenn der Fehler mit dem Festplattenspeicher oder RAM zusammenhängt, können Sie die Datei Web.config unter aktualisieren `C:\Program Files\NetApp\SnapCenter` WebApp zum Ändern der Standardwerte. Wenn der Fehler mit anderen Parametern zusammenhängt, müssen Sie das Problem beheben.

+

NOTE: Wenn Sie in einem HA-Setup die Datei „Web.config“ aktualisieren, müssen Sie die Datei auf beiden Knoten aktualisieren.

. Überwachen Sie den Installationsfortschritt.

