---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords:  
summary: Sie können eine Backup-Richtlinie für die Exchange-Ressourcen oder für die Ressourcengruppen erstellen, bevor Sie SnapCenter zum Sichern von Microsoft Exchange Server-Ressourcen verwenden. Alternativ können Sie beim Erstellen einer Ressourcengruppen oder beim Backup einer einzelnen Ressource eine Backup-Richtlinie erstellen. 
---
= Erstellen von Backup-Richtlinien für Exchange Server-Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Backup-Richtlinie für die Exchange-Ressourcen oder für die Ressourcengruppen erstellen, bevor Sie SnapCenter zum Sichern von Microsoft Exchange Server-Ressourcen verwenden. Alternativ können Sie beim Erstellen einer Ressourcengruppen oder beim Backup einer einzelnen Ressource eine Backup-Richtlinie erstellen.

*Was Sie brauchen*

* Sie müssen Ihre Datensicherungsstrategie definiert haben.
+
Weitere Informationen finden Sie in den Informationen zur Definition einer Datensicherungsstrategie für Exchange Datenbanken.

* Sie müssen auf die Datensicherung vorbereitet sein, indem Sie Aufgaben wie das Installieren von SnapCenter, das Hinzufügen von Hosts, die Identifizierung von Ressourcen und das Erstellen von Verbindungen zum Storage-System abschließen.
* Sie müssen die Exchange Server-Ressourcen aktualisiert (erkannt) haben.
* Wenn Sie Snapshot Kopien in eine Spiegelung oder einen Vault replizieren, muss der SnapCenter Administrator Ihnen die Storage Virtual Machines (SVMs) sowohl für die Quell-Volumes als auch die Ziel-Volumes zugewiesen haben.
* Wenn Sie die PowerShell Skripte in Prescripts und Postscripts ausführen möchten, sollten Sie den Wert der Datei einstellen `usePowershellProcessforScripts` Parameter auf „true“ im anzeigen `web.config` Datei:
+
Der Standardwert ist false



*Über diese Aufgabe*

* Eine Backup-Richtlinie ist eine Reihe von Regeln, die festlegen, wie Backups gemanagt und aufbewahrt werden und wie oft die Ressourcen- oder Ressourcengruppe gesichert wird. Außerdem können Sie Skripteinstellungen festlegen. Durch das Festlegen von Optionen in einer Richtlinie wird Zeit eingespart, wenn die Richtlinie für eine andere Ressourcengruppe wiederverwendet werden soll.
* Eine vollständige Backup-Aufbewahrung ist spezifisch für eine bestimmte Richtlinie. Eine Datenbank oder Ressource, die Richtlinien A mit einer vollständigen Backup-Aufbewahrung von 4 verwendet, behält 4 volle Backups bei und hat keine Auswirkungen auf Richtlinie B für die gleiche Datenbank oder Ressource, die möglicherweise eine Aufbewahrung von 3 haben, um 3 vollständige Backups aufzubewahren.
* Die Backup-Aufbewahrung von Protokollen ist über alle Richtlinien hinweg wirksam und wird für alle Backup-Protokollierung einer Datenbank oder Ressource angewendet. Wenn ein vollständiges Backup mit Richtlinie B durchgeführt wird, wirkt sich die Einstellung für die Protokollaufbewahrung auf die von Richtlinie A erstellten Protokoll-Backups in derselben Datenbank oder Ressource aus. Ebenso wirkt sich die Einstellung für die Protokollaufbewahrung für Policy A auf die von Richtlinie B erstellten Protokoll-Backups in derselben Datenbank aus.
* DER SCRIPTS_PATH wird mit dem PredefinedWindowsScriptDirectory-Schlüssel definiert, der sich in der SMCoreServiceHost.exe.Config-Datei des Plug-in-Hosts befindet.
+
Bei Bedarf können Sie diesen Pfad ändern und den SMCore Service neu starten. Es wird empfohlen, den Standardpfad für die Sicherheit zu verwenden.

+
Der Wert des Schlüssels kann von Swagger über die API angezeigt werden: API /4.7/configsettings

+
Sie können die GET API verwenden, um den Wert der Taste anzuzeigen. SET-API wird nicht unterstützt.



|===


| *Best Practice:* Es ist am besten, dass Sie die sekundäre Aufbewahrungsrichtlinie auf der Grundlage der Anzahl der vollständigen und Log-Backups insgesamt konfigurieren, die Sie behalten möchten. Wenn Sie sekundäre Aufbewahrungsrichtlinien konfigurieren, sollten Sie bedenken, dass bei Datenbanken und Protokollen, die in verschiedenen Volumes vorhanden sind, jedes Backup drei Snapshot Kopien haben kann. Wenn sich Datenbanken und Protokolle in demselben Volume befinden, kann jedes Backup zwei Snapshot Kopien haben. 
|===
*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite Einstellungen auf *Richtlinien*.
. Klicken Sie Auf *Neu*.
. Geben Sie auf der Seite Name den Namen und die Beschreibung der Richtlinie ein.
. Führen Sie auf der Seite Sicherungstyp die folgenden Schritte durch:
+
.. Wählen Sie den Sicherungstyp:
+
|===
| Ihr Ziel ist | Tun Sie das... 


 a| 
Sichern Sie die Datenbankdateien und die erforderlichen Transaktions-Logs
 a| 
Wählen Sie *Vollbackup und Log Backup* aus.

Datenbanken werden durch Log-Verkürzung gesichert und alle Protokolle werden gesichert, einschließlich der gekürzten Protokolle.


NOTE: Dies ist der empfohlene Backup-Typ.



 a| 
Sichern Sie die Datenbankdateien und die nicht gesicherten Transaktionsprotokolle
 a| 
Wählen Sie * Vollbackup* aus.

Datenbanken werden durch Log-Verkürzung gesichert, gekürzte Protokolle werden nicht gesichert.



 a| 
Sichern Sie alle Transaktions-Logs
 a| 
Wählen Sie *Backup protokollieren*.

Alle Transaktions-Logs auf dem aktiven File-System werden gesichert, und es gibt keine Log-Verkürzung.

Ein Verzeichnis _sceBackupinfo_ wird auf derselben Festplatte erstellt wie das Live Log. Dieses Verzeichnis enthält den Zeiger auf die inkrementellen Änderungen für die Exchange-Datenbank und entspricht nicht den vollständigen Log-Dateien.



 a| 
Sichern Sie alle Datenbank- und Transaktions-Logs, ohne die Transaktions-Log-Dateien zu beeinträchtigen
 a| 
Wählen Sie *Backup Kopieren*.

Alle Datenbanken und Protokolle werden gesichert, und es gibt keine Log-Verkürzung. In der Regel verwenden Sie diesen Backup-Typ für das erneutes Seeding einer Kopie oder zum Testen oder zur Diagnose eines Problems.

|===
+

NOTE: Sie sollten den für die Protokoll-Backups benötigten Speicherplatz basierend auf der vollständigen Backup-Aufbewahrung definieren, nicht auf der Grundlage einer up-to-the-minute-Aufbewahrung (UTM).

.. Wählen Sie im Abschnitt Einstellungen für Datenbankverfügbarkeitsgruppen eine Aktion aus:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Sichern Sie aktive Kopien
 a| 
Wählen Sie diese Option aus, um nur die aktiven Kopien der ausgewählten Datenbank zu sichern.

Bei Datenbankverfügbarkeitsgruppen (Database Availability Groups, DAGs) werden mit dieser Option nur aktive Kopien aller Datenbanken in der DAG gesichert.

Passive Kopien werden nicht gesichert.



 a| 
Sichern Sie Kopien auf Servern, die zum Erstellungszeitpunkt des Backup-Jobs ausgewählt werden sollen
 a| 
Wählen Sie diese Option aus, um alle Kopien der Datenbanken auf den ausgewählten Servern zu sichern, sowohl aktiv als auch passiv.

Bei DAGs sichert diese Option sowohl aktive als auch passive Kopien aller Datenbanken auf den ausgewählten Servern.

|===
+

NOTE: Bei Cluster-Konfigurationen werden die Backups entsprechend den in der Richtlinie festgelegten Aufbewahrungseinstellungen auf jedem Node des Clusters aufbewahrt. Wenn sich der Owner-Node des Clusters ändert, werden die Backups des vorherigen Owner-Node beibehalten. Die Aufbewahrung gilt nur auf Node-Ebene.

.. Wählen Sie im Abschnitt Terminfrequenz einen oder mehrere der Frequenztypen aus: *On Demand*, *hourly*, *Daily*, *Weekly* und *Monthly*.
+

NOTE: Sie können den Zeitplan (Startdatum, Enddatum) für Sicherungsvorgänge beim Erstellen einer Ressourcengruppe angeben. So können Sie Ressourcengruppen erstellen, die dieselben Richtlinien- und Backup-Häufigkeit verwenden, aber Sie können jeder Richtlinie verschiedene Backup-Zeitpläne zuweisen.

+

NOTE: Wenn Sie für 2:00 Uhr geplant sind, wird der Zeitplan während der Sommerzeit (DST) nicht ausgelöst.



. Konfigurieren Sie auf der Seite Aufbewahrung die Aufbewahrungseinstellungen.
+
Die angezeigten Optionen hängen vom Backup-Typ und vom Frequenztyp ab, den Sie zuvor ausgewählt haben.

+

NOTE: Der maximale Aufbewahrungswert ist 1018 für Ressourcen auf ONTAP 9.4 oder höher und 254 für Ressourcen unter ONTAP 9.3 oder einer früheren Version. Backups schlagen fehl, wenn die Aufbewahrung auf einen Wert festgelegt ist, der höher ist, als die zugrunde liegende ONTAP Version unterstützt.

+

IMPORTANT: Sie müssen die Aufbewahrungsanzahl auf 2 oder höher einstellen, wenn Sie die SnapVault-Replikation aktivieren möchten. Wenn Sie die Aufbewahrungsanzahl auf 1 festlegen, kann der Aufbewahrungsvorgang möglicherweise fehlschlagen, da die erste Snapshot Kopie die Referenzkopie für die SnapVault-Beziehung ist, bis eine neuere Snapshot Kopie auf das Ziel repliziert wird.

+
.. Wählen Sie im Abschnitt Einstellungen für die Aufbewahrung von Protokollsicherungen eine der folgenden Optionen aus:
+
|===
| Ihr Ziel ist | Tun Sie das... 


 a| 
Bewahren Sie nur eine bestimmte Anzahl von Protokoll-Backups auf
 a| 
Wählen Sie *Anzahl der vollständigen Backups, für die Protokolle aufbewahrt werden*, und geben Sie die Anzahl der vollständigen Backups an, für die Sie eine zeitnahe Wiederherstellung wünschen.

Die up-to-the-minute (UTM) Aufbewahrung gilt für die Protokollierung der Backups, die über vollständige Backups oder das Log-Backup erstellt wurden. Wenn die UTM-Aufbewahrungseinstellungen beispielsweise so konfiguriert sind, dass die Protokollsicherungen der letzten 5 vollständigen Backups gespeichert werden, werden die Protokoll-Backups der letzten 5 vollständigen Backups beibehalten.

Die im Rahmen der vollständigen und der Log-Backups erstellten Protokollordner werden automatisch als Teil von UTM gelöscht. Sie können die Protokollordner nicht manuell löschen. Wenn z. B. die Aufbewahrungseinstellung für vollständige oder vollständige Backup und Log-Sicherung für einen Monat festgelegt ist und die UTM-Aufbewahrung auf 10 Tage festgelegt ist, wird der im Rahmen dieser Backups erstellte Log-Ordner wie pro UTM gelöscht. Dadurch sind nur 10 Tage Protokollordner vorhanden und alle anderen Backups sind für die Point-in-Time-Wiederherstellung markiert.

Sie können den UTM-Aufbewahrungswert auf 0 einstellen, wenn Sie keine minutengenaue Wiederherstellung durchführen möchten. Dies ermöglicht den Point-in-Time Restore-Vorgang.

*Best Practice:* Es ist am besten, dass die Einstellung der Einstellung für Total Snapshot Kopien (vollständige Backups) im Abschnitt Einstellungen für vollständige Backup-Aufbewahrung entspricht. Dadurch wird sichergestellt, dass Protokolldateien für jedes vollständige Backup aufbewahrt werden.



 a| 
Bewahren Sie die Backup-Kopien für eine bestimmte Anzahl von Tagen auf
 a| 
Wählen Sie die Option *Protokollsicherungen für letzte* aufbewahren und geben Sie die Anzahl der Tage an, um die Backup-Kopien des Protokolls zu behalten.

Aufbewahrung der Log-Backups bis zur Anzahl von Tagen voller Backups.

|===
+
Wenn Sie als Backup-Typ *Log Backup* ausgewählt haben, werden Log-Backups als Teil der up-to-the-minute-Aufbewahrungseinstellungen für vollständige Backups beibehalten.

.. Wählen Sie im Abschnitt Einstellungen für vollständige Backups eine der folgenden Optionen für On-Demand-Backups aus, und wählen Sie dann eine für vollständige Backups aus:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Aufbewahrung von nur einer bestimmten Anzahl von Snapshot Kopien
 a| 
Wenn Sie die Anzahl der zu behaltenden vollständigen Backups angeben möchten, wählen Sie die Option *Gesamtanzahl der zu behaltenden Snapshot-Kopien* aus und geben Sie die Anzahl der beizubehaltenden Snapshot-Kopien (vollständige Backups) an.

Wenn die Anzahl der vollständigen Backups die angegebene Anzahl überschreitet, werden die vollständigen Backups, die die angegebene Anzahl überschreiten, gelöscht, wobei die ältesten Kopien zuerst gelöscht werden.



 a| 
Bewahren Sie vollständige Backups für eine bestimmte Anzahl an Tagen auf
 a| 
Wählen Sie die Option *Snapshot Kopien für* beibehalten und geben Sie die Anzahl der Tage an, um Snapshot Kopien zu behalten (vollständige Backups).

|===
+

NOTE: Wenn Sie eine Datenbank mit nur Protokollsicherungen und keinen vollständigen Backups auf einem Host in einer DAG-Konfiguration haben, werden die Protokoll-Backups auf folgende Weise beibehalten:

+
*** Standardmäßig findet SnapCenter auf allen anderen Hosts in der DAG das älteste volle Backup dieser Datenbank und löscht alle Log-Backups auf diesem Host, die vor dem vollständigen Backup erstellt wurden.
*** Sie können das oben genannte Standard-Aufbewahrungsverhalten für eine Datenbank auf einem Host in einer DAG mit nur Protokoll-Backups überschreiben, indem Sie den Schlüssel *MaxLogBackupOnlyCountWithfullBackup* in der Datei _C:\Programme\NetApp\SnapCenter WebApp\Web.config_ hinzufügen.
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
Im Beispiel bedeutet der Wert 10, dass Sie bis zu 10 Log-Backups auf dem Host aufbewahren.





. Wählen Sie auf der Seite Replikation eine oder beide der folgenden sekundären Replikationsoptionen aus:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Aktualisieren Sie SnapMirror nach dem Erstellen einer lokalen Snapshot Kopie
 a| 
Wählen Sie diese Option aus, um Spiegelkopien von Backup-Sets auf einem anderen Volume (SnapMirror) zu behalten.



 a| 
Aktualisieren Sie SnapVault nach dem Erstellen einer lokalen Snapshot Kopie
 a| 
Wählen Sie diese Option aus, um die Disk-to-Disk-Backup-Replikation durchzuführen.



 a| 
Sekundäres Policy-Label
 a| 
Wählen Sie eine Snapshot-Bezeichnung aus.

Abhängig von dem ausgewählten Etikett der Snapshot Kopie wendet ONTAP die Aufbewahrungsrichtlinie für sekundäre Snapshot Kopien an, die mit dem Etikett übereinstimmt.


NOTE: Wenn Sie *Update SnapMirror nach dem Erstellen einer lokalen Snapshot Kopie* ausgewählt haben, können Sie optional das Label für die sekundäre Richtlinie angeben. Wenn Sie jedoch *Update SnapVault nach dem Erstellen einer lokalen Snapshot Kopie* ausgewählt haben, sollten Sie das sekundäre Policy Label angeben.



 a| 
Fehler bei Wiederholungszählung
 a| 
Geben Sie die Anzahl der Replikationsversuche ein, die vor dem Anhalten des Prozesses auftreten sollen.

|===
+

NOTE: Sie sollten die SnapMirror Aufbewahrungsrichtlinie in ONTAP für den sekundären Storage konfigurieren, um zu vermeiden, dass die maximale Anzahl an Snapshot Kopien auf dem sekundären Storage erreicht wird.

. Geben Sie auf der Seite Skript den Pfad und die Argumente des Vorskripts bzw. des Postskripts ein, die vor bzw. nach dem Backup ausgeführt werden sollen.
+
** Zu den vorkript-Backup-Argumenten gehören „` USD Datenbank`“ und „` USD ServerInstance`“.
** Zu den PostScript-Backup-Argumenten gehören „` USD Datenbank`“, „` USD ServerInstance`“, „` USD BackupName`“, „` USD LogDirectory`“ und „` USD LogSnapshot`“.
+
Sie können ein Skript ausführen, um SNMP-Traps zu aktualisieren, Warnmeldungen zu automatisieren, Protokolle zu senden usw.

+

NOTE: Der Pfad für Prescripts oder Postscripts darf keine Laufwerke oder Shares enthalten. Der Pfad sollte relativ zum SCRIPTS_PATH sein.



. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig stellen*.

