---
permalink: protect-sce/task_reseed_a_passive_exchange_node_replica.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie eine Replikatkopie erneut übertragen müssen, beispielsweise wenn eine Kopie beschädigt ist, können Sie sie mithilfe der Funktion zum erneuten Seeding in SnapCenter erneut in das neueste Backup übertragen. 
---
= Erneutes Seeding eines passiven Exchange Node-Replikats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine Replikatkopie erneut übertragen müssen, beispielsweise wenn eine Kopie beschädigt ist, können Sie sie mithilfe der Funktion zum erneuten Seeding in SnapCenter erneut in das neueste Backup übertragen.

*Was Sie brauchen*

* Sie müssen SnapCenter Server 4.1 oder höher und Plug-in für Exchange 4.1 oder höher verwenden.
+
Erneutes Seeding eines Replikats wird in SnapCenter-Versionen vor 4.1 nicht unterstützt.

* Sie müssen eine Sicherung der Datenbank erstellt haben, die Sie erneut senden möchten.


|===


| *Best Practice:* um einen Rückgang zwischen den Knoten zu vermeiden, empfehlen wir Ihnen, entweder ein neues Backup zu erstellen, bevor Sie einen erneuten Vorgang durchführen, oder den Host mit dem neuesten Backup auszuwählen. 
|===
*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Ressourcen* und wählen Sie dann *Microsoft Exchange Server Plug-in* aus der Liste aus.
. Wählen Sie auf der Seite Ressourcen die entsprechende Option aus der Liste Ansicht aus:
+
|===
| Option | Beschreibung 


 a| 
Zum erneuten Seeding einer einzelnen Datenbank
 a| 
Wählen Sie in der Liste Ansicht die Option *Datenbank* aus.



 a| 
Zum erneuten Seeding von Datenbanken in einer DAG
 a| 
Wählen Sie in der Liste View die Option *Database Availability Group* aus.

|===
. Wählen Sie die Ressource aus, die erneut gesendet werden soll.
. Klicken Sie auf der Seite Kopien verwalten auf *erneut*.
. Wählen Sie aus der Liste der ungesunden Datenbankkopien im Assistenten zum erneuten Seeding den aus, den Sie erneut speichern möchten, und klicken Sie dann auf *Weiter*.
. Wählen Sie im Host-Fenster den Host mit dem Backup aus, von dem Sie erneut starten möchten, und klicken Sie dann auf *Weiter*.
. Wählen Sie auf der Benachrichtigungsseite aus der Dropdown-Liste *E-Mail-Präferenz* die Szenarien aus, in denen Sie die E-Mails versenden möchten.
+
Außerdem müssen Sie die E-Mail-Adressen für Absender und Empfänger sowie den Betreff der E-Mail angeben.

. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig stellen*.
. Sie können den Status des Jobs anzeigen, indem Sie das Aktivitätsfenster unten auf der Seite erweitern.
+

NOTE: Ein erneutes Seeding wird nicht unterstützt, wenn die passive Datenbankkopie auf Storage anderer Anbieter liegt.


