---
permalink: protect-sce/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_exchange_database.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Bevor Sie PowerShell cmdlets verwenden können, müssen Sie eine SVM-Verbindung (Storage Virtual Machine) und Zugangsdaten erstellen, um ein Backup und eine Wiederherstellung durchzuführen.' 
---
= Erstellen Sie eine Storage-Systemverbindung und Zugangsdaten mit PowerShell cmdlets für Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie PowerShell cmdlets verwenden können, müssen Sie eine SVM-Verbindung (Storage Virtual Machine) und Zugangsdaten erstellen, um ein Backup und eine Wiederherstellung durchzuführen.

*Was Sie brauchen*

* Sie sollten die PowerShell Umgebung auf die Ausführung der PowerShell Commandlets vorbereitet haben.
* Sie sollten die erforderlichen Berechtigungen in der Rolle „Infrastrukturadministrator“ besitzen, um Speicherverbindungen zu erstellen.
* Sie sollten sicherstellen, dass die Plug-in-Installationen nicht ausgeführt werden.
+
Die Host-Plug-in-Installationen dürfen beim Hinzufügen einer Speichersystemverbindung nicht ausgeführt werden, da der Host-Cache möglicherweise nicht aktualisiert wird und der Datenbank-Status in der SnapCenter GUI unter „`not available for Backup`“ oder „`not on NetApp Storage`“ angezeigt werden kann.

* Speichersystemnamen sollten eindeutig sein.
+
SnapCenter unterstützt nicht mehrere Storage-Systeme mit demselben Namen auf verschiedenen Clustern. Jedes von SnapCenter unterstützte Storage-System sollte über einen eindeutigen Namen und eine eindeutige LIF-IP-Adresse für Daten verfügen.



*Schritte*

. Initiieren Sie eine PowerShell Verbindungssitzung mithilfe von `Open-SmConnection` Cmdlet:
+
In diesem Beispiel wird eine PowerShell Sitzung geöffnet:

+
[listing]
----
PS C:\> Open-SmConnection
----
. Erstellen Sie mit den eine neue Verbindung zum Storage-System `Add-SmStorageConnection` Cmdlet:
+
In diesem Beispiel wird eine neue Speichersystemverbindung erstellt:

+
[listing]
----
PS C:\> Add-SmStorageConnection -SVM test_vs1 -Protocol Https
-Timeout 60
----
. Erstellen Sie mithilfe des einen neuen Run as-Account `Add-Credential` Cmdlet:
+
In diesem Beispiel wird ein neuer Lauf als Konto mit dem Namen ExchangeAdmin mit Windows-Anmeldeinformationen erstellt:

+
[listing]
----
PS C:> Add-SmCredential -Name ExchangeAdmin -AuthMode Windows
-Credential sddev\administrator
----


Die Informationen zu den Parametern, die mit dem Cmdlet und deren Beschreibungen verwendet werden können, können durch Ausführen von _get-Help Command_Name_ abgerufen werden. Alternativ können Sie auch auf die verweisen https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["SnapCenter Software Cmdlet Referenzhandbuch"^].
