---
sidebar: sidebar 
permalink: legal-notices.html 
keywords: copyrights, notice, trademarks, patents, privacy, open source 
summary: Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr. 
---
= Rechtliche Hinweise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr.



== Urheberrecht

http://www.netapp.com/us/legal/copyright.aspx["http://www.netapp.com/us/legal/copyright.aspx"]



== Marken

NetApp, das NETAPP Logo und die auf der NetApp Markenseite aufgeführten Marken sind Marken von NetApp Inc. Andere Firmen- und Produktnamen können Marken der jeweiligen Eigentümer sein.

http://www.netapp.com/us/legal/netapptmlist.aspx["http://www.netapp.com/us/legal/netapptmlist.aspx"]



== Patente

Eine aktuelle Liste der NetApp Patente finden Sie unter:

https://www.netapp.com/us/media/patents-page.pdf["https://www.netapp.com/us/media/patents-page.pdf"]



== Datenschutzrichtlinie

https://www.netapp.com/us/legal/privacypolicy/index.aspx["https://www.netapp.com/us/legal/privacypolicy/index.aspx"]



== Maschinelle Übersetzung

Wichtige Informationen zu lokalisierten Inhalten.

https://www.netapp.com/company/legal/machine-translation/["https://www.netapp.com/company/legal/machine-translation/"]



== Open Source

Stellt Informationen über das Urheberrecht und die Lizenzen Dritter bereit, die in diesem Produkt verwendet werden. Ihr Produkt verwendet nicht unbedingt alle unten genannten Softwarekomponenten.

https://library.netapp.com/ecm/ecm_download_file/ECMLP2883298["Hinweis zu SnapCenter 4.7"^]
