---
permalink: protect-scw/concept_how_snapcenter_backs_up_windows_file_systems.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 'SnapCenter nutzt die Snapshot Technologie, um Windows File-System-Ressourcen zu sichern, die sich auf LUNs, CSVs (Cluster Shared Volumes), RDM (Raw Device Mapping)-Volumes, ALM (asymmetrische LUN-Zuordnung) in Windows Clustern und VMDKs auf Basis von VMFS/NFS (VMware Virtual Machine File System über NFS) befinden.' 
---
= Wie SnapCenter Windows File-Systeme sichert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter nutzt die Snapshot Technologie, um Windows File-System-Ressourcen zu sichern, die sich auf LUNs, CSVs (Cluster Shared Volumes), RDM (Raw Device Mapping)-Volumes, ALM (asymmetrische LUN-Zuordnung) in Windows Clustern und VMDKs auf Basis von VMFS/NFS (VMware Virtual Machine File System über NFS) befinden.

SnapCenter erstellt Backups durch Erstellen von Snapshots der Dateisysteme. Gebündelte Backups, bei denen ein Volume LUNs von mehreren Hosts enthält, sind schneller und effizienter als Backups jeder einzelnen LUN, da nur ein Snapshot des Volumes erstellt wird, im Vergleich zu individuellen Snapshots jedes Filesystems.

Wenn SnapCenter einen Snapshot erstellt, wird im Snapshot das gesamte Storage-System-Volume erfasst. Die Sicherung ist jedoch nur für den Host-Server gültig, für den das Backup erstellt wurde.

Wenn sich Daten von anderen Hostservern auf demselben Volume befinden, können diese Daten nicht aus dem Snapshot wiederhergestellt werden.


NOTE: Wenn ein Windows-Dateisystem eine Datenbank enthält, ist das Sichern des Dateisystems nicht dasselbe wie das Sichern der Datenbank. Um eine Datenbank zu sichern, müssen Sie eines der Datenbank-Plug-ins verwenden.
