---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords:  
summary: Sie können eine neue Sicherungsrichtlinie für Ressourcen erstellen, bevor Sie SnapCenter zum Sichern von Windows-Dateisystemen verwenden, oder Sie können eine neue Backup-Richtlinie zum Zeitpunkt der Erstellung einer Ressourcengruppen oder beim Backup einer Ressource erstellen. 
---
= Erstellen von Backup-Richtlinien für Windows Filesysteme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine neue Sicherungsrichtlinie für Ressourcen erstellen, bevor Sie SnapCenter zum Sichern von Windows-Dateisystemen verwenden, oder Sie können eine neue Backup-Richtlinie zum Zeitpunkt der Erstellung einer Ressourcengruppen oder beim Backup einer Ressource erstellen.

*Was Sie brauchen*

* Sie müssen Ihre Backup-Strategie definiert haben. link:task_define_a_backup_strategy_for_windows_file_systems.html["Weitere Informationen ."^]
* Sie müssen auf die Datensicherung vorbereitet sein.
+
Zur Vorbereitung auf die Datensicherung müssen Aufgaben wie das Installieren von SnapCenter, das Hinzufügen von Hosts, die Erkennung von Ressourcen und das Erstellen von SVM-Verbindungen (Storage Virtual Machine) durchgeführt werden.

* Wenn Sie Snapshot Kopien in einen gespiegelten oder sekundären Vault-Storage replizieren, muss der SnapCenter Administrator Ihnen die SVMs sowohl für die Quell- als auch die Ziel-Volumes zugewiesen haben.
* Wenn Sie die PowerShell-Skripte in Prescripts und Postscripts ausführen möchten, sollten Sie den Wert des Parameters usePowershellProcessforScripts in der Datei Web.config auf true setzen.
+
Der Standardwert ist false



*Über diese Aufgabe*

* DER SCRIPTS_PATH wird mit dem PredefinedWindowsScriptDirectory-Schlüssel definiert, der sich in der SMCoreServiceHost.exe.Config-Datei des Plug-in-Hosts befindet.
+
Bei Bedarf können Sie diesen Pfad ändern und den SMCore Service neu starten. Es wird empfohlen, den Standardpfad für die Sicherheit zu verwenden.

+
Der Wert des Schlüssels kann von Swagger über die API angezeigt werden: API /4.7/configsettings

+
Sie können die GET API verwenden, um den Wert der Taste anzuzeigen. SET-API wird nicht unterstützt.



*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite Einstellungen auf *Richtlinien*.
. Um zu bestimmen, ob Sie eine vorhandene Richtlinie verwenden können, wählen Sie den Richtliniennamen aus und klicken Sie dann auf *Details*.
+
Nach Überprüfung der vorhandenen Richtlinien können Sie eine der folgenden Aktionen durchführen:

+
** Vorhandene Richtlinie verwenden
** Kopieren Sie eine vorhandene Richtlinie, und ändern Sie die Richtlinienkonfiguration.
** Erstellen Sie eine neue Richtlinie.


. Um eine neue Richtlinie zu erstellen, klicken Sie auf *Neu*.
. Geben Sie auf der Seite Name den Richtliniennamen und eine Beschreibung ein.
. Führen Sie auf der Seite Backup-Optionen die folgenden Aufgaben aus:
+
.. Wählen Sie eine Sicherungseinstellung aus.
+
|===
| Option | Beschreibung 


 a| 
Konsistentes File-System-Backup
 a| 
Wählen Sie diese Option, wenn SnapCenter das Festplattenlaufwerk stilllegen soll, auf dem sich das Dateisystem befindet, bevor der Sicherungsvorgang beginnt, und setzen Sie das Laufwerk nach Abschluss des Sicherungsvorgangs wieder ein.



 a| 
Crash-konsistentes Backup des File-Systems
 a| 
Wählen Sie diese Option, wenn Sie nicht möchten, dass SnapCenter das Festplattenlaufwerk stilllegt, auf dem sich das Dateisystem befindet.

|===
.. Wählen Sie eine Zeitplanfrequenz (auch als Richtlinientyp bezeichnet) aus.
+
Die Richtlinie gibt nur die Backup-Häufigkeit an. Der spezifische Schutzzeitplan für das Sichern ist in der Ressourcengruppe festgelegt. Daher können zwei oder mehr Ressourcengruppen dieselbe Richtlinien- und Backup-Häufigkeit teilen, jedoch unterschiedliche Backup-Pläne haben.

+

NOTE: Wenn Sie für 2:00 Uhr geplant sind, wird der Zeitplan während der Sommerzeit (DST) nicht ausgelöst.



. Legen Sie auf der Seite Aufbewahrung die Aufbewahrungseinstellungen für On-Demand-Backups und für jede ausgewählte Zeitplanfrequenz fest.
+
|===
| Option | Beschreibung 


 a| 
Gesamtzahl der zu behaltenden Snapshot-Kopien
 a| 
Wählen Sie diese Option, wenn Sie die Anzahl der Snapshot Kopien SnapCenter-Speicher angeben möchten, bevor Sie sie automatisch löschen.



 a| 
Snapshot Kopien löschen, die älter als sind
 a| 
Wählen Sie diese Option, wenn Sie die Anzahl der Tage angeben möchten, die SnapCenter eine Backup-Kopie behält, bevor Sie sie löschen.

|===
+

IMPORTANT: Sie sollten den Aufbewahrungswert auf 2 oder höher einstellen. Der Mindestwert für die Aufbewahrungsanzahl beträgt 2.

+

NOTE: Der maximale Aufbewahrungswert ist 1018 für Ressourcen auf ONTAP 9.4 oder höher und 254 für Ressourcen unter ONTAP 9.3 oder einer früheren Version. Backups schlagen fehl, wenn die Aufbewahrung auf einen Wert festgelegt ist, der höher ist, als die zugrunde liegende ONTAP Version unterstützt.

. Geben Sie auf der Seite „Replikation“ die Replikation auf das sekundäre Speichersystem an:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Aktualisieren Sie SnapMirror nach dem Erstellen einer lokalen Snapshot Kopie
 a| 
Wählen Sie diese Option aus, um Spiegelkopien von Backup-Sets auf einem anderen Volume (SnapMirror) zu erstellen.



 a| 
Aktualisieren Sie die SnapVault nach dem Erstellen einer Snapshot Kopie
 a| 
Wählen Sie diese Option aus, um die Disk-to-Disk-Backup-Replikation durchzuführen.



 a| 
Sekundäres Policy-Label
 a| 
Wählen Sie eine Snapshot-Bezeichnung aus.

Abhängig von dem ausgewählten Etikett der Snapshot Kopie wendet ONTAP die Aufbewahrungsrichtlinie für sekundäre Snapshot Kopien an, die mit dem Etikett übereinstimmt.


NOTE: Wenn Sie *Update SnapMirror nach dem Erstellen einer lokalen Snapshot Kopie* ausgewählt haben, können Sie optional das Label für die sekundäre Richtlinie angeben. Wenn Sie jedoch *Update SnapVault nach dem Erstellen einer lokalen Snapshot Kopie* ausgewählt haben, sollten Sie das sekundäre Policy Label angeben.



 a| 
Fehler bei Wiederholungszählung
 a| 
Geben Sie die Anzahl der Replikationsversuche ein, die vor dem Anhalten des Prozesses auftreten sollen.

|===
+

NOTE: Sie sollten die SnapMirror Aufbewahrungsrichtlinie in ONTAP für den sekundären Storage konfigurieren, um zu vermeiden, dass die maximale Anzahl an Snapshot Kopien auf dem sekundären Storage erreicht wird.

. Geben Sie auf der Seite Skript den Pfad des Prescript oder Postscript ein, den der SnapCenter-Server vor oder nach dem Backup ausführen soll, bzw. ein Zeitlimit, das SnapCenter wartet, bis das Skript ausgeführt wird, bevor das Timing out abgeschlossen wird.
+
Sie können beispielsweise ein Skript ausführen, um SNMP-Traps zu aktualisieren, Warnmeldungen zu automatisieren und Protokolle zu senden.

+

NOTE: Der Pfad für Prescripts oder Postscripts darf keine Laufwerke oder Shares enthalten. Der Pfad sollte relativ zum SCRIPTS_PATH sein.

. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig stellen*.

