---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: Sie können SnapCenter verwenden, um Backups von Dateisystemen wiederherzustellen. Die Wiederherstellung des Dateisystems ist ein mehrphasiger Prozess, bei dem alle Daten von einem angegebenen Backup an den ursprünglichen Speicherort des Filesystems kopiert werden. 
---
= Windows Dateisystemsicherungen wiederherstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können SnapCenter verwenden, um Backups von Dateisystemen wiederherzustellen. Die Wiederherstellung des Dateisystems ist ein mehrphasiger Prozess, bei dem alle Daten von einem angegebenen Backup an den ursprünglichen Speicherort des Filesystems kopiert werden.

.Bevor Sie beginnen
* Sie müssen das Dateisystem gesichert haben.
* Wenn ein geplanter Vorgang, z. B. ein Backup-Vorgang, derzeit für ein Dateisystem ausgeführt wird, muss dieser Vorgang abgebrochen werden, bevor Sie einen Wiederherstellungsvorgang starten können.
* Sie können ein Dateisystem-Backup nur am ursprünglichen Speicherort, nicht in einem alternativen Pfad wiederherstellen.
+
Sie können keine einzelne Datei aus einem Backup wiederherstellen, da das wiederhergestellte Dateisystem alle Daten überschreibt, die sich am ursprünglichen Speicherort des Dateisystems befinden. Zum Wiederherstellen einer einzelnen Datei aus einem Dateisystem-Backup müssen Sie das Backup klonen und auf die Datei im Klon zugreifen.

* Sie können ein System oder ein Startvolume nicht wiederherstellen.
* SnapCenter kann Filesysteme in einem Windows Cluster wiederherstellen, ohne die Cluster-Gruppe offline zu schalten.


.Über diese Aufgabe
* DER SCRIPTS_PATH wird mit dem PredefinedWindowsScriptDirectory-Schlüssel definiert, der sich in der SMCoreServiceHost.exe.Config-Datei des Plug-in-Hosts befindet.
+
Bei Bedarf können Sie diesen Pfad ändern und den SMCore Service neu starten. Es wird empfohlen, den Standardpfad für die Sicherheit zu verwenden.

+
Der Wert des Schlüssels kann von Swagger über die API angezeigt werden: API /4.7/configsettings

+
Sie können die GET API verwenden, um den Wert der Taste anzuzeigen. SET-API wird nicht unterstützt.

* Für die Wiederherstellung der aktiven Synchronisierung von SnapMirror müssen Sie das Backup vom primären Speicherort auswählen.
* Bei ONTAP Version 9.12.1 und niedriger übernehmen die im Rahmen der Wiederherstellung aus den SnapLock Vault Snapshots erstellten Klone die Verfallszeit von SnapLock Vault. Der Storage-Administrator sollte die Klone nach Ablauf der SnapLock-Gültigkeitsdauer manuell bereinigen.


[role="tabbed-block"]
====
.UI von SnapCenter
--
.Schritte
. Klicken Sie im linken Navigationsbereich auf *Ressourcen* und wählen Sie dann das entsprechende Plug-in aus der Liste aus.
. Um die Liste der Ressourcen zu filtern, wählen Sie die Optionen Dateisystem und Ressourcengruppen aus.
. Wählen Sie eine Ressourcengruppe aus der Liste aus, und klicken Sie dann auf *Wiederherstellen*.
. Wählen Sie auf der Seite Backups aus, ob Sie Daten aus primären oder sekundären Speichersystemen wiederherstellen möchten, und wählen Sie dann ein Backup aus, das wiederhergestellt werden soll.
. Wählen Sie im Assistenten Wiederherstellen Ihre Optionen aus.
. Sie können den Pfad und die Argumente des Prescript oder Postscript eingeben, die SnapCenter vor bzw. nach der Wiederherstellung ausführen soll.
+
Beispielsweise können Sie ein Skript ausführen, um SNMP-Traps zu aktualisieren, Warnmeldungen zu automatisieren, Protokolle zu senden usw.

+

NOTE: Der Pfad für Prescripts oder Postscripts darf keine Laufwerke oder Shares enthalten. Der Pfad sollte relativ zum SCRIPTS_PATH sein.

. Wählen Sie auf der Seite Benachrichtigung eine der folgenden Optionen aus:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Protokollieren der Ereignisse des SnapCenter-Servers im Syslog-Storage-System
 a| 
Wählen Sie diese Option aus, um SnapCenter Serverereignisse im Syslog des Speichersystems zu protokollieren.



 a| 
Senden der AutoSupport-Benachrichtigung für fehlgeschlagene Vorgänge an das Storage-System
 a| 
Wählen Sie diese Option aus, um Informationen zu fehlgeschlagenen Vorgängen mithilfe von AutoSupport an NetApp zu senden.



 a| 
E-Mail-Präferenz
 a| 
Wählen Sie *immer*, *bei Ausfall* oder *bei Fehlschlag oder Warnung* aus, um nach der Wiederherstellung von Backups E-Mail-Nachrichten an Empfänger zu senden. Geben Sie den SMTP-Server, die Standard-E-Mail-Betreffzeile und die E-Mail-Adressen an und von ein.

|===
. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig stellen*.
. Überwachen Sie den Fortschritt des Vorgangs, indem Sie auf *Monitor* > *Jobs* klicken.



IMPORTANT: Wenn das wiederhergestellte Dateisystem eine Datenbank enthält, müssen Sie auch die Datenbank wiederherstellen. Wenn Sie die Datenbank nicht wiederherstellen, ist Ihre Datenbank möglicherweise ungültig. Informationen zum Wiederherstellen von Datenbanken finden Sie im Data Protection Guide für diese Datenbank.

--
.PowerShell Commandlets
--
.Schritte
. Starten Sie eine Verbindungssitzung mit dem SnapCenter-Server für einen bestimmten Benutzer, indem Sie das Cmdlet "Open-SmConnection" verwenden.
+
[listing]
----
PS C:\> Open-Smconnection
----
. Rufen Sie die Informationen zu einem oder mehreren Backups ab, die Sie wiederherstellen möchten, indem Sie die Cmdlets Get-SmBackup und Get-SmBackupReport verwenden.
+
In diesem Beispiel werden Informationen zu allen verfügbaren Backups angezeigt:

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
  1               Payroll Dataset_vise-f6_08... 8/4/2015    11:02:32 AM                 Full Backup
  2               Payroll Dataset_vise-f6_08... 8/4/2015    11:23:17 AM
----
+
Dieses Beispiel zeigt detaillierte Informationen zum Backup vom 29. Januar 2015 bis 3. Februar 2015 an:

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

   SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. Stellen Sie Daten aus dem Backup mit dem Cmdlet "Restore-SmBackup" wieder her.
+
[listing]
----
Restore-SmBackup -PluginCode 'DummyPlugin' -AppObjectId 'scc54.sccore.test.com\DummyPlugin\NTP\DB1' -BackupId 269 -Confirm:$false
output:
Name                : Restore 'scc54.sccore.test.com\DummyPlugin\NTP\DB1'
Id                  : 2368
StartTime           : 10/4/2016 11:22:02 PM
EndTime             :
IsCancellable       : False
IsRestartable       : False
IsCompleted         : False
IsVisible           : True
IsScheduled         : False
PercentageCompleted : 0
Description         :
Status              : Queued
Owner               :
Error               :
Priority            : None
Tasks               : {}
ParentJobID         : 0
EventId             : 0
JobTypeId           :
ApisJobKey          :
ObjectId            : 0
PluginCode          : NONE
PluginName          :
----


Die Informationen zu den Parametern, die mit dem Cmdlet und deren Beschreibungen verwendet werden können, können durch Ausführen von _get-Help Command_Name_ abgerufen werden. Alternativ können Sie auch auf die https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter Software Cmdlet Referenzhandbuch"^].

--
====