---
permalink: protect-scw/task_add_hosts_and_install_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: installing 
summary: Sie können die Seite SnapCenter Add Host verwenden, um Windows Hosts hinzuzufügen. Das SnapCenter-Plug-in für Microsoft Windows wird automatisch auf dem angegebenen Host installiert. Dies ist die empfohlene Methode zum Installieren von Plug-ins. Sie können einen Host hinzufügen und ein Plug-in entweder für einen einzelnen Host oder ein Cluster installieren. 
---
= Fügen Sie Hosts hinzu und installieren Sie das SnapCenter Plug-in für Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Seite SnapCenter Add Host verwenden, um Windows Hosts hinzuzufügen. Das SnapCenter-Plug-in für Microsoft Windows wird automatisch auf dem angegebenen Host installiert. Dies ist die empfohlene Methode zum Installieren von Plug-ins. Sie können einen Host hinzufügen und ein Plug-in entweder für einen einzelnen Host oder ein Cluster installieren.

*Was Sie brauchen*

* Sie müssen ein Benutzer sein, der einer Rolle zugewiesen ist, die über die Berechtigungen für die Plug-in-Installation und -Deinstallation verfügt, wie z. B. die Rolle „SnapCenter-Administrator“.
* Wenn Sie ein Plug-in auf einem Windows-Host installieren, müssen Sie UAC auf dem Host deaktivieren, wenn Sie keine Anmeldedaten angeben, die nicht integriert sind, oder wenn der Benutzer zu einem lokalen Workgroup-Benutzer gehört.
* Der SnapCenter-Benutzer sollte der Rolle „`Anmelden als Dienst`“ des Windows-Servers hinzugefügt werden.
* Stellen Sie sicher, dass der Nachrichtenwarteschlange in Betrieb ist.
* Wenn Sie Group Managed Service Account (gMSA) verwenden, sollten Sie gMSA mit Administratorrechten konfigurieren.
+
link:task_configure_gMSA_on_windows_server_2012_or_later.html["Konfigurieren Sie das Gruppenkonto für Managed Services unter Windows Server 2012 oder höher für Windows File System"]



*Über diese Aufgabe*

* Sie können einen SnapCenter-Server nicht als Plug-in-Host zu einem anderen SnapCenter-Server hinzufügen.
* Windows Plug-ins
+
** Microsoft Windows
** Microsoft Exchange Server
** Microsoft SQL Server
** SAP HANA
** Benutzerdefinierte Plug-ins


* Installieren von Plug-ins auf einem Cluster
+
Wenn Sie Plug-ins auf einem Cluster installieren (WSFC, Oracle RAC oder Exchange DAG), sind sie auf allen Knoten des Clusters installiert.

* E-Series Storage
+
Sie können das Plug-in für Windows nicht auf einem mit E-Series Storage verbundenen Windows-Host installieren.



*Schritte*

. Klicken Sie im linken Navigationsbereich auf *Hosts*.
. Vergewissern Sie sich, dass *verwaltete Hosts* oben ausgewählt ist.
. Klicken Sie Auf *Hinzufügen*.
. Gehen Sie auf der Seite Hosts wie folgt vor:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Host-Typ
 a| 
Wählen Sie den Host-Typ *Windows* aus.

SnapCenter Server fügt den Host hinzu und installiert dann das Plug-in für Windows, falls es nicht bereits auf dem Host installiert ist.



 a| 
Host-Name
 a| 
Geben Sie den vollständig qualifizierten Domänennamen (FQDN) oder die IP-Adresse des Hosts ein.

SnapCenter hängt von der richtigen Konfiguration des DNS ab. Daher empfiehlt es sich, den vollständig qualifizierten Domänennamen (FQDN) einzugeben.

Sie können die IP-Adressen oder FQDN einer der folgenden Adressen eingeben:

** Eigenständiger Host
** Windows Server-Failover-Clustering (WSFC)
+
Wenn Sie einen Host mit SnapCenter hinzufügen und dieser Teil einer Unterdomäne ist, müssen Sie den FQDN angeben.





 a| 
Anmeldedaten
 a| 
Wählen Sie den Anmeldeinformationsnamen aus, den Sie erstellt haben, oder erstellen Sie die neuen Anmeldeinformationen.

Die Anmeldeinformationen müssen über Administratorrechte auf dem Remote-Host verfügen. Weitere Informationen finden Sie unter Informationen zum Erstellen von Anmeldeinformationen.

Details zu Anmeldeinformationen, einschließlich Benutzername, Domäne und Hosttyp, werden angezeigt, indem Sie den Cursor über den von Ihnen angegebenen Anmeldeinformationsnamen platzieren.


NOTE: Der Authentifizierungsmodus wird durch den Hosttyp bestimmt, den Sie im Assistenten zum Hinzufügen von Hosts angeben.

|===
. Wählen Sie im Abschnitt Plug-ins zum Installieren auswählen die zu installierenden Plug-ins aus.
+
Bei neuen Implementierungen werden keine Plug-in-Pakete aufgeführt.

. (Optional) Klicken Sie Auf *Weitere Optionen*.
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Port
 a| 
Behalten Sie die Standard-Port-Nummer bei oder geben Sie die Port-Nummer an.

Die Standardanschlussnummer ist 8145. Wenn der SnapCenter-Server auf einem benutzerdefinierten Port installiert wurde, wird diese Portnummer als Standardport angezeigt.


NOTE: Wenn Sie die Plug-ins manuell installiert und einen benutzerdefinierten Port angegeben haben, müssen Sie denselben Port angeben. Andernfalls schlägt der Vorgang fehl.



 a| 
Installationspfad
 a| 
Der Standardpfad ist C:\Programmdateien\NetApp\SnapCenter.

Optional können Sie den Pfad anpassen. Für das SnapCenter Plug-ins-Paket für Windows lautet der Standardpfad C:\Programme\NetApp\SnapCenter. Wenn Sie möchten, können Sie den Standardpfad jedoch anpassen.



 a| 
Fügen Sie alle Hosts im Cluster hinzu
 a| 
Aktivieren Sie dieses Kontrollkästchen, um alle Cluster-Nodes in einem WSFC hinzuzufügen.



 a| 
Überspringen Sie die Prüfungen vor der Installation
 a| 
Aktivieren Sie dieses Kontrollkästchen, wenn Sie die Plug-ins bereits manuell installiert haben und nicht überprüfen möchten, ob der Host die Anforderungen für die Installation des Plug-ins erfüllt.



 a| 
Verwenden Sie Group Managed Service Account (gMSA), um die Plug-in-Dienste auszuführen
 a| 
Aktivieren Sie dieses Kontrollkästchen, wenn Sie die Plug-in-Dienste über das Group Managed Service Account (gMSA) ausführen möchten.

Geben Sie den gMSA-Namen in folgendem Format an: _Domainname\AccountName€_.


NOTE: GSSA wird nur für den SnapCenter-Plug-in für Windows-Dienst als Anmelde-Dienstkonto verwendet.

|===
. Klicken Sie Auf *Absenden*.
+
Wenn Sie das Kontrollkästchen *Vorabprüfungen* nicht aktiviert haben, wird der Host überprüft, ob er die Voraussetzungen für die Installation des Plug-ins erfüllt. Der Festplattenspeicher, der RAM, die PowerShell-Version, die .NET-Version und der Speicherort werden anhand der Mindestanforderungen validiert. Wenn die Mindestanforderungen nicht erfüllt werden, werden entsprechende Fehler- oder Warnmeldungen angezeigt.

+
Wenn der Fehler mit dem Festplattenspeicher oder RAM zusammenhängt, können Sie die Datei Web.config unter aktualisieren `C:\Program Files\NetApp\SnapCenter` WebApp zum Ändern der Standardwerte. Wenn der Fehler mit anderen Parametern zusammenhängt, müssen Sie das Problem beheben.

+

NOTE: Wenn Sie in einem HA-Setup die Datei „Web.config“ aktualisieren, müssen Sie die Datei auf beiden Knoten aktualisieren.

. Überwachen Sie den Installationsfortschritt.

