---
permalink: protect-scw/task_clone_from_a_windows_file_system_backup.html 
sidebar: sidebar 
keywords: clone 
summary: Sie können SnapCenter zum Klonen eines Windows Filesystem-Backups verwenden. Wenn Sie eine Kopie einer einzelnen Datei wünschen, die versehentlich gelöscht oder geändert wurde, können Sie ein Backup klonen und auf diese Datei im Klon zugreifen. 
---
= Klonen aus einem Windows File-System-Backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können SnapCenter zum Klonen eines Windows Filesystem-Backups verwenden. Wenn Sie eine Kopie einer einzelnen Datei wünschen, die versehentlich gelöscht oder geändert wurde, können Sie ein Backup klonen und auf diese Datei im Klon zugreifen.

.Bevor Sie beginnen
* Sie sollten auf die Datensicherung vorbereitet sein, indem Sie Aufgaben wie das Hinzufügen von Hosts, die Identifizierung von Ressourcen und das Erstellen von SVM-Verbindungen (Storage Virtual Machine) abschließen.
* Sie sollten eine Sicherung des Dateisystems haben.
* Sie sollten sicherstellen, dass die Aggregate, die die Volumes hosten, sich in der Liste der zugewiesenen Aggregate der Storage Virtual Machine (SVM) befinden.
* Sie können keine Ressourcengruppe klonen. Sie können nur individuelle File-System-Backups klonen.
* Wenn sich ein Backup auf einer virtuellen Maschine mit VMDK-Laufwerk befindet, kann SnapCenter das Backup nicht auf einem physischen Server klonen.
* Wenn Sie ein Windows Cluster klonen (z. B. eine gemeinsame LUN oder ein gemeinsam genutztes Cluster-Volume (CSV)-LUN), wird der Klon als dedizierte LUN auf dem von Ihnen angegebenen Host gespeichert.
* Für einen Klonvorgang kann das Stammverzeichnis des Volume-Bereitstellungspunkts kein freigegebenes Verzeichnis sein.
* Auf einem Node, der nicht der Home-Node für das Aggregat ist, können Sie keinen Klon erstellen.
* Sie können keine wiederkehrenden Vorgänge des Klons (Lebenszyklus von Klonen) für Windows Filesysteme planen, sondern nur Backups nach Bedarf klonen.
* Wenn Sie eine LUN verschieben, die einen Klon enthält, auf ein neues Volume, kann SnapCenter den Klon nicht mehr unterstützen. Beispielsweise können Sie diesen Klon nicht mit SnapCenter löschen.
* Sie können nicht über mehrere Umgebungen hinweg klonen. Zum Beispiel Klonen von einer physischen Festplatte auf eine virtuelle Festplatte oder umgekehrt.


.Über diese Aufgabe
* DER SCRIPTS_PATH wird mit dem PredefinedWindowsScriptDirectory-Schlüssel definiert, der sich in der SMCoreServiceHost.exe.Config-Datei des Plug-in-Hosts befindet.
+
Bei Bedarf können Sie diesen Pfad ändern und den SMCore Service neu starten. Es wird empfohlen, den Standardpfad für die Sicherheit zu verwenden.

+
Der Wert des Schlüssels kann von Swagger über die API angezeigt werden: API /4.7/configsettings

+
Sie können die GET API verwenden, um den Wert der Taste anzuzeigen. SET-API wird nicht unterstützt.

* Bei ONTAP Version 9.12.1 und niedriger übernehmen die im Rahmen der Wiederherstellung aus den SnapLock Vault Snapshots erstellten Klone die Verfallszeit von SnapLock Vault. Der Storage-Administrator sollte die Klone nach Ablauf der SnapLock-Gültigkeitsdauer manuell bereinigen.


[role="tabbed-block"]
====
.UI von SnapCenter
--
.Schritte
. Klicken Sie im linken Navigationsbereich auf *Ressourcen* und wählen Sie dann das entsprechende Plug-in aus der Liste aus.
. Wählen Sie auf der Seite Ressourcen die Option *Dateisysteme* aus der Liste aus.
. Wählen Sie den Host aus.
+
Die Topologieansicht wird automatisch angezeigt, wenn die Ressource geschützt ist.

. Wählen Sie in der Liste Ressourcen das zu klonenden Backup aus, und klicken Sie dann auf das Klon-Symbol.
. Gehen Sie auf der Seite Optionen wie folgt vor:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Klonserver
 a| 
Wählen Sie den Host aus, auf dem der Klon erstellt werden soll.



 a| 
„`Automatische Zuweisung von Bereitstellungspunkt`“ oder „`Automatische Zuweisung von Volume-Bereitstellungspunkt unter Pfad`“
 a| 
Legen Sie fest, ob unter einem Pfad automatisch ein Mount-Punkt oder ein Volume-Mount-Punkt zugewiesen werden soll.

Automatisches Zuweisen von Volume-Mount-Punkt unter Pfad: Der Mount-Punkt unter einem Pfad ermöglicht es Ihnen, ein bestimmtes Verzeichnis bereitzustellen, in dem die Mount-Punkte erstellt werden. Bevor Sie diese Option auswählen, müssen Sie überprüfen, ob das Verzeichnis leer ist. Wenn ein Backup im Verzeichnis vorhanden ist, befindet sich das Backup nach dem Mount-Vorgang in einem ungültigen Status.



 a| 
Speicherort der Archivierung
 a| 
Wählen Sie einen Archivort aus, wenn Sie ein sekundäres Backup klonen.

|===
. Geben Sie auf der Seite Skript alle Druckschriften oder Postskripte an, die Sie ausführen möchten.
+

NOTE: Der Pfad für Prescripts oder Postscripts darf keine Laufwerke oder Shares enthalten. Der Pfad sollte relativ zum SCRIPTS_PATH sein.

. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig stellen*.
. Überwachen Sie den Fortschritt des Vorgangs, indem Sie auf *Monitor* > *Jobs* klicken.


--
.PowerShell Commandlets
--
.Schritte
. Starten Sie eine Verbindungssitzung mit dem SnapCenter-Server für einen bestimmten Benutzer, indem Sie das Cmdlet "Open-SmConnection" verwenden.
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146
----
. Listen Sie die Backups auf, die mit dem Cmdlet "Get-SmBackup" oder "Get-SmResourceGroup" geklont werden können.
+
In diesem Beispiel werden Informationen zu allen verfügbaren Backups angezeigt:

+
[listing]
----
C:\PS>PS C:\> Get-SmBackup

BackupId   BackupName                     BackupTime   BackupType
--------   ----------                     ----------   ----------
1          Payroll Dataset_vise-f6_08...  8/4/2015     Full Backup
                                          11:02:32 AM

2          Payroll Dataset_vise-f6_08...  8/4/2015
                                          11:23:17 AM
----
+
In diesem Beispiel werden Informationen über eine bestimmte Ressourcengruppe, ihre Ressourcen und zugehörige Richtlinien angezeigt:

+
[listing]
----
PS C:\> Get-SmResourceGroup -ListResources –ListPolicies

Description :
CreationTime : 8/4/2015 3:44:05 PM
ModificationTime : 8/4/2015 3:44:05 PM
EnableEmail : False
EmailSMTPServer :
EmailFrom :
EmailTo :
EmailSubject :
EnableSysLog : False
ProtectionGroupType : Backup
EnableAsupOnFailure : False
Policies : {FinancePolicy}
HostResourceMaping : {}
Configuration : SMCoreContracts.SmCloneConfiguration
LastBackupStatus :
VerificationServer :
EmailBody :
EmailNotificationPreference : Never
VerificationServerInfo : SMCoreContracts.SmVerificationServerInfo
SchedulerSQLInstance :
CustomText :
CustomSnapshotFormat :
SearchResources : False
ByPassCredential : False
IsCustomSnapshot :
MaintenanceStatus : Production
PluginProtectionGroupTypes : {SMSQL}
Name : Payrolldataset
Type : Group
Id : 1
Host :
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
CloneLevel : 0
ApplySnapvaultUpdate : False
ApplyRetention : False
RetentionCount : 0
RetentionDays : 0
ApplySnapMirrorUpdate : False
SnapVaultLabel :
MirrorVaultUpdateRetryCount : 7
AppPolicies : {}
Description : FinancePolicy
PreScriptPath :
PreScriptArguments :
PostScriptPath :
PostScriptArguments :
ScriptTimeOut : 60000
DateModified : 8/4/2015 3:43:30 PM
DateCreated : 8/4/2015 3:43:30 PM
Schedule : SMCoreContracts.SmSchedule
PolicyType : Backup
PluginPolicyType : SMSQL
Name : FinancePolicy
Type :
Id : 1
Host :
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
CloneLevel : 0
clab-a13-13.sddev.lab.netapp.com
DatabaseGUID :
SQLInstance : clab-a13-13
DbStatus : AutoClosed
DbAccess : eUndefined
IsSystemDb : False
IsSimpleRecoveryMode : False
IsSelectable : True
SqlDbFileGroups : {}
SqlDbLogFiles : {}
AppFileStorageGroups : {}
LogDirectory :
AgName :
Version :
VolumeGroupIndex : -1
IsSecondary : False
Name : TEST
Type : SQL Database
Id : clab-a13-13\TEST
Host : clab-a13-13.sddev.mycompany.com
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
----
. Initiieren Sie einen Klonvorgang aus einem vorhandenen Backup mit dem Cmdlet "New-SmClone".
+
Dieses Beispiel erstellt einen Klon aus einem angegebenen Backup mit allen Protokollen:

+
[listing]
----
PS C:\> New-SmClone
-BackupName payroll_dataset_vise-f3_08-05-2015_15.28.28.9774
-Resources @{"Host"="vise-f3.sddev.mycompany.com";
"Type"="SQL Database";"Names"="vise-f3\SQLExpress\payroll"}
-CloneToInstance vise-f3\sqlexpress -AutoAssignMountPoint
-Suffix _clonefrombackup
-LogRestoreType All -Policy clonefromprimary_ondemand

PS C:> New-SmBackup -ResourceGroupName PayrollDataset -Policy FinancePolicy
----
+
In diesem Beispiel wird ein Klon für eine angegebene Microsoft SQL Server-Instanz erstellt:

+
[listing]
----
PS C:\> New-SmClone
-BackupName "BackupDS1_NY-VM-SC-SQL_12-08-2015_09.00.24.8367"
-Resources @{"host"="ny-vm-sc-sql";"Type"="SQL Database";
"Names"="ny-vm-sc-sql\AdventureWorks2012_data"}
-AppPluginCode SMSQL -CloneToInstance "ny-vm-sc-sql"
-Suffix _CLPOSH -AssignMountPointUnderPath "C:\SCMounts"
----
. Zeigen Sie den Status des Clone-Jobs mit dem Cmdlet Get-SmCloneReport an.
+
In diesem Beispiel wird ein Klonbericht für die angegebene Job-ID angezeigt:

+
[listing]
----
PS C:\> Get-SmCloneReport -JobId 186

SmCloneId : 1
SmJobId : 186
StartDateTime : 8/3/2015 2:43:02 PM
EndDateTime : 8/3/2015 2:44:08 PM
Duration : 00:01:06.6760000
Status : Completed
ProtectionGroupName : Draper
SmProtectionGroupId : 4
PolicyName : OnDemand_Clone
SmPolicyId : 4
BackupPolicyName : OnDemand_Full_Log
SmBackupPolicyId : 1
CloneHostName : SCSPR0054212005.mycompany.com
CloneHostId : 4
CloneName : Draper__clone__08-03-2015_14.43.53
SourceResources : {Don, Betty, Bobby, Sally}
ClonedResources : {Don_DRAPER, Betty_DRAPER, Bobby_DRAPER,
                   Sally_DRAPER}
----


Die Informationen zu den Parametern, die mit dem Cmdlet und deren Beschreibungen verwendet werden können, können durch Ausführen von _get-Help Command_Name_ abgerufen werden. Alternativ können Sie auch auf die https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter Software Cmdlet Referenzhandbuch"^].

--
====