---
permalink: concept/concept_disaster_recovery.html 
sidebar: sidebar 
keywords:  
summary: Sie können den SnapCenter-Server bei einem Ausfall wie z. B. Ressourcenbeschädigung oder Serverabsturz mithilfe der SnapCenter Disaster Recovery-Funktion wiederherstellen. 
---
= SnapCenter Disaster Recovery
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe der Disaster Recovery-Funktion von SnapCenter können Sie den SnapCenter Server im Falle von Ausfällen wie einer Beschädigung von Ressourcen oder einem Serverabsturz wiederherstellen. Sie können SnapCenter Repositorys, Serverzeitpläne und Serverkonfigurationskomponenten wiederherstellen. Sie können auch das SnapCenter Plug-in für SQL Server und das SnapCenter Plug-in für SQL Server Storage wiederherstellen.

In diesem Abschnitt werden die beiden Arten der Disaster Recovery (DR) in SnapCenter beschrieben:

.DR mit SnapCenter Servern
* Die Daten des SnapCenter Servers werden gesichert und können ohne Plug-in wiederhergestellt werden, das dem SnapCenter Server hinzugefügt oder durch ihn gemanagt wird.
* Der sekundäre SnapCenter Server sollte auf demselben Installationsverzeichnis und auf demselben Port wie der primäre SnapCenter-Server installiert sein.
* Für die Multi-Faktor-Authentifizierung (MFA) schließen Sie während der SnapCenter-Server-Wiederherstellung alle Browser-Registerkarten und öffnen Sie einen Browser erneut, um sich erneut anzumelden. Dadurch werden die vorhandenen oder aktiven Sitzungscookies gelöscht und die korrekten Konfigurationsdaten aktualisiert.
* Die Disaster Recovery-Funktion von SnapCenter verwendet FÜR das Backup des SnapCenter Servers REST-APIs. Siehe link:../sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html["REST-API-Workflows für Disaster Recovery von SnapCenter Server"].
* Die Konfigurationsdatei für die Audit-Einstellungen wird nicht im DR-Backup gesichert und auch nicht auf dem DR-Server nach dem Wiederherstellungsvorgang. Sie sollten die Einstellungen für das Überwachungsprotokoll manuell wiederholen.


.SnapCenter Plug-in und Storage DR
DR wird nur für das SnapCenter Plug-in für SQL Server unterstützt. Wenn das SnapCenter-Plug-in für SQL Server ausfällt, wechseln Sie zu einem anderen SQL-Host und stellen Sie die Daten mit wenigen Schritten wieder her. Siehe link:../protect-scsql/task_disaster_recovery_scsql.html["Disaster Recovery eines SnapCenter Plug-ins für SQL Server"].

SnapCenter nutzt ONTAP SnapMirror Technologie zur Datenreplizierung. Er kann zur DR an einem sekundären Standort repliziert und synchron gehalten werden. Ein Failover kann durch die Unterbrechung der Replizierungsbeziehung in SnapMirror initiiert werden. Während Failback kann die Synchronisierung umgekehrt werden und Daten vom DR-Standort zurück zum primären Standort repliziert werden.
