---
permalink: concept/reference_data_security.html 
sidebar: sidebar 
keywords: security,authentication, CA certificates 
summary: SnapCenter setzt strenge Sicherheits- und Authentifizierungsfunktionen ein, damit Ihre Daten sicher bleiben. 
---
= Sicherheitsfunktionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter setzt strenge Sicherheits- und Authentifizierungsfunktionen ein, damit Ihre Daten sicher bleiben.

SnapCenter umfasst die folgenden Sicherheitsfunktionen:

* Die gesamte Kommunikation zu SnapCenter verwendet HTTP über SSL (HTTPS).
* Alle Anmeldedaten in SnapCenter werden mit AES-Verschlüsselung (Advanced Encryption Standard) geschützt.
* SnapCenter verwendet Sicherheitsalgorithmen, die dem Federal Information Processing Standard (FIPS) entsprechen.
* SnapCenter unterstützt die Verwendung der vom Kunden bereitgestellten autorisierten CA-Zertifikate.
* SnapCenter 4.1.1 oder höher unterstützt TLS 1.2 (Transport Layer Security) für die Kommunikation mit ONTAP. Sie können TLS 1.2 auch für die Kommunikation zwischen Clients und Servern verwenden.
+
Ab 5.0 unterstützt SnapCenter (TLS) 1.3 für die Kommunikation mit ONTAP.

* SnapCenter unterstützt einen bestimmten Satz von SSL-Cipher-Suites, um die Sicherheit der Netzwerkkommunikation zu gewährleisten.
+
Weitere Informationen finden Sie unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_the_supported_SSL_Cipher_Suite["So konfigurieren Sie die unterstützte SSL Cipher Suite"].

* SnapCenter wird innerhalb der Firewall Ihres Unternehmens installiert, um den Zugriff auf den SnapCenter Server zu ermöglichen und die Kommunikation zwischen dem SnapCenter Server und den Plug-ins zu ermöglichen.
* Für den SnapCenter-API- und -Betriebszugriff werden Tokens verwendet, die mit AES-Verschlüsselung verschlüsselt sind und nach 24 Stunden ablaufen.
* SnapCenter lässt sich zur Anmeldung und zur rollenbasierten Zugriffssteuerung (Role Based Access Control, RBAC) in Windows Active Directory integrieren und ermöglicht die Zugriffsberechtigungen.
* IPsec wird mit SnapCenter auf ONTAP für Windows- und Linux-Hostcomputer unterstützt. https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html#use-ipsec-identities["Weitere Informationen ."].
* SnapCenter PowerShell Commandlets sind über die Sitzungen gesichert.
* Nach einer Standardlaufzeit von 15 Minuten Inaktivität warnt Sie SnapCenter, dass Sie in 5 Minuten abgemeldet werden. Nach 20 Minuten Inaktivität meldet SnapCenter Sie aus, und Sie müssen sich erneut anmelden. Sie können den Ausloggen Zeitraum ändern.
* Die Anmeldung ist nach 5 oder mehr falschen Anmeldeversuchen vorübergehend deaktiviert.
* Unterstützt die Authentifizierung von CA-Zertifikaten zwischen SnapCenter Server und ONTAP. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_securely_connect_SnapCenter_with_ONTAP_using_CA_certificate["Weitere Informationen ."].
* Integritätsprüfung wird dem SnapCenter-Server und den Plug-ins hinzugefügt und validiert alle im Lieferumfang enthaltenen Binärdateien bei Neuinstallationen und Upgrades.




== ÜBERSICHT ÜBER DAS CA-Zertifikat

Das Installationsprogramm von SnapCenter Server ermöglicht die zentralisierte Unterstützung von SSL-Zertifikaten während der Installation. Um die sichere Kommunikation zwischen Server und Plug-in zu verbessern, unterstützt SnapCenter die Verwendung der vom Kunden bereitgestellten autorisierten CA-Zertifikate.

Sie sollten CA-Zertifikate bereitstellen, nachdem Sie den SnapCenter-Server und die entsprechenden Plug-ins installiert haben. Weitere Informationen finden Sie unter link:../install/reference_generate_CA_certificate_CSR_file.html["ZertifikatCSR-Datei erstellen"].

Sie können auch ein CA-Zertifikat für SnapCenter-Plug-in für VMware vSphere implementieren. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_manage_snapcenter_plug-in_for_vmware_vsphere.html#create-and-import-certificates["Erstellen und Importieren von Zertifikaten"^].



== Bidirektionale SSL-Kommunikation

Die bidirektionale SSL-Kommunikation sichert die gegenseitige Kommunikation zwischen dem SnapCenter-Server und den Plug-ins.



== Übersicht über die zertifikatbasierte Authentifizierung

Die zertifikatbasierte Authentifizierung überprüft die Authentizität der jeweiligen Benutzer, die versuchen, auf den SnapCenter-Plug-in-Host zuzugreifen. Der Benutzer sollte das SnapCenter-Serverzertifikat ohne privaten Schlüssel exportieren und in den vertrauenswürdigen Speicher des Plug-in-Hosts importieren. Die zertifikatbasierte Authentifizierung funktioniert nur, wenn die bidirektionale SSL-Funktion aktiviert ist.



== Multi-Faktor-Authentifizierung (MFA)

MFA verwendet für das Management von Benutzersitzungen einen Identitätsanbieter (IdP) über die Security Assertion Markup Language (SAML) eines Drittanbieters. Diese Funktionalität verbessert die Authentifizierungssicherheit, da sie neben dem vorhandenen Benutzernamen und Passwort mehrere Faktoren wie TOTP, Biometrie, Push-Benachrichtigungen usw. verwenden kann. Zudem können Kunden mithilfe von IT-Providern ihre eigenen Benutzeridentitätsanbieter nutzen, um einheitliche SSO (Benutzeranmeldung) in ihrem gesamten Portfolio zu erhalten.

MFA ist nur für die Benutzerschnittstelle von SnapCenter Server anwendbar. Die Anmeldungen werden über die IdP Active Directory Federation Services (AD FS) authentifiziert. Sie können verschiedene Authentifizierungsfaktoren bei AD FS konfigurieren. SnapCenter ist der Service-Provider, und Sie sollten SnapCenter als eine abhängige Partei in AD FS konfigurieren. Um MFA in SnapCenter zu aktivieren, sind die AD FS-Metadaten erforderlich.

Informationen zur Aktivierung von MFA finden Sie unter link:../install/enable_multifactor_authentication.html["Multi-Faktor-Authentifizierung aktivieren"].
