---
permalink: protect-hana/concept_how_snapcenter_plug_in_for_sap_hana_database_uses_consistency_group_snapshot_copies.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: Sie können das Plug-in verwenden, um Snapshots von Konsistenzgruppen für Ressourcengruppen zu erstellen. Eine Konsistenzgruppe ist ein Container, der mehrere Volumes beherbergen kann, sodass Sie sie als eine Einheit verwalten können. Eine Konsistenzgruppe ist simultane Snapshots mehrerer Volumes und bietet konsistente Kopien einer Gruppe von Volumes. 
---
= So verwendet das SnapCenter Plug-in für SAP HANA Database Snapshots von Konsistenzgruppen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Plug-in verwenden, um Snapshots von Konsistenzgruppen für Ressourcengruppen zu erstellen. Eine Konsistenzgruppe ist ein Container, der mehrere Volumes beherbergen kann, sodass Sie sie als eine Einheit verwalten können. Eine Konsistenzgruppe ist simultane Snapshots mehrerer Volumes und bietet konsistente Kopien einer Gruppe von Volumes.

Sie können auch die Wartezeit für die konsistente Gruppierung von Snapshots durch den Storage Controller angeben. Die verfügbaren Optionen für Wartezeiten sind *dringend*, *Medium* und *entspannt*. Sie können auch die WAFL-Synchronisierung (Write Anywhere File Layout) während des Snapshot-Vorgangs einer konsistenten Gruppe aktivieren oder deaktivieren. WAFL Sync verbessert die Performance eines Snapshots von Konsistenzgruppen.
