---
permalink: protect-hana/task_create_backup_policies_for_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: Bevor Sie SnapCenter zum Sichern von SAP HANA-Datenbankressourcen verwenden, müssen Sie eine Backup-Richtlinie für die Ressource oder Ressourcengruppe erstellen, die Sie sichern möchten. Eine Backup-Richtlinie ist eine Reihe von Regeln, die das Managen, Planen und Aufbewahren von Backups regeln. 
---
= Backup-Richtlinien für SAP HANA Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie SnapCenter zum Sichern von SAP HANA-Datenbankressourcen verwenden, müssen Sie eine Backup-Richtlinie für die Ressource oder Ressourcengruppe erstellen, die Sie sichern möchten. Eine Backup-Richtlinie ist eine Reihe von Regeln, die das Managen, Planen und Aufbewahren von Backups regeln.

.Bevor Sie beginnen
* Sie müssen Ihre Backup-Strategie definiert haben.
+
Weitere Informationen zur Definition einer Datensicherungsstrategie für SAP HANA Datenbanken finden Sie in den Informationen.

* Sie müssen auf die Datensicherung vorbereitet sein, indem Sie Aufgaben wie das Installieren von SnapCenter, das Hinzufügen von Hosts, das Einrichten von Verbindungen zu Storage-Systemen und das Hinzufügen von Ressourcen ausführen.
* Der SnapCenter Administrator muss Ihnen die SVMs sowohl für die Quell- als auch für Ziel-Volumes zugewiesen haben, wenn Sie Snapshots auf eine Spiegelung oder einen Vault replizieren.
+
Außerdem können Sie in der Richtlinie Replizierungs-, Skript- und Applikationseinstellungen festlegen. Diese Optionen sparen Zeit, wenn Sie die Richtlinie für eine andere Ressourcengruppe wiederverwenden möchten.

* Prüfen Sie die spezifischen Voraussetzungen und Einschränkungen von SnapMirror Active Sync. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Objektgrenzen für die aktive SnapMirror Synchronisierung"].


.Über diese Aufgabe
* SAP HANA System Replication
+
** Das primäre SAP HANA System ist gesichert, und alle Datensicherungsvorgänge können durchgeführt werden.
** Sie können das sekundäre SAP HANA System schützen, aber die Backups können nicht erstellt werden.
+
Nach dem Failover kann der gesamte Datensicherungsvorgang durchgeführt werden, wenn das sekundäre SAP HANA System zum primären SAP HANA System wird.

+
Sie können kein Backup für SAP HANA Daten-Volume erstellen, aber SnapCenter schützt weiterhin die nicht-Daten-Volumes (NDV).



* SnapLock
+
** Wenn die Option „Backup-Kopien für eine bestimmte Anzahl von Tagen aufbewahren“ ausgewählt ist, muss die SnapLock Aufbewahrungsfrist kleiner oder gleich den genannten Aufbewahrungstagen sein.
** Wenn Sie eine Snapshot-Sperrfrist festlegen, wird das Löschen der Snapshots bis zum Ablauf der Aufbewahrungsfrist verhindert. Dies kann dazu führen, dass eine größere Anzahl von Snapshots beibehalten wird als in der Richtlinie angegeben.
** Bei ONTAP Version 9.12.1 und niedriger übernehmen die im Rahmen der Wiederherstellung aus den SnapLock Vault Snapshots erstellten Klone die Verfallszeit von SnapLock Vault. Der Storage-Administrator sollte die Klone nach Ablauf der SnapLock-Gültigkeitsdauer manuell bereinigen.




.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite Einstellungen auf *Richtlinien*.
. Klicken Sie Auf *Neu*.
. Geben Sie auf der Seite Name den Richtliniennamen und Details ein.
. Führen Sie auf der Seite Richtlinientyp die folgenden Schritte durch:
+
** Wählen Sie den Storage-Typ aus
** Wählen Sie den Sicherungstyp:
+
|===
| Ihr Ziel ist | Tun Sie das... 


 a| 
Erstellen Sie ein Backup mit Snapshot Technologie
 a| 
Wählen Sie *Snapshot-Basiert* Aus.



 a| 
Führen Sie eine Integritätsprüfung der Datenbank durch
 a| 
Wählen Sie * File-Based Backup* Aus. Es werden nur aktive Mandanten gesichert.

|===


. Führen Sie auf der Seite Snapshot und Replikation die folgenden Schritte durch:
+
** Geben Sie den Terminplantyp an, indem Sie *on Demand*, *hourly*, *Daily*, *Weekly* oder *Monthly* auswählen.
+

NOTE: Sie können den Zeitplan (Startdatum, Enddatum und Häufigkeit) für den Backup-Vorgang beim Erstellen einer Ressourcengruppe angeben. So können Sie Ressourcengruppen erstellen, die dieselben Richtlinien und Backup-Häufigkeit verwenden, aber auch die Möglichkeit haben, den einzelnen Richtlinien unterschiedliche Backup-Zeitpläne zuzuweisen.

+

NOTE: Wenn Sie für 2:00 Uhr geplant sind, wird der Zeitplan während der Sommerzeit (DST) nicht ausgelöst.



. Geben Sie auf der Seite Snapshot und Replikation die Aufbewahrungseinstellungen für den Sicherungstyp und den auf der Seite Sicherungstyp ausgewählten Zeitplantyp an:
+
|===
| Ihr Ziel ist | Dann... 


 a| 
Behalten Sie eine bestimmte Anzahl von Snapshots bei
 a| 
Wählen Sie *Kopien, die behalten werden sollen*, und geben Sie dann die Anzahl der Snapshots an, die Sie behalten möchten.

Wenn die Anzahl der Snapshots die angegebene Zahl überschreitet, werden die Snapshots mit den ältesten zuerst gelöschten Kopien gelöscht.


NOTE: Der maximale Aufbewahrungswert ist 1018. Backups schlagen fehl, wenn die Aufbewahrung auf einen Wert festgelegt ist, der höher ist, als die zugrunde liegende ONTAP Version unterstützt.


IMPORTANT: Wenn Sie Snapshot Backups auf Basis von Kopien aktivieren SnapVault möchten, müssen Sie die Aufbewahrungsanzahl auf 2 oder höher festlegen. Wenn Sie den Aufbewahrungszeitraum auf 1 festlegen, kann der Aufbewahrungsvorgang fehlschlagen, weil der erste Snapshot der ReferenzSnapshot für die SnapVault-Beziehung ist, bis ein neuerer Snapshot auf das Ziel repliziert wird.


NOTE: Für die SAP HANA-Systemreplizierung wird empfohlen, alle Ressourcen des SAP HANA-Systems in einer Ressourcengruppe hinzuzufügen. So wird sichergestellt, dass die richtige Anzahl von Backups beibehalten wird.


NOTE: Bei der SAP HANA-Systemreplikation entsprechen die insgesamt erstellten Snapshots dem Aufbewahrungssatz für die Ressourcengruppe.  Das Entfernen des ältesten Snapshots basiert auf dem Node, auf dem sich der älteste Snapshot befindet.
Die Aufbewahrung ist beispielsweise für eine Ressourcengruppe mit primärer SAP HANA System Replication und sekundärer SAP HANA System Replication auf 7 festgelegt.  Sie können maximal 7 Snapshots gleichzeitig erstellen, einschließlich primärer SAP HANA System Replication und sekundärer SAP HANA System Replication.



 a| 
Bewahren Sie die Snapshots für eine bestimmte Anzahl von Tagen auf
 a| 
Wählen Sie *Kopien behalten für*, und geben Sie dann die Anzahl der Tage an, für die Sie die Snapshots vor dem Löschen aufbewahren möchten.



 a| 
Sperrfrist der primären Snapshot-Kopie
 a| 
Wählen Sie die Sperrfrist für Snapshot Kopien aus und wählen Sie Tage, Monate oder Jahre aus.

Die SnapLock-Aufbewahrungsfrist sollte weniger als 100 Jahre betragen.



 a| 
Sperrfrist für sekundäre Snapshot-Kopien
 a| 
Wählen Sie *Secondary Snapshot copy Sperrfrist* und wählen Sie Tage, Monate oder Jahre.

|===
. Wählen Sie eine Snapshot-Bezeichnung aus.
+
Je nach der ausgewählten Snapshot-Beschriftung wendet ONTAP die sekundäre Snapshot-Aufbewahrungsrichtlinie an, die der Markierung entspricht.

+

NOTE: Wenn Sie *Update SnapMirror nach dem Erstellen einer lokalen Snapshot Kopie* ausgewählt haben, können Sie optional das Label für die sekundäre Richtlinie angeben. Wenn Sie jedoch *Update SnapVault nach dem Erstellen einer lokalen Snapshot Kopie* ausgewählt haben, sollten Sie das sekundäre Policy Label angeben.

. Wählen Sie für auf Snapshot Kopien basierende Backups im Abschnitt sekundäre Replizierungsoptionen auswählen eine oder beide der folgenden sekundären Replizierungsoptionen aus:
+

NOTE: Sie müssen die sekundären Replikationsoptionen für *Sperrfrist der sekundären Snapshot-Kopie* auswählen, um wirksam zu sein.

+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
*Aktualisieren Sie SnapMirror nach dem Erstellen einer lokalen Snapshot Kopie*
 a| 
Wählen Sie dieses Feld aus, um Spiegelkopien der Backup-Sätze auf einem anderen Volume zu erstellen (SnapMirror Replikation).

Diese Option sollte für SnapMirror Active Sync aktiviert sein.

Wenn die Sicherungsbeziehung in ONTAP vom Typ „Mirror and Vault“ ist und Sie nur diese Option auswählen, wird der auf dem primären Volume erstellte Snapshot nicht an das Zielsystem übertragen, sondern im Zielsystem aufgelistet. Wenn dieser Snapshot vom Ziel ausgewählt ist, um einen Wiederherstellungsvorgang durchzuführen, wird die Fehlermeldung „sekundärer Speicherort“ für die ausgewählte vaulted/mirrored Backup nicht verfügbar angezeigt.

Während der sekundären Replizierung wird mit der SnapLock-Ablaufzeit die primäre SnapLock-Ablaufzeit geladen.

Durch Klicken auf die Schaltfläche * Aktualisieren* auf der Seite Topologie wird die sekundäre und primäre SnapLock-Ablaufzeit aktualisiert, die von ONTAP abgerufen werden.

Siehe link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Sehen Sie sich SAP HANA Datenbank-Backups und -Klone auf der Seite Topologie an"].



 a| 
*Aktualisieren Sie SnapVault nach dem Erstellen einer lokalen Snapshot Kopie*
 a| 
Wählen Sie diese Option aus, um Disk-to-Disk-Backup-Replikation (SnapVault-Backups) durchzuführen.

Während der sekundären Replizierung wird mit der SnapLock-Ablaufzeit die primäre SnapLock-Ablaufzeit geladen. Durch Klicken auf die Schaltfläche * Aktualisieren* auf der Seite Topologie wird die sekundäre und primäre SnapLock-Ablaufzeit aktualisiert, die von ONTAP abgerufen werden.

Wenn SnapLock nur auf dem sekundären aus ONTAP, dem sogenannten SnapLock-Vault, konfiguriert ist, wird durch Klicken auf die Schaltfläche * Aktualisieren* auf der Seite Topologie die Sperrfrist auf dem sekundären, das von ONTAP abgerufen wird, aktualisiert.

Weitere Informationen zu SnapLock Vault finden Sie unter https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Speichern von Snapshot-Kopien in WORM-KOPIEN auf einem Vault-Ziel"]

Siehe link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Sehen Sie sich SAP HANA Datenbank-Backups und -Klone auf der Seite Topologie an"].



 a| 
*Anzahl der Wiederholversuche*
 a| 
Geben Sie die maximale Anzahl von Replikationsversuchen ein, die zulässig sind, bevor der Vorgang beendet wird.

|===
+

NOTE:  Sie sollten die SnapMirror Aufbewahrungsrichtlinie in ONTAP für den sekundären Storage konfigurieren, um die maximale Grenze von Snapshots auf dem sekundären Storage zu vermeiden.

. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig stellen*.

