---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_features.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter lässt sich in die Plug-in-Applikation und mit NetApp Technologien auf dem Storage-System integrieren. Um mit benutzerdefinierten Plug-ins zu arbeiten, verwenden Sie die grafische Benutzeroberfläche von SnapCenter. 
---
= Benutzerdefinierte SnapCenter Plug-ins-Funktionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter lässt sich in die Plug-in-Applikation und mit NetApp Technologien auf dem Storage-System integrieren. Um mit benutzerdefinierten Plug-ins zu arbeiten, verwenden Sie die grafische Benutzeroberfläche von SnapCenter.

* *Einheitliche grafische Benutzeroberfläche*
+
Die SnapCenter-Schnittstelle bietet Standardisierung und Konsistenz über Plug-ins und Umgebungen hinweg. Die SnapCenter Schnittstelle ermöglicht konsistente Backup-, Restore-, Recovery- und Klonvorgänge über alle Plug-ins hinweg, zentralisierte Berichterstellung, Dashboard-Ansichten auf einen Blick, rollenbasierte Zugriffssteuerung (Role Based Access Control, RBAC) und das Monitoring von Aufgaben über alle Plug-ins hinweg.

* *Automatisierte zentrale Verwaltung*
+
Sie können Backup-Vorgänge planen, richtlinienbasierte Backup-Aufbewahrung konfigurieren und Restore-Vorgänge durchführen. Zudem lässt sich die Umgebung proaktiv überwachen, indem SnapCenter für das Senden von E-Mail-Warnmeldungen konfiguriert wird.

* *Unterbrechungsfreie NetApp Snapshot Kopie-Technologie*
+
SnapCenter nutzt die NetApp Snapshot-Kopiertechnologie mit den benutzerdefinierten Plug-ins von SnapCenter, um Ressourcen zu sichern. Snapshot Kopien belegen nur minimalen Speicherplatz.



Mithilfe der Funktion „Custom Plug-ins“ ergeben sich darüber hinaus folgende Vorteile:

* Unterstützung für Backup-, Restore- und Klon-Workflows
* RBAC-unterstützte Sicherheit und zentralisierte Rollendelegation
+
Sie können die Anmeldeinformationen auch so festlegen, dass die autorisierten SnapCenter-Benutzer über Berechtigungen auf Anwendungsebene verfügen.

* Erstellung platzsparender und zeitpunktgenauer Kopien von Ressourcen für Tests oder Datenextraktion mit der NetApp FlexClone Technologie
+
Auf dem Storage-System, auf dem Sie den Klon erstellen möchten, ist eine FlexClone Lizenz erforderlich.

* Unterstützung der Snapshot-Kopie der Konsistenzgruppe (CG) von ONTAP im Rahmen der Erstellung von Backups
* Fähigkeit, mehrere Backups gleichzeitig über mehrere Ressourcen-Hosts auszuführen
+
In einem einzigen Vorgang werden Snapshot Kopien konsolidiert, wenn Ressourcen eines einzelnen Hosts dasselbe Volume gemeinsam nutzen.

* Funktion zum Erstellen von Snapshot Kopien mithilfe externer Befehle.
* Funktion zur Erstellung dateisystemkonsistenter Snapshot Kopien in Windows Umgebungen

