---
permalink: protect-scc/snapcenter_custom_plug_ins_features.html 
sidebar: sidebar 
keywords: custom plug-ins features 
summary: SnapCenter lässt sich in die Plug-in-Applikation und mit NetApp Technologien auf dem Storage-System integrieren. Zum Arbeiten mit benutzerdefinierten Plug-ins verwenden Sie die grafische Benutzeroberfläche von SnapCenter. 
---
= Benutzerdefinierte SnapCenter Plug-ins-Funktionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter lässt sich in die Plug-in-Applikation und mit NetApp Technologien auf dem Storage-System integrieren. Zum Arbeiten mit benutzerdefinierten Plug-ins verwenden Sie die grafische Benutzeroberfläche von SnapCenter.

* *Einheitliche grafische Benutzeroberfläche*
+
Die SnapCenter-Schnittstelle bietet Standardisierung und Konsistenz über Plug-ins und Umgebungen hinweg. Die SnapCenter Schnittstelle ermöglicht konsistente Backup-, Restore-, Recovery- und Klonvorgänge über alle Plug-ins hinweg, zentralisierte Berichterstellung, Dashboard-Ansichten auf einen Blick, rollenbasierte Zugriffssteuerung (Role Based Access Control, RBAC) und das Monitoring von Aufgaben über alle Plug-ins hinweg.

* *Automatisierte zentrale Verwaltung*
+
Sie können Backup-Vorgänge planen, richtlinienbasierte Backup-Aufbewahrung konfigurieren und Restore-Vorgänge durchführen. Zudem lässt sich die Umgebung proaktiv überwachen, indem SnapCenter für das Senden von E-Mail-Warnmeldungen konfiguriert wird.

* *Unterbrechungsfreie NetApp Snapshots*
+
SnapCenter nutzt NetApp Snapshot Technologie mit den benutzerdefinierten Plug-ins für das Backup von Ressourcen. Snapshots belegen nur minimalen Speicherplatz.



Die Verwendung benutzerdefinierter Plug-ins bietet darüber hinaus folgende Vorteile:

* Unterstützung für Backup-, Restore- und Klon-Workflows
* RBAC-unterstützte Sicherheit und zentralisierte Rollendelegation
+
Sie können die Anmeldeinformationen auch so festlegen, dass die autorisierten SnapCenter-Benutzer über Berechtigungen auf Anwendungsebene verfügen.

* Erstellung platzsparender und zeitpunktgenauer Kopien von Ressourcen für Tests oder Datenextraktion mit der NetApp FlexClone Technologie
+
Auf dem Storage-System, auf dem Sie den Klon erstellen möchten, ist eine FlexClone Lizenz erforderlich.

* Unterstützung der Snapshot-Funktion von ONTAP für Konsistenzgruppen (CG) beim Erstellen von Backups.
* Fähigkeit, mehrere Backups gleichzeitig über mehrere Ressourcen-Hosts auszuführen
+
In einem einzigen Vorgang werden Snapshots konsolidiert, wenn Ressourcen in einem einzelnen Host dasselbe Volume gemeinsam nutzen.

* Fähigkeit zum Erstellen von Snapshots mit externen Befehlen.
* Möglichkeit zur Erstellung Filesystem-konsistenter Snapshots in Windows Umgebungen.

