---
sidebar: sidebar 
permalink: sc-automation/task_get_started_with_the_rest_api.html 
keywords:  
summary: Der Zugriff auf die API bietet eine gewisse Perspektive, bevor Sie mit den komplexeren Workflow-Prozessen bei Live-Einrichtung beginnen. 
---
= Legen Sie los mit DER REST API
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Die SnapCenter REST API ist ein schneller Einstieg. Der Zugriff auf die API bietet eine gewisse Perspektive, bevor Sie mit den komplexeren Workflow-Prozessen bei Live-Einrichtung beginnen.



== Hallo Welt

Sie können einen einfachen Befehl auf Ihrem System ausführen, um die SnapCenter REST API zu verwenden und deren Verfügbarkeit zu bestätigen.

*Was Sie brauchen*

* Stellen Sie sicher, dass das Curl-Dienstprogramm auf Ihrem System verfügbar ist.
* IP-Adresse oder Hostname des SnapCenter-Servers
* Benutzername und Passwort für ein Konto mit Berechtigung für den Zugriff auf die SnapCenter REST API.



NOTE: Wenn Ihre Anmeldeinformationen Sonderzeichen enthalten, müssen Sie diese auf der Grundlage der verwendeten Shell so formatieren, dass sie für Curl akzeptabel sind. Sie können z. B. vor jedem Sonderzeichen einen umgekehrten Schrägstrich einfügen oder den gesamten Buchstaben umwickeln `username:password` Zeichenfolge in einzelnen Anführungszeichen.

*Schritt*

Führen Sie bei der Befehlszeilenschnittstelle Folgendes aus, um die Plug-in-Informationen abzurufen:

`curl -X GET -u username:password -k "https://<ip_address>/api/hosts?fields=IncludePluginInfo"`

Beispiel:

`curl -X GET -u admin:password -k "'https://10.225.87.97/api/hosts?fields=IncludePluginInfo"`
