---
permalink: protect-azure/add-hosts-install-plugin-for-oracle.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, oracle, database 
summary: Fügen Sie Hosts hinzu, und installieren Sie dann die Plug-ins-Pakete. 
---
= Fügen Sie Hosts hinzu und installieren Sie das SnapCenter Plug-in für die Oracle-Datenbank
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Host hinzufügen“ können Sie Hosts hinzufügen, und dann das SnapCenter Plug-ins Paket für Linux oder SnapCenter Plug-ins Package für AIX installieren. Die Plug-ins werden automatisch auf den Remote-Hosts installiert.

Sie können einen Host hinzufügen und Plug-in-Pakete für einen einzelnen Host oder für ein Cluster installieren. Wenn Sie das Plug-in auf einem Cluster (Oracle RAC) installieren, wird das Plug-in auf allen Knoten des Clusters installiert. Für Oracle RAC One Node sollten Sie das Plug-in sowohl auf aktiven als auch auf passiven Knoten installieren.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Hosts*.
. Vergewissern Sie sich, dass die Registerkarte *verwaltete Hosts* ausgewählt ist.
. Klicken Sie Auf *Hinzufügen*.
. Führen Sie auf der Seite Hosts die folgenden Aktionen durch:
+
.. Wählen Sie im Feld Hosttyp den Hosttyp aus.
.. Geben Sie im Feld Hostname den vollständig qualifizierten Domänennamen (FQDN) oder die IP-Adresse des Hosts ein.
.. Geben Sie im Feld Anmeldeinformationen die von Ihnen erstellten Anmeldeinformationen ein.


. Wählen Sie im Abschnitt Plug-ins zum Installieren auswählen die zu installierenden Plug-ins aus.
. (Optional) Klicken Sie auf *Weitere Optionen* und geben Sie die Details an.
. Klicken Sie Auf *Absenden*.
. Überprüfen Sie den Fingerabdruck, und klicken Sie dann auf *Bestätigen und Senden*.
+
In einer Cluster-Einrichtung sollten Sie den Fingerabdruck aller Nodes im Cluster überprüfen.

. Überwachen Sie den Installationsfortschritt.

