---
permalink: protect-azure/backup-sql-resource-groups.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SQL Server Database, back up, resource groups 
summary: Eine Ressourcengruppe ist eine Sammlung von Ressourcen auf einem Host. Für alle in der Ressourcengruppe definierten Ressourcen wird ein Sicherungsvorgang in der Ressourcengruppe durchgeführt. 
---
= Sichern Sie SQL Server-Ressourcengruppen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Ressourcengruppen sichern, die aus mehreren Ressourcen bestehen. Für alle in der Ressourcengruppe definierten Ressourcen wird ein Sicherungsvorgang in der Ressourcengruppe durchgeführt.

.Schritte
. Wählen Sie im linken Navigationsbereich *Ressourcen* aus, und wählen Sie dann das entsprechende Plug-in aus der Liste aus.
. Wählen Sie auf der Seite Ressourcen in der Liste *Ansicht* die Option *Ressourcengruppe* aus.
. Wählen Sie auf der Seite Ressourcengruppen die Ressourcengruppe aus, die Sie sichern möchten, und wählen Sie dann *Jetzt sichern* aus.
. Führen Sie auf der Seite Backup die folgenden Schritte aus:
+
.. Wenn der Ressourcengruppe mehrere Richtlinien zugeordnet sind, wählen Sie aus der Dropdown-Liste *Policy* die Richtlinie aus, die Sie für das Backup verwenden möchten.
.. Wählen Sie nach dem Backup *Verify* aus, um das On-Demand-Backup zu überprüfen.
.. Wählen Sie *Backup*.


. Überwachen Sie den Vorgangsfortschritt, indem Sie *Monitor* > *Jobs* auswählen.

