---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Erstellen Sie die Azure-Zugangsdaten in SnapCenter, um auf das Azure NetApp-Konto zuzugreifen. 
---
= Erstellen Sie die Azure-Zugangsdaten in SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die Azure-Anmeldeinformationen in SnapCenter erstellen, um auf das Azure NetApp-Konto zuzugreifen.

.Bevor Sie beginnen
* Stellen Sie sicher, dass Sie den Dienstprinzipal in Azure erstellt haben.
* Stellen Sie sicher, dass Ihnen die Mandanten-ID, die Client-ID und der geheime Schlüssel für den Dienstprinzipal zur Verfügung stehen.
+
** Die Mandanten-ID ist im Azure-Portal auf der Übersichtsseite für die Entra ID verfügbar.
** Die Client-ID wird auch als Anwendungs-ID für den Enterprise App/Service Principal bezeichnet. Sie finden dies im Azure-Portal auf der Seite „Übersicht“ für die von Ihnen erstellte Enterprise-Applikation, die als Service Principal für SnapCenter fungiert.
** Der Client Secret Key wird auch als Secret Value bezeichnet. Sie können diesen Client-Schlüssel im Azure-Portal erstellen, indem Sie unter Entra-ID zu *App-Registrierungen* navigieren. Nachdem Sie die von Ihnen erstellte Enterprise App ausgewählt haben, navigieren Sie zu *Certificates & Secrets* und dann zu *New Client secret*.
+

NOTE: Auf den geheimen Wert kann nur bei der Erstellung zugegriffen werden. Sie können später nicht darauf zugreifen.

** Dem Service Principal müssen Berechtigungen gewährt werden. Die Rolle des Contributors ermöglicht es dem Service-Principal, erforderliche Aktionen in Azure durchzuführen. Dies kann über die Seite Zugriffssteuerung (Access Control, IAM) auf der Seite Abonnement gewährt werden.




.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite Einstellungen auf *Credential*.
. Klicken Sie Auf *Neu*.
. Geben Sie auf der Seite Anmeldeinformationen die folgenden Informationen an, die zum Erstellen der Anmeldeinformationen erforderlich sind.
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Anmeldeinformationsname
 a| 
Geben Sie einen Namen für die Anmeldedaten ein.



 a| 
Authentifizierungsmodus
 a| 
Wählen Sie *Azure Credential* aus der Dropdown-Liste aus.



 a| 
Mandanten-ID
 a| 
Geben Sie die Mandanten-ID ein.



 a| 
Client-ID
 a| 
Geben Sie die Client-ID ein.



 a| 
Geheimer Client-Schlüssel
 a| 
Geben Sie den geheimen Client-Schlüssel ein.

|===
. Klicken Sie auf *OK*.

