---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Erstellen Sie die Azure-Zugangsdaten in SnapCenter, um auf das Azure NetApp-Konto zuzugreifen. 
---
= Erstellen Sie die Azure-Zugangsdaten in SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die Azure-Anmeldeinformationen in SnapCenter erstellen, um auf das Azure NetApp-Konto zuzugreifen.

Stellen Sie vor dem Erstellen der Azure-Anmeldeinformationen sicher, dass Sie den Dienstprinzipal in Azure erstellt haben. Zum Erstellen der Azure-Zugangsdaten müssen die Mandanten-ID, die Client-ID und der geheime Schlüssel, die dem Service-Principal zugeordnet sind, angegeben werden.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite Einstellungen auf *Credential*.
. Klicken Sie Auf *Neu*.
. Geben Sie auf der Seite Anmeldeinformationen die folgenden Informationen an, die zum Erstellen der Anmeldeinformationen erforderlich sind.
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Anmeldeinformationsname
 a| 
Geben Sie einen Namen für die Anmeldedaten ein.



 a| 
Authentifizierungsmodus
 a| 
Wählen Sie *Azure Credential* aus der Dropdown-Liste aus.



 a| 
Mandanten-ID
 a| 
Geben Sie die Mandanten-ID ein.



 a| 
Client-ID
 a| 
Geben Sie die Client-ID ein.



 a| 
Geheimer Client-Schlüssel
 a| 
Geben Sie den geheimen Client-Schlüssel ein.

|===
. Klicken Sie auf *OK*.

