---
permalink: protect-azure/create-credential-add-plugin-host.html 
sidebar: sidebar 
keywords: snapcenter, azure, credential, plug-in host 
summary: Erstellen Sie die Anmeldeinformationen, um den Plug-in-Host hinzuzufügen. 
---
= Erstellen Sie die Anmeldeinformationen, um den Plug-in-Host hinzuzufügen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter verwendet Zugangsdaten, um Benutzer für SnapCenter-Vorgänge zu authentifizieren.

Sie sollten Anmeldedaten für die Installation von SnapCenter-Plug-ins und zusätzliche Anmeldedaten für die Durchführung von Datensicherungsvorgängen erstellen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite Einstellungen auf *Credential*.
. Klicken Sie Auf *Neu*.
. Geben Sie auf der Seite Anmeldeinformationen die folgenden Informationen an, die zum Erstellen der Anmeldeinformationen erforderlich sind.
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Anmeldeinformationsname
 a| 
Geben Sie einen Namen für die Anmeldedaten ein.



 a| 
Authentifizierungsmodus
 a| 
Wählen Sie den Authentifizierungsmodus aus der Dropdown-Liste aus.



 a| 
Authentifizierungstyp
 a| 
Wählen Sie entweder *passwortbasiert* oder *SSH Key basiert* (nur für Linux-Host).



 a| 
Benutzername
 a| 
Geben Sie den Benutzernamen an.



 a| 
Passwort
 a| 
Wenn Sie die passwortbasierte Authentifizierung ausgewählt haben, geben Sie das Kennwort an.



 a| 
Privater SSH-Schlüssel
 a| 
Wenn Sie SSH Key Based Authentication ausgewählt haben, geben Sie den privaten Schlüssel an.



 a| 
Sudo-Berechtigungen verwenden
 a| 
Aktivieren Sie das Kontrollkästchen Sudo-Berechtigungen verwenden, wenn Sie Anmeldeinformationen für einen Benutzer ohne Root erstellen.


NOTE: Dies gilt nur für Linux-Benutzer.

|===
. Klicken Sie auf *OK*.

