---
permalink: protect-azure/create-backup-policies-sap-hana.html 
sidebar: sidebar 
keywords: create policies, SAP HANA, backup policies 
summary: Erstellen Sie eine Sicherungsrichtlinie für die Ressource oder Ressourcengruppe, die Sie sichern möchten. 
---
= Backup-Richtlinien für SAP HANA Datenbanken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie SnapCenter zum Sichern von SAP HANA-Datenbankressourcen verwenden, müssen Sie eine Backup-Richtlinie für die Ressource oder Ressourcengruppe erstellen, die Sie sichern möchten.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite Einstellungen auf *Richtlinien*.
. Klicken Sie Auf *Neu*.
. Geben Sie auf der Seite Name den Namen und die Beschreibung der Richtlinie ein.
. Führen Sie auf der Seite Richtlinientyp die folgenden Schritte durch:
+
.. Wählen Sie *Azure NetApp Files* als Speichertyp aus.
.. Wählen Sie *dateibasiert*, wenn Sie eine Integritätsprüfung der Datenbank durchführen möchten.
.. Wählen Sie *Snapshot-basiert*, wenn Sie ein Backup mit Snapshot-Technologie erstellen möchten.


. Führen Sie auf der Seite Snapshot und Backup die folgenden Schritte durch:
+
.. Wählen Sie die Häufigkeit der geplanten Sicherung aus.
.. Legen Sie die Aufbewahrungseinstellungen fest.
.. Wenn Sie die Azure NetApp Files-Sicherung aktivieren möchten, wählen Sie *Sicherung aktivieren* und geben Sie die Aufbewahrungseinstellungen an.


. Überprüfen Sie die Zusammenfassung und klicken Sie auf *Fertig stellen*.

