---
permalink: admin/concept_manage_the_snapcenter_server_repository.html 
sidebar: sidebar 
keywords: SnapCenter Server 
summary: Informationen zu verschiedenen von SnapCenter durchgeführten Vorgängen werden im Datenbank-Repository des SnapCenter Servers gespeichert. Sie müssen Backups des Repositorys erstellen, um den SnapCenter-Server vor Datenverlust zu schützen. 
---
= Verwalten des SnapCenter-Server-Repositorys
:allow-uri-read: 


[role="lead"]
Informationen zu verschiedenen von SnapCenter durchgeführten Vorgängen werden im Datenbank-Repository des SnapCenter Servers gespeichert. Sie müssen Backups des Repositorys erstellen, um den SnapCenter-Server vor Datenverlust zu schützen.

Das SnapCenter Server-Repository wird manchmal auch als NSM-Datenbank bezeichnet. Siehe die  https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter Software Cmdlet Referenzhandbuch"^] für Einzelheiten zu allen verfügbaren Cmdlets.



== Voraussetzungen für den Schutz des SnapCenter-Repositorys

Ihre Umgebung sollte bestimmte Voraussetzungen zum Schutz des SnapCenter-Repositorys erfüllen.

* Managen von Storage Virtual Machine-Verbindungen (SVM
+
Sie sollten die Speicher-Anmeldeinformationen konfigurieren.

* Bereitstellung von Hosts
+
Auf dem SnapCenter Repository-Host sollte mindestens eine NetApp Speicherplatte vorhanden sein. Wenn auf dem SnapCenter Repository-Host kein NetApp-Laufwerk vorhanden ist, müssen Sie ein Laufwerk erstellen.

+
Informationen zum Hinzufügen von Hosts, zum Einrichten von SVM-Verbindungen und zum Bereitstellen von Hosts finden Sie in den Installationsanweisungen.

* Bereitstellung von iSCSI LUN oder VMDK
+
Für Hochverfügbarkeitskonfigurationen (HA) können Sie ein iSCSI-LUN oder eine VMDK auf einem der SnapCenter-Server bereitstellen.





== Sichern des SnapCenter Repositorys

Durch die Sicherung des SnapCenter Server-Repositorys wird es vor Datenverlust geschützt. Sie können das Repository sichern, indem Sie das  `Protect-SmRepository` Cmdlet ausführen.

.Über diese Aufgabe
Das  `Protect-SmRepository` cmdlet erfüllt folgende Aufgaben:

* Erstellt eine Ressourcengruppe und eine Richtlinie
* Erstellt einen Backup-Zeitplan für das SnapCenter-Repository


.Schritte
. Starten Sie PowerShell.
. Stellen Sie auf dem SnapCenter Serverhost mithilfe des  `Open-SmConnection` cmdlets eine Sitzung her und geben Sie Ihre Anmeldeinformationen ein.
. Sichern Sie das Repository mithilfe des  `Protect-SmRepository` Cmdlets, das die folgenden erforderlichen Parameter benötigt:
+
.. `-HostName (String)`: Gibt den Hostnamen des Servers an, auf dem sich das SnapCenter-Repository befindet.
.. `-Path (String)`: Gibt den Dateisystempfad auf dem NetApp Storage-System an, auf dem die Repository-Backups gespeichert sind.
.. `-Schedule (Hashtable)`: Definiert den Zeitplan für das Repository-Backup. Es wird typischerweise als Hashtabelle definiert.
.. `-RetentionCount (Int32)`: Gibt die Anzahl der aufzubewahrenden Repository-Backups an. Wenn die Anzahl der Backups diese Zahl überschreitet, wird das älteste Backup gelöscht.






== Anzeigen von Backups des SnapCenter Repositorys

Sie können eine Liste der SnapCenter Server-Datenbank-Repository-Backups anzeigen, indem Sie das  `Get-SmRepositoryBackups` Cmdlet ausführen. Weitere Informationen finden Sie in der  https://docs.netapp.com/us-en/snapcenter-cmdlets/Get-SmRepositoryBackups.html["SnapCenter Software Cmdlet-Referenzhandbuch – Get-SmRepositoryBackups"^].

Die Repository-Backups werden gemäß dem im  `Protect-SmRepository` cmdlet festgelegten Zeitplan erstellt.

.Schritte
. Starten Sie PowerShell.
. Geben Sie an der Eingabeaufforderung das  `Open-SmConnection` Cmdlet ein und geben Sie die Anmeldeinformationen für die Verbindung zum SnapCenter Server an.
. Alle verfügbaren SnapCenter Datenbank-Backups mit dem  `Get-SmRepositoryBackups` Cmdlet auflisten.




== Wiederherstellung des SnapCenter Datenbank-Repositorys

Sie können das SnapCenter repository wiederherstellen, indem Sie das  `Restore-SmRepositoryBackup` cmdlet ausführen.

Wenn Sie das SnapCenter-Repository wiederherstellen, werden andere SnapCenter-Vorgänge beeinträchtigt, da während des Wiederherstellungsvorgangs die Repository-Datenbank nicht zugänglich ist.

.Schritte
. Starten Sie PowerShell.
. Geben Sie an der Eingabeaufforderung das  `Open-SmConnection` Cmdlet ein und geben Sie die Anmeldeinformationen für die Verbindung zum SnapCenter Server an.
. Stellen Sie das Repository-Backup mit dem  `Restore-SmRepositoryBackup` Cmdlet wieder her.
+
Mit dem folgenden Cmdlet wird das SnapCenter MySQL Datenbank-Repository aus den auf iSCSI LUN oder VMDK vorhandenen Backups wiederhergestellt:

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445
----
+
Mit dem folgenden Cmdlet wird die SnapCenter MySQL Datenbank wiederhergestellt, wenn Backup-Dateien versehentlich in der iSCSI-LUN gelöscht werden. Für VMDK stellen Sie das Backup manuell aus ONTAP-Snapshots wieder her.

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445 -RestoreFileSystem
----



NOTE: Das Backup, das zur Durchführung des Repository-Wiederherstellungsvorgangs verwendet wurde, wird nicht aufgeführt, wenn die Repository-Backups nach Durchführung der Wiederherstellung abgerufen werden.



== SnapCenter-Repository migrieren

Sie können das Datenbank-Repository des SnapCenter-Servers vom Standardspeicherort auf ein anderes Laufwerk migrieren. Sie können das Repository migrieren, wenn Sie es auf eine Festplatte mit mehr Speicherplatz verschieben möchten.

.Schritte
. Beenden Sie den MYSQL57-Dienst in Windows.
. Suchen Sie das MySQL-Datenverzeichnis.
+
Das Datenverzeichnis finden Sie in der Regel unter C:\ProgramData\MySQL\MySQL Server 5.7\Data.

. Kopieren Sie das MySQL-Datenverzeichnis in den neuen Speicherort, z. B. E:\Data\nsm.
. Klicken Sie mit der rechten Maustaste auf das neue Verzeichnis, und wählen Sie dann *Eigenschaften* > *Sicherheit* aus, um das lokale Network Service Server-Konto dem neuen Verzeichnis hinzuzufügen, und weisen Sie dann die volle Kontrolle zu.
. Benennen Sie das ursprüngliche Datenbankverzeichnis um, z. B. nsm_copy.
. Erstellen Sie in einer Windows-Eingabeaufforderung mithilfe des Befehls _mklink_ einen symbolischen Verzeichnislink.
+
`"mklink /d "C:\ProgramData\MySQL\MySQL Server 5.7\Data\nsm" "E:\Data\nsm" "`

. Starten Sie den MYSQL57-Dienst unter Windows.
. Stellen Sie sicher, dass die Änderung des Datenbankstandorts erfolgreich ist, indem Sie sich bei SnapCenter anmelden und Repository-Einträge überprüfen, oder indem Sie sich beim MySQL-Dienstprogramm anmelden und eine Verbindung zum neuen Repository herstellen.
. Löschen Sie das ursprüngliche, umbenannte Datenbank-Repository-Verzeichnis (nsm_copy).




== Setzen Sie das SnapCenter Repository-Kennwort zurück

Das MySQL Server Repository-Datenbankkennwort wird bei der Installation des SnapCenter Servers von SnapCenter 4.2 automatisch generiert. Dieses automatisch generierte Passwort ist dem SnapCenter-Benutzer an keinem Punkt bekannt. Wenn Sie auf die Repository-Datenbank zugreifen möchten, sollten Sie das Passwort zurücksetzen.

.Bevor Sie beginnen
Sie sollten über die SnapCenter-Administratorrechte verfügen, um das Kennwort zurückzusetzen.

.Schritte
. Starten Sie PowerShell.
. Geben Sie an der Eingabeaufforderung das  `Open-SmConnection` Cmdlet ein und geben Sie die Anmeldeinformationen für die Verbindung zum SnapCenter Server an.
. Setzen Sie das Repository-Passwort mit dem  `Set-SmRepositoryPassword` Cmdlet zurück.
+
Mit dem folgenden Befehl wird das Repository-Passwort zurückgesetzt:

+
[listing]
----

Set-SmRepositoryPassword at command pipeline position 1
Supply values for the following parameters:
NewPassword: ********
ConfirmPassword: ********
Successfully updated the MySQL server password.
----


.Verwandte Informationen
Sie können die Informationen zu den Parametern, die Sie mit dem Cmdlet verwenden können, und deren Beschreibungen erhalten, indem Sie den  `Get-Help command_name` Befehl ausführen. Alternativ können Sie auf die  https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter Software Cmdlet Referenzhandbuch"^] verweisen.
