---
permalink: protect-postgresql/restore-postgresql-using-powershell-cmdlets.html 
sidebar: sidebar 
keywords: restore, postgresql, snapcenter 
summary: Zum Wiederherstellen eines PostgreSQL-Backups gehört das Initiieren einer Verbindungssitzung mit dem SnapCenter-Server, das Auflisten der Backups und das Abrufen von Sicherungsinformationen sowie das Wiederherstellen eines Backups. 
---
= Stellen Sie PostgreSQL-Cluster mithilfe von PowerShell Cmdlets wieder her
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Wiederherstellen eines PostgreSQL-Backups gehört das Initiieren einer Verbindungssitzung mit dem SnapCenter-Server, das Auflisten der Backups und das Abrufen von Sicherungsinformationen sowie das Wiederherstellen eines Backups.

.Bevor Sie beginnen
Sie müssen die PowerShell Umgebung vorbereitet haben, um die PowerShell Cmdlets auszuführen.

.Schritte
. Starten Sie eine Verbindungssitzung mit dem SnapCenter-Server für einen bestimmten Benutzer, indem Sie das Cmdlet "Open-SmConnection" verwenden.
+
[listing]
----
PS C:\> Open-SmConnection
----
. Identifizieren Sie das wiederherzustellende Backup mit den Cmdlets Get-SmBackup und Get-SmBackupReport.
+
Dieses Beispiel zeigt, dass zwei Backups für die Wiederherstellung verfügbar sind:

+
[listing]
----
 PS C:\> Get-SmBackup

        BackupId    BackupName                    BackupTime            BackupType
        --------    ----------                    ----------            ----------
         1          Payroll Dataset_vise-f6_08... 8/4/2015 11:02:32 AM  Full Backup
         2          Payroll Dataset_vise-f6_08... 8/4/2015 11:23:17 AM
----
+
Dieses Beispiel zeigt detaillierte Informationen zum Backup vom 29. Januar 2015 bis 3. Februar 2015 an:

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. Stellen Sie Daten aus dem Backup mit dem Cmdlet "Restore-SmBackup" wieder her.
+

NOTE: AppObjectId ist "Host\Plugin\UID", wobei UID = <instance_name> für manuell erkannte PostgreSQL-Instanzressource und UID = <instance_name>\<databse_name> für PostgreSQL-Clusterressource ist. Sie erhalten die ResourceID aus dem Cmdlet "Get-smResources".

+
[listing]
----
Get-smResources  -HostName cn24.sccore.test.com  -PluginCode PostgreSQL
----
+
Dieses Beispiel zeigt, wie das Cluster aus dem primären Speicher wiederhergestellt wird:

+
[listing]
----
Restore-SmBackup -PluginCode PostgreSQL -AppObjectId cn24.sccore.test.com\PostgreSQL\PostgreSQLinst1\DB01 -BackupId 3
----
+
Dieses Beispiel zeigt, wie das Cluster aus dem sekundären Speicher wiederhergestellt wird:

+
[listing]
----
Restore-SmBackup -PluginCode 'PostgreSQL' -AppObjectId cn24.sccore.test.com\DB2\db2inst1\DB01 -BackupId 399 -Confirm:$false  -Archive @( @{"Primary"="<Primary Vserver>:<PrimaryVolume>";"Secondary"="<Secondary Vserver>:<SecondaryVolume>"})
----
+
Die Informationen zu den Parametern, die mit dem Cmdlet und deren Beschreibungen verwendet werden können, können durch Ausführen von _get-Help Command_Name_ abgerufen werden. Alternativ können Sie auch auf die https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter Software Cmdlet Referenzhandbuch"^].


