---
permalink: protect-postgresql/storage-types-supported-by-snapcenter-plug-in-for-postgresql.html 
sidebar: sidebar 
keywords: storage types, 
summary: 'SnapCenter unterstützt eine Vielzahl von Storage-Typen sowohl auf physischen Computern als auch auf Virtual Machines (VMs). Sie müssen die Unterstützung für Ihren Speichertyp überprüfen, bevor Sie das SnapCenter-Plug-in für PostgreSQL installieren.' 
---
= Von SnapCenter Plug-in für PostgreSQL unterstützte Speichertypen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter unterstützt eine Vielzahl von Storage-Typen sowohl auf physischen Computern als auch auf Virtual Machines (VMs). Sie müssen die Unterstützung für Ihren Speichertyp überprüfen, bevor Sie das SnapCenter-Plug-in für PostgreSQL installieren.

|===
| Maschine | Storage-Typ 


 a| 
Physischer Server
 a| 
* FC-verbundene LUNs
* ISCSI-verbundene LUNs
* Volumes mit NFS-Anbindung




 a| 
VMware ESXi
 a| 
* RDM-LUNs, die über ein FC- oder iSCSI-ESXi HBASCAning der Host Bus Adapter (HBAs) verbunden sind, können viel Zeit in Anspruch nehmen, da SnapCenter alle im Host vorhandenen Host-Bus-Adapter scannt.
+
Sie können die Datei *LinuxConfig.pm* unter _/opt/NetApp/snapcenter/spl/Plugins/scu/scucore/modules/SCU/Config_ bearbeiten, um den Wert des *SCSI_HOSTS_OPTIMIZED_RECAN* Parameters auf 1 zu setzen, um nur die in HBA_DRIVER_NAMES aufgeführten HBAs erneut zu scannen.

* ISCSI-LUNs, die direkt über den iSCSI-Initiator mit dem Gastsystem verbunden sind
* VMDKs auf NFS-Datastores
* VMDKs auf VMFS
* NFS-Volumes sind direkt mit dem Gastbetriebssystem verbunden
* VVol Datastores auf NFS und SAN
+
VVol Datastore kann nur mit ONTAP Tools für VMware vSphere bereitgestellt werden.



|===