---
permalink: protect-postgresql/types-of-restore-strategies-supported-for-manually-added-postgresql.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Sie müssen eine Strategie definieren, bevor Sie die Restore-Vorgänge mit SnapCenter erfolgreich durchführen können. Es gibt zwei Arten von Wiederherstellungsstrategien für manuell hinzugefügte PostgreSQL-Ressourcen. Manuell hinzugefügte PostgreSQL-Ressourcen können nicht wiederhergestellt werden. 
---
= Arten von Wiederherstellungsstrategien, die für manuell hinzugefügte PostgreSQL-Ressourcen unterstützt werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen eine Strategie definieren, bevor Sie die Restore-Vorgänge mit SnapCenter erfolgreich durchführen können.


NOTE: Manuell hinzugefügte PostgreSQL-Ressourcen können nicht wiederhergestellt werden.



== Komplette Ressourcenwiederherstellung

* Stellt alle Volumes, qtrees und LUNs einer Ressource wieder her



NOTE: Wenn die Ressource Volumes oder qtrees enthält, werden die Snapshots, die nach dem ausgewählten Snapshot für die Wiederherstellung auf diesen Volumes oder qtrees erstellt wurden, gelöscht und können nicht wiederhergestellt werden. Wenn auch eine andere Ressource auf den gleichen Volumes oder qtrees gehostet wird, wird diese Ressource auch gelöscht.

HINWEIS: Plug-in für PostgreSQL erstellt ein Backup_Label und tablespace_map im Ordner _/<OS_temp_folder>/postgresql_sc_Recovery_<Restore_JobId>/_, um die manuelle Wiederherstellung zu unterstützen.
