---
permalink: install/concept_snapcenter_licenses.html 
sidebar: sidebar 
keywords: licenses, FAS, AFF, ASA, SnapMirror, SnapVault, SnapRestore, FlexClone, SMBR, Single Mailbox Recovery 
summary: Für die Aktivierung von Datensicherungsvorgängen SnapCenter sind mehrere Lizenzen erforderlich. Die Art der installierten SnapCenter Lizenzen hängt von Ihrer Storage-Umgebung und den gewünschten Funktionen ab. 
---
= SnapCenter-Lizenzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Datensicherung von Applikationen, Datenbanken, Filesystemen und Virtual Machines benötigt SnapCenter mehrere Lizenzen. Die Art der installierten SnapCenter Lizenzen hängt von Ihrer Storage-Umgebung und den gewünschten Funktionen ab.

|===
| Lizenz | Bei Bedarf 


 a| 
SnapCenter Standard Controller-basiert
 a| 
Erforderlich für FAS, AFF, All-SAN-Array (ASA)

Bei der SnapCenter Standardlizenz handelt es sich um eine Controller-basierte Lizenz, die als Teil von ONTAP One enthalten ist. Wenn Sie die Lizenz für die SnapManager Suite besitzen, erhalten Sie auch die Standardlizenz von SnapCenter. Wenn Sie SnapCenter als Testlizenz mit FAS, AFF oder ASA Storage installieren möchten, erhalten Sie bei Ihrem Vertriebsmitarbeiter eine Evaluierungslizenz für ONTAP One.

Informationen zu Lizenzen, die in ONTAP One enthalten sind, finden Sie unter https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["In ONTAP One enthaltene Lizenzen"].


NOTE: SnapCenter ist auch als Teil des Datensicherungs-Bundles verfügbar. Wenn Sie A400 oder höher erworben haben, sollten Sie ein Datensicherungs-Bundle erwerben.



 a| 
SnapMirror oder SnapVault
 a| 
ONTAP

Wenn die Replizierung in SnapCenter aktiviert ist, ist entweder eine SnapMirror oder eine SnapVault Lizenz erforderlich.



 a| 
SnapRestore
 a| 
Für die Wiederherstellung und Überprüfung von Backups erforderlich.

Auf primären Storage-Systemen

* Erforderlich auf SnapVault Zielsystemen, um eine Remote-Verifizierung und die Wiederherstellung aus einem Backup durchzuführen.
* Erforderlich auf SnapMirror Zielsystemen für die Remote-Verifizierung




 a| 
FlexClone
 a| 
Die für das Klonen von Datenbanken und Verifizierungsvorgängen erforderlich sind.

Auf primären und sekundären Storage-Systemen

* Erforderlich auf SnapVault Zielsystemen, um Klone aus dem sekundären Vault Backup zu erstellen.
* Erforderlich auf SnapMirror Zielsystemen, um Klone aus dem sekundären SnapMirror Backup zu erstellen.




 a| 
Protokolle
 a| 
* ISCSI- oder FC-Lizenz für LUNs
* CIFS-Lizenz für SMB-Freigaben
* NFS-Lizenz für NFS-Typ VMDKs
* ISCSI- oder FC-Lizenz für VMFS-VMDKs des Typs VMDK


Ist auf SnapMirror Zielsystemen erforderlich, um Daten bereitzustellen, wenn ein Quell-Volume nicht verfügbar ist.



 a| 
SnapCenter-Standardlizenzen (optional)
 a| 
Sekundäre Ziele


NOTE: Es wird empfohlen, aber nicht erforderlich, dass Sie SnapCenter Standard-Lizenzen zu sekundären Zielen hinzufügen. Wenn SnapCenter Standardlizenzen nicht für sekundäre Ziele aktiviert sind, können Sie nach einem Failover-Vorgang SnapCenter nicht für ein Backup von Ressourcen auf dem sekundären Ziel verwenden. Allerdings ist eine FlexClone Lizenz für sekundäre Ziele erforderlich, um Klon- und Verifizierungsvorgänge durchzuführen.

|===

NOTE: Lizenzen für SnapCenter Advanced- und SnapCenter-NAS-Fileservices sind veraltet und sind nicht mehr verfügbar. Für Amazon FSX for NetApp ONTAP, ONTAP Select, Cloud Volumes ONTAP und Azure NetApp Files sind die Standardlizenz und die kapazitätsbasierte Lizenz nicht mehr erforderlich.

Sie sollten eine oder mehrere SnapCenter Lizenzen installieren. Informationen zum Hinzufügen von Lizenzen finden Sie unter link:../install/concept_snapcenter_standard_controller_based_licenses.html["Controller-basierte SnapCenter Standard-Lizenzen hinzufügen"].



== Single Mailbox Recovery-Lizenzen (SMBR

Wenn Sie für das Management von Microsoft Exchange Server Datenbanken und Single Mailbox Recovery (SMBR) mit dem SnapCenter Plug-in für Exchange arbeiten, benötigen Sie eine zusätzliche Lizenz für SMBR, die separat in Abhängigkeit von der Benutzer-Mailbox erworben werden muss.

Die Einstellung der Verfügbarkeit für NetApp Single Mailbox Recovery (EOA) steht am 12. Mai 2023 fest. Weitere Informationen finden Sie unter link:https://mysupport.netapp.com/info/communications/ECMLP2885729.html["CPC-00507"]. NetApp unterstützt Kunden, die für den Zeitraum der Support-Berechtigung Mailbox-Kapazität, Wartung und Support erworben haben, weiterhin über die am 24. Juni 2020 eingeführten Marketing-Teilenummern.

NetApp Single Mailbox Recovery ist ein Partnerprodukt von Ontrack. OnTrack PowerControls bietet ähnliche Funktionen wie NetApp Single Mailbox Recovery. Kunden können von Ontrack (bis licensingteam@ontrack.com) neue Ontrack PowerControls Softwarelizenzen und Ontrack PowerControls Wartungs- und Supportverlängerungen für eine granulare Mailbox-Recovery nach dem EOA-Datum vom 12. Mai 2023 beziehen.
