---
permalink: install/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication 
summary: Je nach Anwendung oder Umgebung verwenden Anmeldeinformationen unterschiedliche Authentifizierungsmethoden. Anmeldedaten authentifizieren Benutzer, sodass sie SnapCenter-Vorgänge ausführen können. Zum Installieren von Plug-ins und einem anderen Satz für Datensicherungsvorgänge sollten Sie einen Satz von Anmeldeinformationen erstellen. 
---
= Authentifizierungsmethoden für Ihre Anmeldedaten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Je nach Anwendung oder Umgebung verwenden Anmeldeinformationen unterschiedliche Authentifizierungsmethoden. Anmeldedaten authentifizieren Benutzer, sodass sie SnapCenter-Vorgänge ausführen können. Zum Installieren von Plug-ins und einem anderen Satz für Datensicherungsvorgänge sollten Sie einen Satz von Anmeldeinformationen erstellen.



== Windows Authentifizierung

Die Windows-Authentifizierungsmethode authentifiziert sich gegen Active Directory. Für die Windows-Authentifizierung wird Active Directory außerhalb von SnapCenter eingerichtet. SnapCenter authentifiziert sich ohne zusätzliche Konfiguration. Sie benötigen Windows-Anmeldedaten, um Aufgaben wie das Hinzufügen von Hosts, die Installation von Plug-in-Paketen und die Planung von Jobs auszuführen.



== Nicht vertrauenswürdige Domänenauthentifizierung

SnapCenter ermöglicht die Erstellung von Windows-Anmeldeinformationen unter Verwendung von Benutzern und Gruppen, die zu nicht vertrauenswürdigen Domänen gehören. Damit die Authentifizierung erfolgreich ist, sollten Sie die nicht vertrauenswürdigen Domains bei SnapCenter registrieren.



== Authentifizierung für lokale Arbeitsgruppen

SnapCenter ermöglicht die Erstellung von Windows-Anmeldeinformationen für Benutzer und Gruppen lokaler Arbeitsgruppen. Die Windows-Authentifizierung für Benutzer und Gruppen lokaler Arbeitsgruppen findet zum Zeitpunkt der Erstellung von Windows-Anmeldeinformationen nicht statt, wird jedoch verschoben, bis die Hostregistrierung und andere Hostvorgänge durchgeführt werden.



== SQL Server-Authentifizierung

Die SQL-Authentifizierungsmethode authentifiziert sich anhand einer SQL Server-Instanz. Das bedeutet, dass eine SQL Server-Instanz in SnapCenter erkannt werden muss. Daher müssen Sie vor dem Hinzufügen von SQL-Anmeldeinformationen einen Host hinzufügen, Plug-in-Pakete installieren und Ressourcen aktualisieren. Sie benötigen die SQL Server-Authentifizierung für Vorgänge wie die Planung auf SQL Server oder die Ermittlung von Ressourcen.



== Linux-Authentifizierung

Die Linux-Authentifizierungsmethode authentifiziert sich bei einem Linux-Host. Sie benötigen die Linux-Authentifizierung während des ersten Schritts des Hinzufügens des Linux-Hosts und der Remote-Installation des SnapCenter-Plug-ins-Pakets für Linux über die SnapCenter-Benutzeroberfläche.



== AIX Authentifizierung

Die AIX-Authentifizierungsmethode authentifiziert sich gegen einen AIX-Host. Sie benötigen eine AIX-Authentifizierung während des ersten Schritts, in dem Sie den AIX-Host hinzufügen und das SnapCenter Plug-ins Paket für AIX Remote von der SnapCenter-Benutzeroberfläche aus installieren.



== Oracle-Datenbankauthentifizierung

Die Oracle-Datenbankauthentifizierung authentifiziert sich anhand einer Oracle-Datenbank. Sie benötigen eine Oracle-Datenbankauthentifizierung, um Vorgänge in der Oracle-Datenbank auszuführen, wenn die Betriebssystemauthentifizierung auf dem Datenbank-Host deaktiviert ist. Daher sollten Sie vor dem Hinzufügen von Oracle-Datenbankberechtigungen einen Oracle-Benutzer in der Oracle-Datenbank mit sysdba-Berechtigungen erstellen.



== Oracle ASM Authentifizierung

Die Oracle ASM-Authentifizierungsmethode authentifiziert sich anhand einer Oracle Automatic Storage Management (ASM)-Instanz. Wenn Sie auf die Oracle ASM-Instanz zugreifen müssen und wenn die Betriebssystemauthentifizierung auf dem Datenbank-Host deaktiviert ist, benötigen Sie eine Oracle ASM-Authentifizierung. Daher sollten Sie vor dem Hinzufügen einer Oracle ASM-Berechtigung einen Oracle-Benutzer mit sysasm-Berechtigungen in der ASM-Instanz erstellen.



== RMAN-Katalogauthentifizierung

Die Authentifizierungsmethode des RMAN-Katalogs authentifiziert sich mit der Oracle Recovery Manager (RMAN)-Katalogdatenbank. Wenn Sie einen externen Katalogmechanismus konfiguriert und Ihre Datenbank in der Katalogdatenbank registriert haben, müssen Sie die RMAN-Katalogauthentifizierung hinzufügen.
