---
permalink: install/configure_ca_certificate_linux_host.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate, linux, linux host 
summary: Sie sollten das CA-Zertifikat mit SnapCenter-Server auf Linux-Host konfigurieren. 
---
= Konfigurieren Sie das CA-Zertifikat für den Linux-Host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Installation des SnapCenter-Servers unter Linux erstellt das Installationsprogramm das selbstsignierte Zertifikat. Wenn Sie das CA-Zertifikat verwenden möchten, sollten Sie die Zertifikate für nginx Reverse Proxy, Audit-Protokollierung und SnapCenter-Dienste konfigurieren.



== Konfigurieren Sie das nginx-Zertifikat

.Schritte
. Navigieren Sie zu _/etc/nginx/conf.d_: `cd /etc/nginx/conf.d`
. Öffnen Sie *snapcenter.conf* mit vi oder einem beliebigen Texteditor.
. Navigieren Sie zum Abschnitt Server in der Konfigurationsdatei.
. Ändern Sie die Pfade von _ssl_Certificate_ und _ssl_Certificate_Key_, um auf das CA-Zertifikat zu verweisen.
. Speichern und schließen Sie die Datei.
. Nginx neu laden: `$nginx -s reload`




== Konfigurieren Sie das Audit-Protokoll-Zertifikat

.Schritte
. Öffnen Sie _INSTALL_dir/NetApp/snapcenter/SnapManagerWeb/SnapManager.Web.UI.dll.config_ mithilfe von vi oder einem beliebigen Texteditor.
+
Der Standardwert von _INSTALL_dir_ ist _/opt_.

. Bearbeiten Sie die Schlüssel *AUDILOG_CERTIFICATE_PATH* und *AUDILOG_CERTIFICATE_PASSWORD*, um den CA-Zertifikatspfad und das Passwort einzuschließen.
+
Für das Auditprotokoll-Zertifikat wird nur das _.pfx_-Format unterstützt.

. Speichern und schließen Sie die Datei.
. Starten Sie den Dienst *SnapManager Web* neu: `$ systemctl restart snapmanagerweb`




== Konfigurieren Sie das Zertifikat für SnapCenter-Services

.Schritte
. Öffnen Sie die folgenden Konfigurationsdateien mit vi oder einem beliebigen Texteditor.
+
** _INSTALL_dir/NetApp/snapcenter/SnapManagerWeb/SnapManager.Web.UI.dll.config_
** _INSTALL_dir/NetApp/snapcenter/SMCore/SMCoreServiceHost.dll.config_
** _INSTALL_dir/NetApp/snapcenter/Scheduler/Scheduler.API.dll.config_
+
Der Standardwert von _INSTALL_dir_ ist _/opt_.



. Bearbeiten Sie die Schlüssel *SERVICE_CERTIFICATE_PATH* und *SERVICE_CERTIFICATE_PASSWORD*, um den CA-Zertifikatspfad und das entsprechende Passwort einzuschließen.
+
Für das SnapCenter-Servicezertifikat wird nur das _.pfx_-Format unterstützt.

. Speichern und schließen Sie die Dateien.
. Starten Sie alle Dienste neu.
+
** `$ systemctl restart snapmanagerweb`
** `$ systemctl restart smcore`
** `$ systemctl restart scheduler`



