---
permalink: install/reference_provision_storage_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie die SnapCenter GUI nicht zum Ausführen von Aufgaben zur Host-Bereitstellung und zur Speicherplatzrückgewinnung verwenden möchten, können Sie die PowerShell Commandlets verwenden, die vom SnapCenter Plug-in für Microsoft Windows zur Verfügung gestellt werden. Sie können Cmdlets direkt verwenden oder zu Skripten hinzufügen. 
---
= Stellen Sie Storage mit PowerShell cmdlets bereit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die SnapCenter GUI nicht zum Ausführen von Aufgaben zur Host-Bereitstellung und zur Speicherplatzrückgewinnung verwenden möchten, können Sie die PowerShell Commandlets verwenden, die vom SnapCenter Plug-in für Microsoft Windows zur Verfügung gestellt werden. Sie können Cmdlets direkt verwenden oder zu Skripten hinzufügen.

Wenn Sie die Cmdlets auf einem Remote-Plug-in-Host ausführen, müssen Sie das Cmdlet SnapCenter Open-SMConnection ausführen, um eine Verbindung zum SnapCenter Server zu öffnen.

Die Informationen zu den Parametern, die mit dem Cmdlet und deren Beschreibungen verwendet werden können, können durch Ausführen von _get-Help Command_Name_ abgerufen werden. Alternativ können Sie auch auf die verweisen https://["SnapCenter Software Cmdlet Referenzhandbuch"^].

Wenn SnapCenter PowerShell Cmdlets aufgrund der Entfernung von SnapDrive für Windows vom Server beschädigt sind, lesen Sie https://["SnapCenter cmdlets defekt, wenn SnapDrive für Windows deinstalliert wird"^].
