---
permalink: install/reference_space_and_sizing_requirements.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Vor der Installation des SnapCenter Servers sollten Sie mit den Platz- und Größenanforderungen vertraut sein. Sie sollten auch die verfügbaren System- und Sicherheitsupdates anwenden. 
---
= Platz- und Größenanforderungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Installation des SnapCenter Servers sollten Sie mit den Platz- und Größenanforderungen vertraut sein. Sie sollten auch die verfügbaren System- und Sicherheitsupdates anwenden.

|===
| Element | Windows-Host-Anforderungen | Anforderungen an Linux-Hosts 


 a| 
Betriebssysteme
 a| 
Microsoft Windows

Es werden nur englische, deutsche, japanische und vereinfachte chinesische Versionen der Betriebssysteme unterstützt.

Aktuelle Informationen zu unterstützten Versionen finden Sie unter https://imt.netapp.com/matrix/imt.jsp?components=121033;&solution=1258&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^].
 a| 
* Red hat Enterprise Linux (RHEL) 8 und 9
* SUSE Linux Enterprise Server (SLES) 15


Aktuelle Informationen zu unterstützten Versionen finden Sie unter https://imt.netapp.com/matrix/imt.jsp?components=121032;&solution=1258&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^].



 a| 
Minimale CPU-Anzahl
 a| 
4 Kerne
 a| 
4 Kerne



 a| 
Mind. RAM
 a| 
8 GB


NOTE: Der MySQL Server Pufferpool nutzt 20 Prozent des gesamten RAM.
 a| 
8 GB



 a| 
Minimaler Festplattenspeicher für die SnapCenter-Serversoftware und Protokolle
 a| 
7 GB


NOTE: Wenn sich das SnapCenter-Repository auf demselben Laufwerk befindet, auf dem SnapCenter-Server installiert ist, wird empfohlen, 15 GB zu verwenden.
 a| 
15 GB



 a| 
Minimaler Festplattenspeicher für das SnapCenter-Repository
 a| 
8 GB


NOTE: HINWEIS: Wenn der SnapCenter-Server auf demselben Laufwerk installiert ist, auf dem das SnapCenter-Repository installiert ist, wird empfohlen, 15 GB zu verwenden.
 a| 
Keine Angabe



 a| 
Erforderliche Softwarepakete
 a| 
* ASP.NET Core Runtime 8.0.12 (und alle nachfolgenden 8.0.x-Patches) Hosting Bundle
* PowerShell 7.4.2 oder höher


Informationen zur .NET-spezifischen Fehlerbehebung finden Sie unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["SnapCenter-Upgrade oder -Installation schlägt bei Legacy-Systemen ohne Internetverbindung fehl"^].
 a| 
* .NET Framework 8.0.12 (und alle nachfolgenden 8.0.x-Patches)
* PowerShell 7.4.2 oder höher
* Nginx ist ein Webserver, der als Reverse Proxy verwendet werden kann
* PAM-Entwicklung
+
PAM (Pluggable Authentication Modules) ist ein Systemsicherheitstool, mit dem Systemadministratoren Authentifizierungsrichtlinien festlegen können, ohne Programme neu kompilieren zu müssen, die die Authentifizierung durchführen.



|===

NOTE: ASP.NET Core benötigt IIS_IUSRS für den Zugriff auf das temporäre Dateisystem im SnapCenter-Server unter Windows.
