---
permalink: install/reference_connection_and_port_requirements.html 
sidebar: sidebar 
keywords: ports, port requirements 
summary: Stellen Sie sicher, dass die Verbindungs- und Ports-Anforderungen erfüllt sind, bevor Sie die SnapCenter Server- und Applikations- oder Datenbank-Plug-ins installieren. 
---
= Verbindungs- und Portanforderungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie sicher, dass die Verbindungs- und Ports-Anforderungen erfüllt sind, bevor Sie die SnapCenter Server- und Applikations- oder Datenbank-Plug-ins installieren.

* Anwendungen können einen Port nicht gemeinsam nutzen.
+
Jeder Port muss der entsprechenden Applikation zugeordnet sein.

* Bei anpassbaren Ports können Sie während der Installation einen benutzerdefinierten Port auswählen, wenn Sie den Standardport nicht verwenden möchten.
+
Sie können einen Plug-in-Port nach der Installation mithilfe des Assistenten zum Ändern von Hosts ändern.

* Für feste Ports sollten Sie die Standard-Port-Nummer akzeptieren.
* Firewalls
+
** Firewalls, Proxys oder andere Netzwerkgeräte sollten keine Verbindung stören.
** Wenn Sie bei der Installation von SnapCenter einen benutzerdefinierten Port angeben, sollten Sie auf dem Plug-in-Host eine Firewall-Regel für diesen Port für den SnapCenter-Plug-in-Loader hinzufügen.




In der folgenden Tabelle werden die verschiedenen Ports und ihre Standardwerte aufgeführt.

|===
| Typ des Ports | Standardport 


 a| 
SnapCenter-Port
 a| 
8146 (HTTPS), bidirektional, anpassbar, wie unter der URL _\https://server:8146_

Wird für die Kommunikation zwischen dem SnapCenter-Client (dem SnapCenter-Benutzer) und dem SnapCenter-Server verwendet. Wird auch zur Kommunikation von den Plug-in-Hosts mit dem SnapCenter-Server verwendet.



 a| 
SnapCenter SMCore-Kommunikations-Port
 a| 
8145 (HTTPS), bidirektional, anpassbar

Der Port wird für die Kommunikation zwischen dem SnapCenter-Server und den Hosts verwendet, auf denen die SnapCenter-Plug-ins installiert sind.



 a| 
MySQL-Anschluss
 a| 
3306 (HTTPS), bidirektional

Der Port wird für die Kommunikation zwischen SnapCenter und der MySQL Repository Datenbank verwendet.

Sie können sichere Verbindungen vom SnapCenter-Server zum MySQL-Server erstellen. link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["Weitere Informationen ."]



 a| 
Windows Plug-in-Hosts
 a| 
135, 445 (TCP)

Neben den Ports 135 und 445 sollte auch der von Microsoft festgelegte dynamische Portbereich geöffnet sein. Remote-Installationsvorgänge verwenden den Windows Management Instrumentation (WMI)-Dienst, der diesen Portbereich dynamisch durchsucht.

Informationen zum unterstützten dynamischen Portbereich finden Sie unter https://support.microsoft.com/kb/832017["Serviceübersicht und Netzwerkanschlussanforderungen für Windows"^]

Die Ports dienen zur Kommunikation zwischen dem SnapCenter-Server und dem Host, auf dem das Plug-in installiert wird. Um Plug-in-Binärdateien auf Windows-Plug-in-Hosts zu übertragen, müssen die Ports nur auf dem Plug-in-Host geöffnet sein, und sie können nach der Installation geschlossen werden.



 a| 
Linux- oder AIX-Plug-in-Hosts
 a| 
22 (SSH)

Die Ports dienen zur Kommunikation zwischen dem SnapCenter-Server und dem Host, auf dem das Plug-in installiert wird. Die Ports werden von SnapCenter verwendet, um Plug-in-Paketbinärdateien auf Linux- oder AIX-Plug-in-Hosts zu kopieren. Sie sollten von der Firewall oder von iptables geöffnet oder ausgeschlossen sein.



 a| 
SnapCenter-Plug-ins-Paket für Windows, SnapCenter-Plug-ins-Paket für Linux oder SnapCenter-Plug-ins-Paket für AIX
 a| 
8145 (HTTPS), bidirektional, anpassbar

Der Port wird für die Kommunikation zwischen SMCore und Hosts verwendet, auf denen das Plug-ins-Paket installiert ist.

Der Kommunikationspfad muss auch zwischen der SVM-Management-LIF und dem SnapCenter-Server offen sein.



 a| 
SnapCenter Plug-in für Oracle Database
 a| 
27216, anpassbar

Der Standard-JDBC-Port wird vom Plug-in für Oracle für die Verbindung mit der Oracle-Datenbank verwendet.



 a| 
Benutzerdefinierte Plug-ins für SnapCenter
 a| 
9090 (HTTPS), fest

Dies ist ein interner Port, der nur auf dem benutzerdefinierten Plug-in-Host verwendet wird. Es ist keine Firewall-Ausnahme erforderlich.

Die Kommunikation zwischen dem SnapCenter-Server und benutzerdefinierten Plug-ins wird über Port 8145 geleitet.



 a| 
ONTAP-Cluster oder SVM-Kommunikations-Port
 a| 
443 (HTTPS), bidirectional80 (HTTP), bidirektional

Der Port wird von der SAL (Storage Abstraction Layer) für die Kommunikation zwischen dem Host verwendet, auf dem SnapCenter-Server und SVM ausgeführt wird. Der Port wird zur Kommunikation zwischen dem SnapCenter Plug-in-Host und der SVM derzeit auch von der SAL on SnapCenter für Windows Plug-in-Hosts verwendet.



 a| 
SnapCenter-Plug-in für SAP HANA-Datenbank vCode Zauber-Checkerports
 a| 
3instance_number13 or 3instance_number15, HTTP oder HTTPS, bidirektional und anpassbar

Bei einem einzelnen Mandanten mit mandantenfähigen Datenbank-Containern (MDC) endet die Port-Nummer mit 13. Für einen nicht-MDC-Server endet die Port-Nummer mit 15.

Beispielsweise ist 32013 die Portnummer für die Instanz 20 und 31015 die Portnummer für Instanz 10.



 a| 
Kommunikations-Port des Domänencontrollers
 a| 
In der Microsoft-Dokumentation finden Sie Informationen zu den Ports, die in der Firewall auf einem Domänencontroller geöffnet werden sollen, damit die Authentifizierung ordnungsgemäß funktioniert.

Es ist erforderlich, die erforderlichen Microsoft-Ports auf dem Domänen-Controller zu öffnen, damit der SnapCenter-Server, Plug-in-Hosts oder andere Windows-Client die Benutzer authentifizieren kann.

|===
Informationen zum Ändern der Portdetails finden Sie unter link:../admin/concept_manage_hosts.html#modify-plug-in-hosts["Ändern Sie die Plug-in-Hosts"].
