---
permalink: install/reference_connection_and_port_requirements.html 
sidebar: sidebar 
keywords: ports, port requirements 
summary: Stellen Sie sicher, dass die Verbindungs- und Ports-Anforderungen erfüllt sind, bevor Sie die SnapCenter Server- und Applikations- oder Datenbank-Plug-ins installieren. 
---
= Verbindungs- und Portanforderungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie sicher, dass die Verbindungs- und Ports-Anforderungen erfüllt sind, bevor Sie die SnapCenter Server- und Applikations- oder Datenbank-Plug-ins installieren.

* Anwendungen können einen Port nicht gemeinsam nutzen.
+
Jeder Port muss der entsprechenden Applikation zugeordnet sein.

* Bei anpassbaren Ports können Sie während der Installation einen benutzerdefinierten Port auswählen, wenn Sie den Standardport nicht verwenden möchten.
+
Sie können einen Plug-in-Port nach der Installation mithilfe des Assistenten zum Ändern von Hosts ändern.

* Für feste Ports sollten Sie die Standard-Port-Nummer akzeptieren.
* Firewalls
+
** Firewalls, Proxys oder andere Netzwerkgeräte sollten keine Verbindung stören.
** Wenn Sie bei der Installation von SnapCenter einen benutzerdefinierten Port angeben, sollten Sie auf dem Plug-in-Host eine Firewall-Regel für diesen Port für den SnapCenter-Plug-in-Loader hinzufügen.




In der folgenden Tabelle werden die verschiedenen Ports und ihre Standardwerte aufgeführt.

|===
| Port-Name | Port-Nummern | Protokoll | Richtung | Beschreibung 


 a| 
SnapCenter-Port
 a| 
8146
 a| 
HTTPS
 a| 
Bidirektional
 a| 
Dieser Port wird für die Kommunikation zwischen dem SnapCenter-Client (dem SnapCenter-Benutzer) und dem SnapCenter-Server verwendet und wird auch für die Kommunikation zwischen den Plug-in-Hosts und dem SnapCenter-Server verwendet.

Sie können die Portnummer anpassen.



 a| 
SnapCenter SMCore-Kommunikations-Port
 a| 
8145
 a| 
HTTPS
 a| 
Bidirektional
 a| 
Dieser Port wird für die Kommunikation zwischen dem SnapCenter-Server und den Hosts verwendet, auf denen die SnapCenter-Plug-ins installiert sind.

Sie können die Portnummer anpassen.



 a| 
Scheduler-Service-Port
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
Über diesen Port werden die SnapCenter-Scheduler-Workflows für alle gemanagten Plug-ins im SnapCenter Server Host zentral orchestriert.

Sie können die Portnummer anpassen.



 a| 
RabbitMQ-Anschluss
 a| 
5672
 a| 
TCP
 a| 
 a| 
Dies ist der Standardport, den RabbitMQ abhört und der für die Kommunikation zwischen dem Scheduler-Dienst und dem SnapCenter zwischen dem Publisher-Subscriber-Modell verwendet wird.



 a| 
MySQL-Anschluss
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
Der Port wird für die Kommunikation mit der SnapCenter-Repository-Datenbank verwendet. Sie können sichere Verbindungen vom SnapCenter-Server zum MySQL-Server erstellen. link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["Weitere Informationen ."]



 a| 
Windows Plug-in-Hosts
 a| 
135, 445
 a| 
TCP
 a| 
 a| 
Dieser Port wird für die Kommunikation zwischen dem SnapCenter-Server und dem Host verwendet, auf dem das Plug-in installiert wird. Der von Microsoft angegebene zusätzliche dynamische Portbereich sollte ebenfalls offen sein.



 a| 
Linux- oder AIX-Plug-in-Hosts
 a| 
22
 a| 
SSH
 a| 
Unidirektional
 a| 
Dieser Port wird für die Kommunikation zwischen dem SnapCenter-Server und dem Host verwendet, der vom Server zum Client-Host initiiert wird.



 a| 
SnapCenter Plug-ins-Paket für Windows, Linux oder AIX
 a| 
8145
 a| 
HTTPS
 a| 
Bidirektional
 a| 
Dieser Port wird für die Kommunikation zwischen SMCore und Hosts verwendet, auf denen das Plug-ins-Paket installiert ist. Anpassbar.

Sie können die Portnummer anpassen.



 a| 
SnapCenter Plug-in für Oracle Database
 a| 
27216
 a| 
 a| 
 a| 
Der Standard-JDBC-Port wird vom Plug-in für Oracle für die Verbindung mit der Oracle-Datenbank verwendet.



 a| 
SnapCenter Plug-in für Exchange Datenbank
 a| 
909
 a| 
 a| 
 a| 
Das Standard-NET. Der TCP-Port wird vom Plug-in für Windows für die Verbindung mit Exchange VSS-Rückrufen verwendet.



 a| 
Von NetApp unterstützte Plug-ins für SnapCenter
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
Dies ist ein interner Port, der nur auf dem benutzerdefinierten Plug-in-Host verwendet wird. Es ist keine Firewall-Ausnahme erforderlich.

Die Kommunikation zwischen dem SnapCenter-Server und benutzerdefinierten Plug-ins wird über Port 8145 geleitet.



 a| 
ONTAP-Cluster oder SVM-Kommunikations-Port
 a| 
* 443 (HTTPS)
* 80 (HTTP)

 a| 
* HTTPS
* HTTP

 a| 
Bidirektional
 a| 
Der Port wird von der SAL (Storage Abstraction Layer) für die Kommunikation zwischen dem Host verwendet, auf dem SnapCenter-Server und SVM ausgeführt wird. Der Port wird zur Kommunikation zwischen dem SnapCenter Plug-in-Host und der SVM derzeit auch von der SAL on SnapCenter für Windows Plug-in-Hosts verwendet.



 a| 
SnapCenter-Plug-in für SAP HANA Database
 a| 
* 3instance_number13
* 3instance_number15

 a| 
* HTTPS
* HTTP

 a| 
Bidirektional
 a| 
Bei einem einzelnen Mandanten mit mandantenfähigen Datenbank-Containern (MDC) endet die Port-Nummer mit 13. Für einen nicht-MDC-Server endet die Port-Nummer mit 15.

Sie können die Portnummer anpassen.



 a| 
SnapCenter Plug-in für PostgreSQL
 a| 
5432
 a| 
 a| 
 a| 
Dieser Port ist der Standard-PostgreSQL-Port, der für die Kommunikation des Plug-ins für PostgreSQL mit dem PostgreSQL-Cluster verwendet wird.

Sie können die Portnummer anpassen.

|===
Informationen zum Ändern der Portdetails finden Sie unter link:../admin/concept_manage_hosts.html#modify-plug-in-hosts["Ändern Sie die Plug-in-Hosts"].
