---
permalink: install/register_enable_software_access.html 
sidebar: sidebar 
keywords: install, snapcenter software, install, register, new customer, NetApp account, enable, Amazon FSx for NetApp ONTAP, Azure NetApp Files 
summary: Wenn Sie noch kein NetApp-Konto haben, führen Sie die folgenden Schritte aus, um sich für den Zugriff auf Software zu registrieren. 
---
= Registrieren Sie sich, um auf die SnapCenter Software zuzugreifen
:allow-uri-read: 


[role="lead"]
Sie sollten sich registrieren, um auf die SnapCenter Software zuzugreifen, wenn Sie zum ersten mal Amazon FSX for NetApp ONTAP oder Azure NetApp Files kennen und noch kein NetApp-Konto besitzen.

.Bevor Sie beginnen
* Sie sollten Zugriff auf die Unternehmens-E-Mail-ID haben.
* Wenn Sie Azure NetApp Files verwenden, sollten Sie über die Azure-Abonnement-ID verfügen.
* Wenn Sie Amazon FSX für NetApp ONTAP verwenden, sollten Sie die Dateisystem-ID Ihres FSX für ONTAP-Dateisystems haben.


.Über diese Aufgabe
Ihre Registrierung unterliegt der Informationsvalidierung und kann bis zu einem Tag dauern, bis Sie ein neues Konto auf der NetApp Support-Website (NSS) bestätigen und upgraden können, um vom *Guest*-Zugang *vollen* Zugriff zu erhalten.

.Schritte
. Klicken Sie hier, https://mysupport.netapp.com/site/user/registration[] um sich zu registrieren.
. Geben Sie Ihre Unternehmens-E-Mail-ID ein, füllen Sie das Captcha aus, akzeptieren Sie die Datenschutzerklärung von NetApp und klicken Sie auf *Senden*.
. Authentifizieren Sie die Registrierung, indem Sie das an Ihre E-Mail-ID gesendete OTP eingeben und auf *Weiter* klicken.
. Geben Sie auf der Seite zum Abschluss der Registrierung die folgenden Details ein, um die Registrierung abzuschließen.
+
.. Wählen Sie *NetApp-Kunde/Endbenutzer* aus.
.. Geben Sie im Feld SERIENNUMMER entweder die Azure-Abonnement-ID ein, wenn Sie Azure NetApp Files verwenden, oder die Dateisystemkennung, wenn Sie Amazon FSX für NetApp ONTAP verwenden.





NOTE: Sie können ein Ticket https://mysupport.netapp.com/site/help[] erstellen, wenn Sie während der Registrierung Probleme haben oder den Status kennen.
