---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate 
summary: Sie sollten das CA-Zertifikat mit der SnapCenter-Site auf einem Windows-Host konfigurieren. 
---
= Konfigurieren Sie ein CA-Zertifikat mit SnapCenter Site
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten das CA-Zertifikat mit der SnapCenter-Site auf einem Windows-Host konfigurieren.

*Schritte*

. Öffnen Sie den IIS-Manager auf dem Windows-Server, auf dem SnapCenter installiert ist.
. Klicken Sie im linken Navigationsbereich auf *Verbindungen*.
. Erweitern Sie den Namen des Servers und *Sites*.
. Wählen Sie die SnapCenter-Website aus, auf der Sie das SSL-Zertifikat installieren möchten.
. Navigieren Sie zu *Aktionen* > *Website bearbeiten* und klicken Sie auf *Bindungen*.
. Wählen Sie auf der Seite Bindungen die Option *Bindung für https* aus.
. Klicken Sie Auf *Bearbeiten*.
. Wählen Sie aus der Dropdown-Liste SSL-Zertifikat das kürzlich importierte SSL-Zertifikat aus.
. Klicken Sie auf *OK*.
+

NOTE: Die SnapCenter-Scheduler-Site (Standardport: 8154, HTTPS) ist mit einem selbstsignierten Zertifikat konfiguriert. Dieser Port kommuniziert innerhalb des SnapCenter-Serverhosts, und es ist nicht zwingend erforderlich, mit einem CA-Zertifikat zu konfigurieren. Wenn Sie in Ihrer Umgebung jedoch die Verwendung eines CA-Zertifikats vorschreibt, wiederholen Sie die Schritte 5 bis 9 mithilfe des SnapCenter-Planerstandorts.




NOTE: Wenn das kürzlich bereitgestellte CA-Zertifikat nicht im Dropdown-Menü aufgeführt ist, überprüfen Sie, ob das CA-Zertifikat mit dem privaten Schlüssel verknüpft ist.


IMPORTANT: Stellen Sie sicher, dass das Zertifikat über den folgenden Pfad hinzugefügt wird: *Konsolenstamm > Zertifikate – lokaler Computer > vertrauenswürdige Stammzertifizierungsstellen > Zertifikate*.
