---
permalink: install/task_switch_from_nlb_to_f5_for_high_availability.html 
sidebar: sidebar 
keywords: F5, NLB, high availability 
summary: 'Sie können Ihre SnapCenter HA-Konfiguration von Network Load Balancing (NLB) auf F5 Load Balancer ändern.' 
---
= Für hohe Verfügbarkeit von NLB auf F5 umschalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihre SnapCenter HA-Konfiguration von Network Load Balancing (NLB) auf F5 Load Balancer ändern.

*Schritte*

. Konfigurieren Sie SnapCenter-Server für Hochverfügbarkeit mit F5. https://["Weitere Informationen ."^].
. Starten Sie PowerShell auf dem Host des SnapCenter Servers.
. Starten Sie eine Sitzung mit dem Cmdlet "Open-SmConnection", und geben Sie dann Ihre Anmeldeinformationen ein.
. Aktualisieren Sie den SnapCenter-Server, um mit dem Cmdlet "Update-SmServerCluster" auf die F5-Cluster-IP-Adresse zu verweisen.
+
Die Informationen zu den Parametern, die mit dem Cmdlet und deren Beschreibungen verwendet werden können, können durch Ausführen von _get-Help Command_Name_ abgerufen werden. Alternativ können Sie auch auf die verweisen https://["SnapCenter Software Cmdlet Referenzhandbuch"^].


