---
permalink: install/task_install_the_snapcenter_server_using_the_install_wizard.html 
sidebar: sidebar 
keywords: install, snapcenter software, install wizard, features enabled 
summary: Sie können die ausführbare Datei für das SnapCenter-Server-Installationsprogramm ausführen, um den SnapCenter-Server zu installieren. 
---
= Installieren Sie den SnapCenter-Server auf dem Windows-Host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die ausführbare Datei für das SnapCenter-Server-Installationsprogramm ausführen, um den SnapCenter-Server zu installieren.

Optional können Sie mithilfe von PowerShell Cmdlets mehrere Installations- und Konfigurationsverfahren durchführen. Sie sollten PowerShell 7.4.2 oder höher verwenden.


NOTE: Die automatische Installation des SnapCenter-Servers über die Befehlszeile wird nicht unterstützt.

.Bevor Sie beginnen
* Der SnapCenter-Server-Host muss mit Windows-Updates auf dem neuesten Stand sein, ohne dass das System neu gestartet werden muss.
* Sie sollten sicherstellen, dass MySQL Server nicht auf dem Host installiert ist, auf dem Sie den SnapCenter-Server installieren möchten.
* Sie sollten das Debuggen von Windows-Installateurs aktiviert haben.
+
Informationen zur Aktivierung finden Sie auf der Microsoft-Website https://support.microsoft.com/kb/223300["Windows Installer-Protokollierung"^].

+

NOTE: Sie sollten den SnapCenter-Server nicht auf einem Host mit Microsoft Exchange Server, Active Directory oder Domain Name Servern installieren.



.Schritte
. Laden Sie das Installationspaket für den SnapCenter Server von herunter https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp Support Website"^].
. Starten Sie die Installation des SnapCenter-Servers, indem Sie auf die heruntergeladene .exe-Datei doppelklicken.
+
Nach Beginn der Installation werden alle Vorabprüfungen durchgeführt und wenn die Mindestanforderungen nicht erfüllt werden, werden entsprechende Fehler- oder Warnmeldungen angezeigt.

+
Sie können die Warnmeldungen ignorieren und mit der Installation fortfahren. Fehler sollten jedoch behoben werden.

. Überprüfen Sie die für die SnapCenter Server-Installation erforderlichen vordefinierten Werte, und ändern Sie sie, falls erforderlich.
+
Sie müssen das Kennwort für die MySQL Server Repository-Datenbank nicht angeben. Während der Installation des SnapCenter Servers wird das Passwort automatisch generiert.

+

NOTE: Das Sonderzeichen "`%`" is not supported in the custom path for the repository database. If you include "`%`“ im Pfad schlägt die Installation fehl.

. Klicken Sie Auf *Jetzt Installieren*.
+
Wenn Sie ungültige Werte angegeben haben, werden entsprechende Fehlermeldungen angezeigt. Sie sollten die Werte erneut eingeben und dann die Installation starten.

+

NOTE: Wenn Sie auf die Schaltfläche *Abbrechen* klicken, wird der ausgeführte Schritt abgeschlossen und der Rollback-Vorgang gestartet. Der SnapCenter-Server wird vollständig vom Host entfernt.

+
Wenn Sie jedoch *Abbrechen* klicken, wenn die Vorgänge „Neustart des SnapCenter-Servers“ oder „Warten auf Start des SnapCenter-Servers“ ausgeführt werden, wird die Installation ohne Abbrechen des Vorgangs fortgesetzt.

+
Protokolldateien werden immer im Ordner %temp% des Admin-Benutzers aufgeführt (älteste zuerst). Wenn Sie die Protokollstandorte umleiten möchten, initiieren Sie die Installation des SnapCenter-Servers über die Eingabeaufforderung, indem Sie Folgendes ausführen:``C:\installer_location\installer_name.exe /log"C:\"``





== Während der Installation auf dem Windows-Host aktivierte Funktionen

Das SnapCenter-Serverinstallationsprogramm aktiviert die Windows-Funktionen und -Rollen auf Ihrem Windows-Host während der Installation. Diese könnten für die Fehlerbehebung und Wartung des Hostsystems von Interesse sein.

|===
| Kategorie | Merkmal 


 a| 
Web-Server
 a| 
* Internet Information Services
* World Wide Web Services
* Allgemeine HTTP-Funktionen
+
** Standarddokument
** Verzeichnisbrowsing
** HTTP-Fehler
** HTTP-Umleitung
** Statischer Inhalt
** WebDAV-Publishing


* Systemzustand und Diagnose
+
** Benutzerdefinierte Protokollierung
** HTTP-Protokollierung
** Protokollierungs-Tools
** Monitor Anfordern
** Nachzeichnen


* Performance-Funktionen
+
** Statische Inhaltskomprimierung


* Sicherheit
+
** IP-Sicherheit
** Grundlegende Authentifizierung
** Zentralisierte Unterstützung von SSL-Zertifikaten
** Authentifizierung Für Die Clientzertifikatzuordnung
** Authentifizierung für die IIS-Clientzertifikatzuordnung
** IP- und Domänenbeschränkungen
** Anforderungsfilterung
** URL-Autorisierung
** Windows Authentifizierung


* Funktionen Zur Applikationsentwicklung
+
** .NET Extensibility 4.5
** Initialisierung Der Applikation
** ASP.NET Core Runtime 8.0.12 (und alle nachfolgenden 8.0.x-Patches) Hosting Bundle
** Server-Seitige Umfasst
** WebSocket-Protokoll


* Management Tools
+
** IIS-Verwaltungskonsole






 a| 
IIS-Verwaltungsskripte und -Tools
 a| 
* IIS-Verwaltungsdienst
* Web-Management-Tools




 a| 
+.NET Framework 8.0.12 Features+
 a| 
* ASP.NET Core Runtime 8.0.12 (und alle nachfolgenden 8.0.x-Patches) Hosting Bundle
* Windows Communication Foundation (WCF) HTTP Activation45
+
** TCP-Aktivierung
** HTTP-Aktivierung




Informationen zur .NET-spezifischen Fehlerbehebung finden Sie unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["SnapCenter-Upgrade oder -Installation schlägt bei Legacy-Systemen ohne Internetverbindung fehl"^].



 a| 
Windows-Prozess-Aktivierungsdienst
 a| 
Prozessmodell



 a| 
Konfigurations-APIs
 a| 
Alle

|===