---
permalink: protect-scu/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux.html 
sidebar: sidebar 
keywords: prerequisites, iSCSI, host requirement for Linux, sudo privileges, non-root user, credentials, authenticate, domain administrator, local administrator, workgroup, sudo, root user 
summary: Bevor Sie einen Host hinzufügen und die Plug-ins-Pakete installieren, müssen Sie alle Anforderungen erfüllen. 
---
= Voraussetzungen für das Hinzufügen von Hosts und das Installieren von Plug-ins Package für Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie einen Host hinzufügen und das Plug-in-Paket für Linux installieren, müssen Sie alle Anforderungen erfüllen.

* Wenn Sie iSCSI verwenden, muss der iSCSI-Dienst ausgeführt werden.
* Sie können entweder die passwortbasierte Authentifizierung für den Root- oder nicht-Root-Benutzer oder die SSH-Schlüsselauthentifizierung verwenden.
+
Das SnapCenter-Plug-in für Unix-Dateisysteme kann von einem Benutzer installiert werden, der kein Root-Benutzer ist. Sie sollten jedoch die sudo-Berechtigungen für den nicht-Root-Benutzer konfigurieren, um den Plug-in-Prozess zu installieren und zu starten. Nach der Installation des Plug-ins werden die Prozesse als effektiver nicht-Root-Benutzer ausgeführt.

* Anmeldedaten mit Authentifizierungsmodus als Linux für den Installationsbenutzer erstellen.
* Sie müssen Java 11 auf Ihrem Linux-Host installiert haben.
+

NOTE: Stellen Sie sicher, dass Sie nur die zertifizierte Version VON JAVA 11 auf dem Linux-Host installiert haben.

+
Informationen zum Herunterladen VON JAVA finden Sie unter: http://www.java.com/en/download/manual.jsp["Java-Downloads für alle Betriebssysteme"^]

* Sie sollten *bash* als Standard-Shell für die Plug-in-Installation haben.




== Linux Host-Anforderungen

Bevor Sie das SnapCenter-Plug-ins-Paket für Linux installieren, sollten Sie sicherstellen, dass der Host die Anforderungen erfüllt.

|===
| Element | Anforderungen 


 a| 
Betriebssysteme
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server (SLES)




 a| 
MindestRAM für das SnapCenter Plug-in auf dem Host
 a| 
2 GB



 a| 
Minimale Installation und Protokollierung von Speicherplatz für das SnapCenter Plug-in auf dem Host
 a| 
2 GB


NOTE: Sie sollten genügend Festplattenspeicher zuweisen und den Speicherverbrauch durch den Protokollordner überwachen. Der erforderliche Protokollspeicherplatz ist abhängig von der Anzahl der zu sichernden Einheiten und der Häufigkeit von Datensicherungsvorgängen. Wenn kein ausreichender Festplattenspeicher vorhanden ist, werden die Protokolle für die kürzlich ausgeführten Vorgänge nicht erstellt.



 a| 
Erforderliche Softwarepakete
 a| 
Java 11 Oracle Java und OpenJDK


NOTE: Stellen Sie sicher, dass Sie nur die zertifizierte Version VON JAVA 11 auf dem Linux-Host installiert haben.

Wenn SIE JAVA auf die neueste Version aktualisiert haben, müssen Sie sicherstellen, dass die JAVA_HOME-Option unter /var/opt/snapcenter/spl/etc/spl.properties auf die richtige JAVA-Version und den richtigen Pfad eingestellt ist.

|===
Aktuelle Informationen zu unterstützten Versionen finden Sie im https://imt.netapp.com/matrix/imt.jsp?components=116858;&solution=1258&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^].
