---
permalink: protect-scu/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux.html 
sidebar: sidebar 
keywords: prerequisites, iSCSI, host requirement for Linux, sudo privileges, non-root user, credentials, authenticate, domain administrator, local administrator, workgroup, sudo, root user 
summary: Bevor Sie einen Host hinzufügen und die Plug-ins-Pakete installieren, müssen Sie alle Anforderungen erfüllen. 
---
= Voraussetzungen für das Hinzufügen von Hosts und das Installieren von Plug-ins Package für Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie einen Host hinzufügen und das Plug-in-Paket für Linux installieren, müssen Sie alle Anforderungen erfüllen.

* Wenn Sie iSCSI verwenden, muss der iSCSI-Dienst ausgeführt werden.
* Sie können entweder die passwortbasierte Authentifizierung für den Root- oder nicht-Root-Benutzer oder die SSH-Schlüsselauthentifizierung verwenden.
+

NOTE: Der RSA-Schlüssel ist das einzige von SSH unterstützte Schlüsselformat für SnapCenter. Siehe den Knowledge Base Artikel link:https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/How_to_create_an_RSA_key_for_SnapCenter_SSH_Key_Based_credential["Wie man einen RSA-Schlüssel für SnapCenter SSH-schlüsselbasierte Anmeldeinformationen erstellt"^] für Details zum Erstellen des SSH-Schlüssels.

+
Das SnapCenter-Plug-in für Unix-Dateisysteme kann von einem Benutzer installiert werden, der kein Root-Benutzer ist. Sie sollten jedoch die sudo-Berechtigungen für den nicht-Root-Benutzer konfigurieren, um den Plug-in-Prozess zu installieren und zu starten. Nach der Installation des Plug-ins werden die Prozesse als effektiver nicht-Root-Benutzer ausgeführt.

* Anmeldedaten mit Authentifizierungsmodus als Linux für den Installationsbenutzer erstellen.
* Java 17 für SnapCenter 6.2.1 und höher oder Java 11 für SnapCenter 6.2 und früher muss auf Ihrem Linux-Host installiert sein.
+

NOTE: Stellen Sie sicher, dass Sie auf dem Linux-Host nur die zertifizierte Edition von Java 17 für SnapCenter 6.2.1 und höher oder Java 11 für SnapCenter 6.2 und früher installiert haben.

+
Informationen zu Java-Downloads finden Sie unter link:https://www.oracle.com/java/technologies/downloads/#java17["Laden Sie Java für alle Betriebssysteme herunter"^].

* Sie sollten *bash* als Standard-Shell für die Plug-in-Installation haben.




== Linux Host-Anforderungen

Bevor Sie das SnapCenter-Plug-ins-Paket für Linux installieren, sollten Sie sicherstellen, dass der Host die Anforderungen erfüllt.

|===
| Element | Anforderungen 


 a| 
Betriebssysteme
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server (SLES)




 a| 
MindestRAM für das SnapCenter Plug-in auf dem Host
 a| 
2 GB



 a| 
Minimale Installation und Protokollierung von Speicherplatz für das SnapCenter Plug-in auf dem Host
 a| 
2 GB


NOTE: Sie sollten genügend Festplattenspeicher zuweisen und den Speicherverbrauch durch den Protokollordner überwachen. Der erforderliche Protokollspeicherplatz ist abhängig von der Anzahl der zu sichernden Einheiten und der Häufigkeit von Datensicherungsvorgängen. Wenn kein ausreichender Festplattenspeicher vorhanden ist, werden die Protokolle für die kürzlich ausgeführten Vorgänge nicht erstellt.



 a| 
Erforderliche Softwarepakete
 a| 
* Java 17 (Oracle Java, OpenJDK oder SAP JDK) für SnapCenter 6.2.1 und höher oder Java 11 für SnapCenter 6.2 und früher



NOTE: Stellen Sie sicher, dass Sie auf dem Linux-Host nur die zertifizierte Edition von Java 17 für SnapCenter 6.2.1 und höher oder Java 11 für SnapCenter 6.2 und früher installiert haben.

Wenn Sie Java auf die neueste Version aktualisiert haben, müssen Sie sicherstellen, dass die Option JAVA_HOME unter /var/opt/snapcenter/spl/etc/spl.properties auf die richtige Java-Version und den richtigen Pfad eingestellt ist.

|===
Die aktuellsten Informationen zu den unterstützten Versionen finden Sie unter https://imt.netapp.com/imt/imt.jsp?components=180320;180338;&solution=1257&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^].
