---
permalink: protect-db2/add-hosts-and-install-plug-in-packages-on-remote-hosts-ibm-db2.html 
sidebar: sidebar 
keywords: credentials 
summary: Sie müssen Hosts über die Seite SnapCenter Add Host hinzufügen hinzufügen und dann die Plug-ins-Pakete installieren. Die Plug-ins werden automatisch auf den Remote-Hosts installiert. Sie können einen Host hinzufügen und Plug-in-Pakete für einen einzelnen Host oder für ein Cluster installieren. 
---
= Fügen Sie Hosts hinzu und installieren Sie Plug-in-Pakete auf Remote-Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen Hosts über die Seite SnapCenter Add Host hinzufügen hinzufügen und dann die Plug-ins-Pakete installieren. Die Plug-ins werden automatisch auf den Remote-Hosts installiert. Sie können einen Host hinzufügen und Plug-in-Pakete für einen einzelnen Host oder für ein Cluster installieren.

.Bevor Sie beginnen
* Wenn das Betriebssystem des SnapCenter-Server-Hosts Windows 2019 und das Betriebssystem des Plug-in-Hosts Windows 2022 ist, sollten Sie Folgendes durchführen:
+
** Führen Sie ein Upgrade auf Windows Server 2019 (OS Build 17763.5936) oder höher durch
** Führen Sie ein Upgrade auf Windows Server 2022 (OS Build 20348.2402) oder höher durch


* Sie müssen ein Benutzer sein, der einer Rolle zugewiesen ist, die über die Berechtigungen für die Plug-in-Installation und -Deinstallation verfügt, wie z. B. die Rolle „SnapCenter-Administrator“.
* Wenn Sie ein Plug-in auf einem Windows-Host installieren, wenn Sie keine Anmeldedaten angeben oder der Benutzer zu einem lokalen Workgroup-Benutzer gehört, müssen Sie UAC auf dem Host deaktivieren.
* Stellen Sie sicher, dass der Nachrichtenwarteschlange ausgeführt wird.
* Die Administrationsdokumentation enthält Informationen zum Verwalten von Hosts.
* Wenn Sie Group Managed Service Account (gMSA) verwenden, sollten Sie gMSA mit Administratorrechten konfigurieren.
+
link:../protect-db2/configure-gMSA-on-windows-server-2012-or-later.html["Konfigurieren Sie das Group Managed Service-Konto unter Windows Server 2016 oder höher für IBM DB2"^]



.Über diese Aufgabe
* Sie können einen SnapCenter-Server nicht als Plug-in-Host zu einem anderen SnapCenter-Server hinzufügen.


.Schritte
. Klicken Sie im linken Navigationsbereich auf *Hosts*.
. Überprüfen Sie, ob die Registerkarte *verwaltete Hosts* oben ausgewählt ist.
. Klicken Sie Auf *Hinzufügen*.
. Führen Sie auf der Seite Hosts die folgenden Aktionen durch:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Host-Typ
 a| 
Wählen Sie den Host-Typ aus:

** Windows
** Linux
+

NOTE: Das Plug-in für IBM DB2 ist auf dem IBM DB2-Client-Host installiert, und dieser Host kann entweder auf einem Windows-System oder auf einem Linux-System ausgeführt werden.





 a| 
Host-Name
 a| 
Geben Sie den Hostnamen der Kommunikation ein. Geben Sie den vollständig qualifizierten Domänennamen (FQDN) oder die IP-Adresse des Hosts ein. SnapCenter hängt von der richtigen Konfiguration des DNS ab. Daher empfiehlt es sich, den FQDN einzugeben.



 a| 
Anmeldedaten
 a| 
Wählen Sie entweder den von Ihnen erstellten Anmeldeinformationsnamen aus oder erstellen Sie neue Anmeldedaten. Die Anmeldeinformationen müssen über Administratorrechte auf dem Remote-Host verfügen. Weitere Informationen finden Sie unter Informationen zum Erstellen von Anmeldeinformationen.

Sie können Details zu den Anmeldeinformationen anzeigen, indem Sie den Cursor über den von Ihnen angegebenen Anmeldeinformationsnamen positionieren.


NOTE: Der Authentifizierungsmodus für die Anmeldeinformationen wird durch den Hosttyp bestimmt, den Sie im Assistenten zum Hinzufügen von Hosts angeben.

|===
. Wählen Sie im Abschnitt Plug-ins zum Installieren auswählen die zu installierenden Plug-ins aus.
+
Wenn Sie die REST-API zum Installieren von Plug-in für DB2 verwenden, müssen Sie die Version als 3.0 übergeben. Beispiel: DB2:3.0

. (Optional) Klicken Sie Auf *Weitere Optionen*.
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Port
 a| 
Behalten Sie die Standard-Port-Nummer bei oder geben Sie die Port-Nummer an. Die Standardanschlussnummer ist 8145. Wenn der SnapCenter-Server auf einem benutzerdefinierten Port installiert wurde, wird diese Portnummer als Standardport angezeigt.


NOTE: Wenn Sie die Plug-ins manuell installiert und einen benutzerdefinierten Port angegeben haben, müssen Sie denselben Port angeben. Andernfalls schlägt der Vorgang fehl.



 a| 
Installationspfad
 a| 
Das Plug-in für IBM DB2 ist auf dem IBM DB2-Client-Host installiert, und dieser Host kann entweder auf einem Windows-System oder auf einem Linux-System ausgeführt werden.

** Der Standardpfad für das SnapCenter Plug-ins-Paket für Windows ist C:\Programme\NetApp\SnapCenter. Optional können Sie den Pfad anpassen.
** Für das SnapCenter Plug-ins-Paket für Linux lautet der Standardpfad: /Opt/NetApp/snapcenter. Optional können Sie den Pfad anpassen.




 a| 
Überspringen Sie die Prüfungen vor der Installation
 a| 
Aktivieren Sie dieses Kontrollkästchen, wenn Sie die Plug-ins bereits manuell installiert haben und nicht überprüfen möchten, ob der Host die Anforderungen für die Installation des Plug-ins erfüllt.



 a| 
Verwenden Sie Group Managed Service Account (gMSA), um die Plug-in-Dienste auszuführen
 a| 
Aktivieren Sie für Windows-Host dieses Kontrollkästchen, wenn Sie die Plug-in-Dienste über das Group Managed Service Account (gMSA) ausführen möchten.


NOTE: Geben Sie den gMSA-Namen in folgendem Format an: Domainname\AccountName€.


NOTE: GSSA wird nur für den SnapCenter-Plug-in für Windows-Dienst als Anmelde-Dienstkonto verwendet.

|===
. Klicken Sie Auf *Absenden*.
+
Wenn Sie das Kontrollkästchen Vorabprüfungen überspringen nicht aktiviert haben, wird der Host validiert, um zu überprüfen, ob der Host die Anforderungen für die Installation des Plug-ins erfüllt. Der Festplattenspeicher, RAM, PowerShell-Version, . NET-Version, Speicherort (für Windows-Plug-ins) und Java 11 (für Windows- und Linux-Plug-ins) werden anhand der Mindestanforderungen validiert. Wenn die Mindestanforderungen nicht erfüllt werden, werden entsprechende Fehler- oder Warnmeldungen angezeigt.

+
Wenn der Fehler mit dem Festplattenspeicher oder RAM zusammenhängt, können Sie die Datei Web.config unter C:\Programme\NetApp\SnapCenter WebApp aktualisieren, um die Standardwerte zu ändern. Wenn der Fehler mit anderen Parametern zusammenhängt, müssen Sie das Problem beheben.

+

NOTE: Wenn Sie in einem HA-Setup die Datei „Web.config“ aktualisieren, müssen Sie die Datei auf beiden Knoten aktualisieren.

. Wenn der Hosttyp Linux ist, überprüfen Sie den Fingerabdruck und klicken Sie dann auf *Bestätigen und Senden*.
+
In einer Cluster-Einrichtung sollten Sie den Fingerabdruck aller Nodes im Cluster überprüfen.

+

NOTE: Eine Fingerabdruck-Verifizierung ist erforderlich, auch wenn zuvor derselbe Host zu SnapCenter hinzugefügt wurde und der Fingerabdruck bestätigt wurde.

. Überwachen Sie den Installationsfortschritt.
+
** Für das Windows Plug-in befinden sich die Installations- und Upgrade-Protokolle unter: _C:\Windows\SnapCenter Plug-in\Install_<JOBID>\
** Für Linux-Plug-ins befinden sich die Installationsprotokolle unter: _/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Install_<JOBID>.log. Die Upgrade-Protokolle befinden sich unter: _/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Upgrade_<JOBID>.log




.Nachdem Sie fertig sind
Wenn Sie auf SnapCenter 6.0 oder höher aktualisieren möchten, wird das vorhandene PERL-basierte Plug-in für DB2 vom Remote-Plug-in-Server deinstalliert.
