---
permalink: protect-db2/configure-CA-certificate-for-ibm-db2-on-windows-host.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Konfigurieren Sie das CA-Zertifikat für den SnapCenter-IBM DB2-Plug-ins-Dienst auf Windows-Hosts 
---
= Konfigurieren Sie das CA-Zertifikat für den SnapCenter-IBM DB2-Plug-ins-Dienst auf Windows-Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten das Kennwort des Plug-In-Schlüsselspeichers und seines Zertifikats verwalten, das CA-Zertifikat konfigurieren, Stamm- oder Zwischenzertifikate für den Plug-In-Truststore konfigurieren und ein von der CA signiertes Schlüsselpaar für den Plug-In-Truststore mit dem SnapCenter-Plug-In-Dienst konfigurieren, um das installierte digitale Zertifikat zu aktivieren.

Die Plug-Ins verwenden die Datei _keystore.jks_, die sich unter _C:\Programme\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc_ befindet, sowohl als Truststore als auch als Keystore.



== Verwalten Sie das Kennwort für den Plug-In-Schlüsselspeicher und den Alias des verwendeten, von der Zertifizierungsstelle signierten Schlüsselpaars.

.Schritte
. Sie können das Standardkennwort für den Plug-In-Keystore aus der Eigenschaftendatei des Plug-In-Agenten abrufen.
+
Es ist der Wert, der dem Schlüssel _KEYSTORE_PASS_ entspricht.

. Ändern Sie das Schlüsselspeicher-Passwort:
+
_Keytool -storepasswd -keystore keystore.jks_

+

NOTE: Wenn der Befehl "keytool" in der Windows-Eingabeaufforderung nicht erkannt wird, ersetzen Sie den Befehl keytool mit seinem vollständigen Pfad.

+
_C:\Programme\Java\<jdk_Version>\bin\keytool.exe“ -storepasswd -keystore keystore.jks_

. Ändern Sie das Kennwort für alle Aliase privater Schlüsseleinträge im Schlüsselspeicher auf dasselbe Kennwort, das für den Schlüsselspeicher verwendet wird:
+
_Keytool -keypasswd -alias „alias_Name_in_cert“ -keystore keystore.jks_

+
Aktualisieren Sie das gleiche für den Schlüssel KEYSTORE_PASS in _agent.properties_ Datei.

. Starten Sie den Dienst neu, nachdem Sie das Passwort geändert haben.
+

NOTE: Das Kennwort für den Plug-In-Schlüsselspeicher und für alle zugehörigen Aliaskennwörter des privaten Schlüssels müssen identisch sein.





== Konfigurieren Sie Stamm- oder Zwischenzertifikate für den Plug-In-Truststore

Sie sollten die Stamm- oder Zwischenzertifikate ohne den privaten Schlüssel für den Plug-In-Truststore konfigurieren.

.Schritte
. Navigieren Sie zu dem Ordner, der den Plug-in-Schlüsselspeicher enthält: _C:\Programme\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc_
. Suchen Sie die Datei 'keystore.jks'.
. Liste der hinzugefügten Zertifikate im Schlüsselspeicher:
+
_Keytool -list -V -keystore keystore.jks_

. Fügen Sie ein Stammzertifikat oder ein Zwischenzertifikat hinzu:
+
_Keytool -Import -trustcacerts -alias myRootCA -file /root/USERTrustRSA_Root.cer -keystore keystore.jks_

. Starten Sie den Dienst neu, nachdem Sie die Stamm- oder Zwischenzertifikate für den Plug-In-Truststore konfiguriert haben.



NOTE: Sie sollten das Root-CA-Zertifikat und anschließend die Zwischenzertifizierungszertifikate hinzufügen.



== Konfigurieren Sie das von der Zertifizierungsstelle signierte Schlüsselpaar für den Plug-In-Truststore

Sie sollten das von der Zertifizierungsstelle signierte Schlüsselpaar für den Truststore des Plug-Ins konfigurieren.

.Schritte
. Navigieren Sie zu dem Ordner, der den Plug-in-Schlüsselspeicher enthält: _C:\Programme\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc_
. Suchen Sie die Datei _keystore.jks_.
. Liste der hinzugefügten Zertifikate im Schlüsselspeicher:
+
_Keytool -list -V -keystore keystore.jks_

. Fügen Sie das CA-Zertifikat mit einem privaten und einem öffentlichen Schlüssel hinzu.
+
_Keytool -importkeystore -srckeystore /root/snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS_

. Listen Sie die hinzugefügten Zertifikate im Schlüsselspeicher auf.
+
_Keytool -list -V -keystore keystore.jks_

. Vergewissern Sie sich, dass der Schlüsselspeicher den Alias enthält, der dem neuen CA-Zertifikat entspricht, das dem Schlüsselspeicher hinzugefügt wurde.
. Ändern Sie das hinzugefügte Passwort für den privaten Schlüssel für das CA-Zertifikat in das Schlüsselspeicher-Passwort.
+
Das Standardkennwort für den Plug-in-Keystore ist der Wert des Schlüssels KEYSTORE_PASS in der Datei agent.properties.

+
_Keytool -keypasswd -alias „alias_Name_in_CA_cert“ -keystore keystore.jks_

. Konfigurieren Sie den Alias-Namen aus dem CA-Zertifikat in der Datei _agent.properties_.
+
Diesen Wert mit dem Schlüssel SCC_CERTIFICATE_ALIAS aktualisieren.

. Starten Sie den Dienst neu, nachdem Sie das von der Zertifizierungsstelle signierte Schlüsselpaar für den Plug-In-Truststore konfiguriert haben.




== Konfigurieren der Zertifikatsperrliste (CRL) für SnapCenter-Plug-Ins

.Über diese Aufgabe
* Informationen zum Herunterladen der neuesten CRL-Datei für das zugehörige CA-Zertifikat finden Sie unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_update_certificate_revocation_list_file_in_SnapCenter_CA_Certificate["Aktualisieren der Listendatei für Zertifikatsperrlisten im SnapCenter CA-Zertifikat"].
* SnapCenter-Plug-Ins suchen in einem vorkonfigurierten Verzeichnis nach den CRL-Dateien.
* Das Standardverzeichnis für die CRL-Dateien für SnapCenter-Plug-ins ist _'C:\Programme\NetApp\SnapCenter\Snapcenter Plug-in Creator\ etc\crl'_.


.Schritte
. Sie können das Standardverzeichnis in der Datei _agent.properties_ mit dem Schlüssel CRL_PATH ändern und aktualisieren.
. Sie können mehrere CRL-Dateien in diesem Verzeichnis platzieren.
+
Die eingehenden Zertifikate werden gegen jede CRL überprüft.


