---
permalink: protect-db2/host-requirements-to-install-snapcenter-plug-in-package-for-windows-db2.html 
sidebar: sidebar 
keywords: IBM Db2 
summary: Bevor Sie das SnapCenter Plug-ins-Paket für Windows installieren, sollten Sie mit einigen grundlegenden Speicherplatzanforderungen und Größenanforderungen für das Host-System vertraut sein. 
---
= Hostanforderungen für die Installation des SnapCenter Plug-ins Pakets für Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie das SnapCenter Plug-ins-Paket für Windows installieren, sollten Sie mit einigen grundlegenden Speicherplatzanforderungen und Größenanforderungen für das Host-System vertraut sein.

|===
| Element | Anforderungen 


 a| 
Betriebssysteme
 a| 
Microsoft Windows

+ Aktuelle Informationen zu unterstützten Versionen finden Sie unter https://imt.netapp.com/imt/imt.jsp?components=180321;180339;&solution=1257&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"]Die



 a| 
MindestRAM für das SnapCenter Plug-in auf dem Host
 a| 
1 GB



 a| 
Minimale Installation und Protokollierung von Speicherplatz für das SnapCenter Plug-in auf dem Host
 a| 
5 GB


NOTE: Sie sollten genügend Festplattenspeicher zuweisen und den Speicherverbrauch durch den Protokollordner überwachen. Der erforderliche Protokollspeicherplatz ist abhängig von der Anzahl der zu sichernden Einheiten und der Häufigkeit von Datensicherungsvorgängen. Wenn kein ausreichender Festplattenspeicher vorhanden ist, werden die Protokolle für die kürzlich ausgeführten Vorgänge nicht erstellt.



 a| 
Erforderliche Softwarepakete
 a| 
* ASP.NET Core Runtime 8.0.12 (und alle nachfolgenden 8.0.x-Patches) Hosting Bundle
* PowerShell Core 7.4.2
* Java 11 Oracle Java und OpenJDK


Informationen zur .NET-spezifischen Fehlerbehebung finden Sie unter https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["Das Upgrade oder die Installation von SnapCenter schlägt bei älteren Systemen, die keine Internetverbindung haben, fehl."]

|===