---
permalink: protect-db2/prerequisites-for-using-snapcenter-plug-in-for-ibm-db2.html 
sidebar: sidebar 
keywords: Credentials,SnapCenter Plug-in for IBM Db2 
summary: Bevor Sie das SnapCenter-Plug-in für IBM DB2 verwenden, muss der SnapCenter-Administrator den SnapCenter-Server installieren und konfigurieren und die erforderlichen Aufgaben ausführen. 
---
= Voraussetzungen für die Verwendung des SnapCenter-Plug-ins für IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie das SnapCenter-Plug-in für IBM DB2 verwenden, muss der SnapCenter-Administrator den SnapCenter-Server installieren und konfigurieren und die erforderlichen Aufgaben ausführen.

* Installation und Konfiguration von SnapCenter Server
* Melden Sie sich beim SnapCenter-Server an.
* Konfigurieren Sie die SnapCenter Umgebung, indem Sie Storage-Systemverbindungen hinzufügen und ggf. Anmeldedaten erstellen.
* Java 17 (Oracle Java, OpenJDK oder SAP JDK) für SnapCenter 6.2.1 und höher oder Java 11 für SnapCenter 6.2 und früher auf dem Linux- oder Windows-Host installieren.
+
Sie müssen den Java-Pfad in der Umgebungspfadvariable des Host-Rechners festlegen.

* Richten Sie SnapMirror und SnapVault ein, sofern Sie eine Backup-Replizierung möchten.

