---
permalink: protect-db2/types-of-restore-performed-for-auto-discovered-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 'SnapCenter unterstützt volumenbasierte SnapRestore (VBSR), Single File SnapRestore und Connect-and-Copy-Wiederherstellungstypen für automatisch erkannte IBM Db2-Datenbanken.' 
---
= Wiederherstellungstypen für automatisch erkannte IBM Db2-Datenbanken in SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SnapCenter Plug-in für IBM DB2 unterstützt Single File SnapRestore und Wiederherstellungstypen für Verbindungen und Kopien für automatisch erkannte IBM DB2-Datenbanken.



[[single-file-snaprestore-is-performed-in-nfs-environments-for-the-following-scenarios]]
== Single File SnapRestore wird in NFS-Umgebungen für die folgenden Szenarien durchgeführt:

* Wenn nur die Option *Complete Resource* ausgewählt ist
* Wenn der ausgewählte Backup von einem sekundären Standort SnapMirror oder SnapVault stammt und die Option *Complete Resource* ausgewählt ist




[[single-file-snaprestore-is-performed-in-san-environments-for-the-following-scenarios]]
== Single File SnapRestore wird in SAN-Umgebungen für die folgenden Szenarien durchgeführt:

* Wenn nur die Option *Complete Resource* ausgewählt ist
* Wenn das Backup von einem sekundären Standort SnapMirror oder SnapVault ausgewählt wird und die Option *Complete Resource* ausgewählt ist

