---
permalink: protect-nsp/add_hosts_and_install_plug_in_packages_on_remote_hosts.html 
sidebar: sidebar 
keywords: add hostsNetApp supported plug-ins, MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB, Storage plug-in 
summary: Sie müssen Hosts über die Seite SnapCenterAdd Host hinzufügen und dann die Plug-in-Pakete installieren. Die Plug-ins werden automatisch auf den Remote-Hosts installiert. Sie können einen Host hinzufügen und die Plug-in-Pakete entweder für einen einzelnen Host oder für einen Cluster installieren. 
---
= Hosts hinzufügen und SnapCenter Plug-in-Pakete auf Remote-Hosts installieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Seite SnapCenter Host hinzufügen verwenden, um Hosts hinzuzufügen, und dann die Plug-in-Pakete installieren. Die Plug-ins werden automatisch auf den Remote-Hosts installiert. Sie können einen Host hinzufügen und die Plug-in-Pakete entweder für einen einzelnen Host oder für einen Cluster installieren.

.Bevor Sie beginnen
* Sie sollten ein Benutzer sein, der einer Rolle zugewiesen wird, die über die Berechtigungen für die Plug-in-Installation und -Deinstallation verfügt, wie z. B. die Rolle „SnapCenter Admin“.
* Stellen Sie sicher, dass der Nachrichtenwarteschlange ausgeführt wird.
* Wenn Sie Group Managed Service Account (gMSA) verwenden, sollten Sie gMSA mit Administratorrechten konfigurieren.
+
link:configure_gMSA_on_windows_server_2012_or_later.html["Konfigurieren Sie das Gruppenkonto für Managed Services unter Windows Server 2016 oder höher für benutzerdefinierte Anwendungen"]

* Für Windows-Host müssen Sie sicherstellen, dass Sie SnapCenter-Plug-in für Windows auswählen.


.Über diese Aufgabe
* Sie können einen SnapCenter-Server nicht als Plug-in-Host zu einem anderen SnapCenter-Server hinzufügen.
* Wenn Sie Plug-ins auf einem Cluster (WSFC) installieren, werden die Plug-ins auf allen Nodes des Clusters installiert.


.Schritte
. Wählen Sie im linken Navigationsbereich *Hosts* aus.
. Überprüfen Sie, ob die Registerkarte *verwaltete Hosts* oben ausgewählt ist.
. Wählen Sie *Hinzufügen*.
. Führen Sie auf der Seite Hosts die folgenden Aktionen durch:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Host-Typ
 a| 
Wählen Sie den Host-Typ aus:

** Windows
** Linux
** AIX



NOTE: Die von NetApp unterstützten Plug-ins können in Windows-, Linux- und AIX-Umgebungen verwendet werden.


NOTE: Storage und Oracle Applikationen werden auf AIX unterstützt.



 a| 
Host-Name
 a| 
Geben Sie den vollständig qualifizierten Domänennamen (FQDN) oder die IP-Adresse des Hosts ein.

SnapCenter hängt von der richtigen Konfiguration des DNS ab. Daher empfiehlt es sich, den FQDN einzugeben.

In Windows-Umgebungen wird die IP-Adresse nur für nicht vertrauenswürdige Domänen-Hosts unterstützt, wenn sie in den FQDN auflöst.

Sie können die IP-Adressen oder FQDN eines eigenständigen Hosts eingeben.

Wenn Sie einen Host mithilfe von SnapCenter hinzufügen und der Host Teil einer Unterdomäne ist, müssen Sie den FQDN angeben.



 a| 
Anmeldedaten
 a| 
Wählen Sie entweder den von Ihnen erstellten Anmeldeinformationsnamen aus, oder erstellen Sie neue Anmeldedaten.

Die Anmeldeinformationen müssen über Administratorrechte auf dem Remote-Host verfügen. Weitere Informationen finden Sie unter Informationen zum Erstellen von Anmeldeinformationen.

Sie können Details zu den Anmeldeinformationen anzeigen, indem Sie den Cursor über den von Ihnen angegebenen Anmeldeinformationsnamen positionieren.


NOTE: Der Authentifizierungsmodus für die Anmeldeinformationen wird durch den Hosttyp bestimmt, den Sie im Assistenten zum Hinzufügen von Hosts angeben.

|===
. Wählen Sie im Abschnitt *Plug-ins zur Installation auswählen* die zu installierenden Plug-ins aus.
+
Sie können die folgenden Plug-ins aus der Liste installieren:

+
** MongoDB
** ORASCPM (angezeigt als Oracle Applications)
** SAP ASE
** SAP MaxDB
** Storage


. (Optional) Wählen Sie *Weitere Optionen*, um die anderen Plug-ins zu installieren.
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
Port
 a| 
Behalten Sie die Standard-Port-Nummer oder geben Sie die Port-Nummer an.

Die Standardanschlussnummer ist 8145. Wenn der SnapCenter-Server auf einem benutzerdefinierten Port installiert wurde, wird diese Portnummer als Standardport angezeigt.


NOTE: Wenn Sie die Plug-ins manuell installiert und einen benutzerdefinierten Port angegeben haben, müssen Sie denselben Port angeben. Andernfalls schlägt der Vorgang fehl.



 a| 
Installationspfad
 a| 
Die von NetApp unterstützten Plug-ins können entweder auf einem Windows-System oder auf einem Linux-System installiert werden.

** Der Standardpfad für das SnapCenter Plug-ins-Paket für Windows ist C:\Programme\NetApp\SnapCenter.
+
Optional können Sie den Pfad anpassen.

** Für SnapCenter Plug-ins Paket für Linux und SnapCenter Plug-ins Paket für AIX ist der Standardpfad `/opt/NetApp/snapcenter` .
+
Optional können Sie den Pfad anpassen.





 a| 
Überspringen Sie die Prüfungen vor der Installation
 a| 
Aktivieren Sie dieses Kontrollkästchen, wenn Sie die Plug-ins bereits manuell installiert haben und nicht überprüfen möchten, ob der Host die Anforderungen für die Installation des Plug-ins erfüllt.



 a| 
Verwenden Sie Group Managed Service Account (gMSA), um die Plug-in-Dienste auszuführen
 a| 
Aktivieren Sie für Windows-Host dieses Kontrollkästchen, wenn Sie die Plug-in-Dienste über das Group Managed Service Account (gMSA) ausführen möchten.


IMPORTANT: Geben Sie den gMSA-Namen in folgendem Format an: Domainname\AccountName€.


NOTE: GSSA wird nur für den SnapCenter-Plug-in für Windows-Dienst als Anmelde-Dienstkonto verwendet.

|===
. Wählen Sie *Senden*.
+
Wenn Sie das Kontrollkästchen *Vorabprüfungen* nicht aktiviert haben, wird der Host validiert, um zu überprüfen, ob der Host die Anforderungen für die Installation des Plug-ins erfüllt. Der Festplattenspeicher, der RAM, die PowerShell-Version, die .NET-Version, der Speicherort (für Windows-Plug-ins) und die Java-Version (für Linux-Plug-ins) werden anhand der Mindestanforderungen validiert. Wenn die Mindestanforderungen nicht erfüllt werden, werden entsprechende Fehler- oder Warnmeldungen angezeigt.

+
Wenn der Fehler mit dem Speicherplatz oder RAM zusammenhängt, können Sie die Datei Web.config unter aktualisieren `C:\Program Files\NetApp\SnapCenter WebApp`, um die Standardwerte zu ändern. Wenn der Fehler mit anderen Parametern zusammenhängt, müssen Sie das Problem beheben.

+

NOTE: Wenn Sie in einem HA-Setup SnapManager.Web.UI.dll.config aktualisieren, müssen Sie die Datei auf beiden Knoten aktualisieren und den SnapCenter-App-Pool neu starten.

+
Der Windows-Standardpfad lautet `C:\Program Files\NetApp\SnapCenter WebApp\SnapManager.Web.UI.dll.config`

+
Der Standardpfad für Linux lautet `/opt/NetApp/snapcenter/SnapManagerWeb/SnapManager.Web.UI.dll.config`

. Wenn der Hosttyp Linux ist, überprüfen Sie den Fingerabdruck und wählen Sie dann *Bestätigen und Senden*.
+

NOTE: Eine Fingerabdruck-Verifizierung ist erforderlich, auch wenn zuvor derselbe Host zu SnapCenter hinzugefügt wurde und der Fingerabdruck bestätigt wurde.

. Überwachen Sie den Installationsfortschritt.
+
Die installationsspezifischen Protokolldateien befinden sich unter `/custom_location/snapcenter/` Protokolle:


