---
permalink: protect-nsp/create_policies_for_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: create policies, NetApp supported plug-in 
summary: Bevor Sie SnapCenter zum Sichern bestimmter NetApp-unterstützter Plug-in-Ressourcen verwenden, müssen Sie eine Backup-Richtlinie für die Ressource oder Ressourcengruppe erstellen, die Sie sichern möchten. 
---
= Erstellen von Richtlinien für von NetApp unterstützte Plug-in-Ressourcen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie SnapCenter zum Sichern bestimmter NetApp-unterstützter Plug-in-Ressourcen verwenden, müssen Sie eine Backup-Richtlinie für die Ressource oder Ressourcengruppe erstellen, die Sie sichern möchten.

.Bevor Sie beginnen
* Sie sollten Ihre Backup-Strategie definiert haben.
+
Weitere Details finden Sie in den Informationen zur Definition einer Datensicherungsstrategie für von NetApp unterstützte Plug-ins.

* Sie sollten sich auf die Datensicherung vorbereiten.
+
Die Vorbereitung auf die Datensicherung umfasst Aufgaben wie das Installieren von SnapCenter, das Hinzufügen von Hosts, das Erstellen von Verbindungen zum Storage-System und das Hinzufügen von Ressourcen.

* Die Storage Virtual Machines (SVMs) sollten Ihnen für Spiegelungs- oder Vault-Vorgänge zugewiesen werden.
+
Der SnapCenter Administrator muss Ihnen die SVMs sowohl für die Quell- als auch für Ziel-Volumes zugewiesen haben, wenn Sie Snapshots auf eine Spiegelung oder einen Vault replizieren.

* Sie sollten die Ressourcen, die Sie schützen möchten, manuell hinzugefügt haben.


.Über diese Aufgabe
* Eine Backup-Richtlinie ist eine Reihe von Regeln, die das Managen, Planen und Aufbewahren von Backups regeln. Außerdem können Sie Replizierungs-, Skript- und Applikationseinstellungen festlegen.
* Durch das Festlegen von Optionen in einer Richtlinie wird Zeit eingespart, wenn die Richtlinie für eine andere Ressourcengruppe wiederverwendet werden soll.
* SnapLock
+
** Wenn die Option „Backup-Kopien für eine bestimmte Anzahl von Tagen aufbewahren“ ausgewählt ist, muss die SnapLock Aufbewahrungsfrist kleiner oder gleich den genannten Aufbewahrungstagen sein.
** Wenn Sie eine Snapshot-Sperrfrist festlegen, wird das Löschen der Snapshots bis zum Ablauf der Aufbewahrungsfrist verhindert. Dies kann dazu führen, dass eine größere Anzahl von Snapshots beibehalten wird als in der Richtlinie angegeben.
** Bei ONTAP Version 9.12.1 und niedriger übernehmen die im Rahmen der Wiederherstellung aus den SnapLock Vault Snapshots erstellten Klone die Verfallszeit von SnapLock Vault. Der Storage-Administrator sollte die Klone nach Ablauf der SnapLock-Gültigkeitsdauer manuell bereinigen.





NOTE: Die primären SnapLock-Einstellungen werden in der SnapCenter Backup Policy gemanagt, und die sekundären SnapLock-Einstellungen werden von ONTAP gemanagt.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Einstellungen*.
. Klicken Sie auf der Seite Einstellungen auf *Richtlinien*.
. Klicken Sie Auf *Neu*.
. Geben Sie auf der Seite Name den Richtliniennamen und Details ein.
. Führen Sie auf der Seite Richtlinientyp folgende Schritte aus:
+
.. Wählen Sie den Speichertyp aus.
.. Geben Sie im Abschnitt Benutzerdefinierte Backup-Einstellungen alle spezifischen Backup-Einstellungen an, die im Schlüsselwertformat an das Plug-in übergeben werden müssen.
+
Sie können mehrere wichtige Werte angeben, die an das Plug-in übergeben werden.



. Führen Sie auf der Seite Snapshot und Replikation die folgenden Schritte durch:
+
.. Geben Sie den Terminplantyp an, indem Sie *on Demand*, *hourly*, *Daily*, *Weekly* oder *Monthly* auswählen.
+

NOTE: Sie können den Zeitplan (Startdatum, Enddatum und Häufigkeit) für den Backup-Vorgang beim Erstellen einer Ressourcengruppe angeben. So können Sie Ressourcengruppen erstellen, die dieselben Richtlinien- und Backup-Häufigkeit verwenden, aber Sie können jeder Richtlinie verschiedene Backup-Zeitpläne zuweisen.

+

NOTE: Wenn Sie für 2:00 Uhr geplant sind, wird der Zeitplan während der Sommerzeit (DST) nicht ausgelöst.

.. Geben Sie im Abschnitt Snapshot-Einstellungen die Aufbewahrungseinstellungen für den Sicherungstyp und den auf der Seite *Sicherungstyp* ausgewählten Zeitplantyp an:
+
|===
| Ihr Ziel ist | Dann... 


 a| 
Behalten Sie eine bestimmte Anzahl von Snapshots bei
 a| 
Wählen Sie *Kopien, die behalten werden sollen*, und geben Sie dann die Anzahl der Snapshots an, die Sie behalten möchten.

Wenn die Anzahl der Snapshots die angegebene Zahl überschreitet, werden die Snapshots mit den ältesten zuerst gelöschten Kopien gelöscht.


NOTE: Sie müssen die Aufbewahrungsanzahl auf 2 oder höher einstellen, wenn Sie die SnapVault-Replikation aktivieren möchten. Wenn Sie den Aufbewahrungszeitraum auf 1 festlegen, kann der Aufbewahrungsvorgang fehlschlagen, weil der erste Snapshot der ReferenzSnapshot für die SnapVault-Beziehung ist, bis ein neuerer Snapshot auf das Ziel repliziert wird.


NOTE: Der maximale Aufbewahrungswert ist 1018. Backups schlagen fehl, wenn die Aufbewahrung auf einen Wert festgelegt ist, der höher ist, als die zugrunde liegende ONTAP Version unterstützt.



 a| 
Bewahren Sie die Snapshots für eine bestimmte Anzahl von Tagen auf
 a| 
Wählen Sie *Kopien behalten für*, und geben Sie dann die Anzahl der Tage an, für die Sie die Snapshots vor dem Löschen aufbewahren möchten.



 a| 
Sperrzeitraum für Snapshot-Kopien
 a| 
Wählen Sie *Sperrzeitraum für Snapshot-Kopien* und geben Sie Tage, Monate oder Jahre an.

Die SnapLock-Aufbewahrungsfrist sollte weniger als 100 Jahre betragen.

|===
.. Wählen Sie eine Richtlinienbezeichnung aus.
+

NOTE: Sie können primären Snapshots SnapMirror Labels für die Remote-Replikation zuweisen, sodass die primären Snapshots den Snapshot-Replikationsvorgang von SnapCenter auf sekundäre ONTAP -Systeme auslagern können.  Dies kann erfolgen, ohne die Option SnapMirror oder SnapVault auf der Richtlinienseite zu aktivieren.



. Wählen Sie im Abschnitt sekundäre Replikationsoptionen auswählen eine oder beide der folgenden sekundären Replikationsoptionen aus:
+
|===
| Für dieses Feld... | Tun Sie das... 


 a| 
*Aktualisieren Sie SnapMirror nach dem Erstellen einer lokalen Snapshot Kopie*
 a| 
Wählen Sie dieses Feld aus, um Spiegelkopien der Backup-Sätze auf einem anderen Volume zu erstellen (SnapMirror Replikation).

Wenn die Sicherungsbeziehung in ONTAP vom Typ „Mirror and Vault“ ist und Sie nur diese Option auswählen, wird auf dem primären Snapshot nicht an das Zielsystem übertragen, sondern auf dem Zielsystem aufgelistet. Wenn dieser Snapshot vom Ziel ausgewählt wurde, um einen Wiederherstellungsvorgang durchzuführen, wird die folgende Fehlermeldung angezeigt: Sekundärer Speicherort ist für das ausgewählte Backup mit vaulted/mirrored nicht verfügbar.

Während der sekundären Replizierung wird mit der SnapLock-Ablaufzeit die primäre SnapLock-Ablaufzeit geladen.

Durch Klicken auf die Schaltfläche * Aktualisieren* auf der Seite Topologie wird die sekundäre und primäre SnapLock-Ablaufzeit aktualisiert, die von ONTAP abgerufen werden.

Siehe link:view_netapp_supported_plugins_resource_backups_and_clones_in_the_topology_page.html["Zeigen Sie auf der Seite „Topologie“ ressourcenbezogene Backups und Klone von NetApp-unterstützten Plug-ins an"].



 a| 
*Aktualisieren Sie SnapVault nach dem Erstellen einer lokalen Snapshot Kopie*
 a| 
Wählen Sie diese Option aus, um Disk-to-Disk-Backup-Replikation (SnapVault-Backups) durchzuführen.

Während der sekundären Replizierung wird mit der SnapLock-Ablaufzeit die primäre SnapLock-Ablaufzeit geladen. Durch Klicken auf die Schaltfläche * Aktualisieren* auf der Seite Topologie wird die sekundäre und primäre SnapLock-Ablaufzeit aktualisiert, die von ONTAP abgerufen werden.

Wenn SnapLock nur auf dem sekundären aus ONTAP, dem sogenannten SnapLock-Vault, konfiguriert ist, wird durch Klicken auf die Schaltfläche * Aktualisieren* auf der Seite Topologie die Sperrfrist auf dem sekundären, das von ONTAP abgerufen wird, aktualisiert.

Weitere Informationen zu SnapLock Vault finden Sie unter Festsetzen von Snapshots auf WORM auf einem Vault-Ziel.

Siehe link:view_netapp_supported_plugins_resource_backups_and_clones_in_the_topology_page.html["Zeigen Sie auf der Seite „Topologie“ ressourcenbezogene Backups und Klone von NetApp-unterstützten Plug-ins an"].



 a| 
*Anzahl der Wiederholversuche*
 a| 
Geben Sie die maximale Anzahl von Replikationsversuchen ein, die zulässig sind, bevor der Vorgang beendet wird.

|===
+

NOTE: Sie sollten die SnapMirror Aufbewahrungsrichtlinie in ONTAP für den sekundären Storage konfigurieren, um die maximale Grenze von Snapshots auf dem sekundären Storage zu vermeiden.

. Überprüfen Sie die Zusammenfassung und klicken Sie dann auf *Fertig stellen*.

