---
permalink: get-started/learn-about-snapcenter-support-for-asa-r2-systems.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: Sie sollten das unterstützte Storage-System, die Applikationen und Datenbanken kennen. 
---
= Unterstützte SnapCenter-Operationen für ASA R2-Systeme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2-Speichersysteme werden ab SnapCenter 6.1 unterstützt. https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Erfahren Sie mehr über ASA r2-Systeme"^] .

SnapCenter unterstützt sowohl den primären als auch den sekundären Schutz von Anwendungen, die auf physischen Systemen und auf Virtual Machine File Systems (VMFS) ausgeführt werden.  SnapCenter verwendet REST-APIs für alle Vorgänge auf ASA r2-Systemen.  ASA r2-Systeme unterstützen keine ZAPIs.

*Von SnapCenter für ASA r2-Systeme unterstützte Vorgänge*

* Erstellen primärer Backups von Anwendungen
* Verschieben von Snapshots hierarchischer Konsistenzgruppen auf ein sekundäres Speichersystem
* Wiederherstellen von Backups von primären und sekundären Speichersystemen auf dem ursprünglichen oder alternativen Host
+
** In-Place-Wiederherstellung von primären und sekundären Speichersystemen mit VMware vMotion
** Verbinden und Kopieren sowie Wiederherstellen von primären und sekundären Speichersystemen


* Klonen der Backups auf den ursprünglichen Host oder auf den alternativen Host
* Raw Device Mapping (RDM)
* Schutz von Anwendungsvolumes für Oracle
* Schutz von SAP HANA NDV
* LockVault
* Sekundäre Bereitstellung des Protokollverzeichnisses des SQL-Plugin-Hosts


SnapCenter erkennt oder erstellt ONTAP Konsistenzgruppen.  Es richtet SnapMirror -Beziehungen auf dem Zielcluster für sekundären Schutz ein. https://docs.netapp.com/us-en/ontap/consistency-groups["Erfahren Sie mehr über ONTAP Consistency Groups"^] .


NOTE: Nach dem Upgrade auf SnapCenter 6.2 (Server und Plug-Ins) und ONTAP 9.17.1 ändert SnapCenter während der ersten geplanten Sicherung flache Konsistenzgruppen in hierarchische Konsistenzgruppen.

Informationen zum Aktivieren des sekundären Schutzes auf ASA R2-Systemen für Ihre Anwendung finden Sie unter:

* https://docs.netapp.com/us-en/snapcenter/protect-scsql/create-resource-groups-secondary-protection-for-asa-r2-mssql-resources.html["Aktivieren Sie den sekundären Schutz für Microsoft SQL Server-Ressourcen"]
* https://docs.netapp.com/us-en/snapcenter/protect-hana/create-resource-groups-secondary-protection-for-asa-r2-hana-resources.html["Aktivieren Sie den sekundären Schutz für SAP HANA-Ressourcen"]
* https://docs.netapp.com/us-en/snapcenter/protect-sco/create-resource-groups-secondary-protection-for-asa-r2-oracle-resources.html["Aktivieren Sie den sekundären Schutz für Oracle-Ressourcen"]
* https://docs.netapp.com/us-en/snapcenter/protect-scw/create-resource-groups-secondary-protection-for-asa-r2-windows-file-systems.html["Aktivieren Sie den sekundären Schutz für Windows-Dateisysteme"]
* https://docs.netapp.com/us-en/snapcenter/protect-db2/create-resource-groups-secondary-protection-for-asa-r2-db2-resources.html["Aktivieren Sie den sekundären Schutz für IBM Db2-Ressourcen"]
* https://docs.netapp.com/us-en/snapcenter/protect-postgresql/create-resource-groups-secondary-protection-for-asa-r2-postgresql-resources.html["Aktivieren Sie den sekundären Schutz für PostgreSQL-Ressourcen"]
* https://docs.netapp.com/us-en/snapcenter/protect-mysql/create-resource-groups-secondary-protection-for-asa-r2-mysql-resources.html["Aktivieren Sie den sekundären Schutz für MySQL-Ressourcen"]
* https://docs.netapp.com/us-en/snapcenter/protect-scu/create-resource-groups-secondary-protection-for-asa-r2-unix-resources.html["Aktivieren Sie den sekundären Schutz für Unix-Dateisysteme"]


*Von SnapCenter für ASA r2-Systeme nicht unterstützte Vorgänge*

* Manipulationssichere Snapshots
* FlexGroup Volumes
* Migration von ASA-, AFF- oder FAS-Speichersystemen auf ASA r2-Speichersysteme
* Schutz von Datenbanken mit einer Mischung aus ASA, AFF oder FAS -Ressourcen und ASA r2-Ressourcen
* Umbenennen von Snapshots
* Bereitstellung von Windows-Ressourcen
* Sekundärer Schutz bei SnapMirror Active Sync Failover
* Nonvolatile Memory Express (NVMe)-Protokoll, wenn SnapMirror Active Sync aktiviert ist
* Schutz von Anwendungen, die auf AIX laufen
* Technologieaktualisierung
* Notfallwiederherstellung von Microsoft SQL-Ressourcen

