---
permalink: get-started/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: Sie sollten das unterstützte Storage-System, die Applikationen und Datenbanken kennen. 
---
= Storage-Systeme und Applikationen unterstützt von SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die Storage-Systeme, Applikationen und Datenbanken kennen, die von SnapCenter unterstützt werden.



== Unterstützte Storage-Systeme

* NetApp ONTAP 9.12.1 und höher
* Azure NetApp Dateien
* Amazon FSX für NetApp ONTAP
+
Amazon FSx for NetApp ONTAP unterstützt Non-Volatile Memory Express (NVMe) über Transport Control Protocol (TCP).

+
Informationen zu Amazon FSX für NetApp ONTAP finden Sie unter https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Dokumentation zu Amazon FSX für NetApp ONTAP"^].

* NetApp ASA r2-Systeme, auf denen NetApp ONTAP 9.16.1 und höher ausgeführt wird
+
Sie sollten ONTAP 9.17.1 verwenden, wenn Sie SnapCenter Server 6.2 und SnapCenter -Plug-Ins 6.2 verwenden.





== Unterstützte Applikationen und Datenbanken

SnapCenter unterstützt den Schutz verschiedener Anwendungen und Datenbanken.

SnapCenter unterstützt den Schutz von Oracle- und Microsoft SQL-Workloads in VMware Cloud auf AWS-Umgebungen (Software-Defined Data Center) von Amazon Web Services. https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["Weitere Informationen"^].
