---
permalink: get-started/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: Sie sollten das unterstützte Storage-System, die Applikationen und Datenbanken kennen. 
---
= Storage-Systeme und Applikationen unterstützt von SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die Storage-Systeme, Applikationen und Datenbanken kennen, die von SnapCenter unterstützt werden.



== Unterstützte Storage-Systeme

* NetApp ONTAP 9.12.1 und höher
* Azure NetApp Dateien
* Amazon FSX für NetApp ONTAP
+
Unterstützt Non-Volatile Memory Express (NVMe) über Transport Control Protocol (TCP).

+
Informationen zu Amazon FSX für NetApp ONTAP finden Sie unter https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Dokumentation zu Amazon FSX für NetApp ONTAP"^].

* NetApp ASA r2-Systeme mit NetApp ONTAP 9.16.1.
+
ASA r2 Systeme bieten eine einheitliche Hardware- und Softwarelösung für reine SAN-Umgebungen, die auf All-Flash-Plattformen basieren. https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Erfahren Sie mehr über ASA r2-Systeme"].

+

NOTE: SnapCenter unterstützt nur VMware Virtual Machine File System (VMFS) auf ASA r2 Systemen.

+
|===
| Unterstützte Vorgänge | Vorgänge werden nicht unterstützt 


 a| 
** Erstellung primärer Backups von Anwendungen über VMDK
** Übertragen von Snapshots von Konsistenzgruppen auf das sekundäre Speichersystem
** Wiederherstellen der Backups und Wiederherstellung von einem anderen Speicherort
+
*** In-Place-Wiederherstellung von primärem und sekundärem Storage mit VMware vMotion
*** Verbinden und Kopieren von Daten aus primärem und sekundärem Storage


** Das Klonen der Backups und das Klonen an einem alternativen Speicherort

 a| 
** Raw Device Mapping (RDM)
** Application Volumes für Oracle
** SAP HANA NDV
** LockVault
** Manipulationssicherer Schnappschuss
** Flex Group
** Hierarchische Konsistenzgruppe
** Migration von ONTAP 9.x auf ASA r2-Systeme
** Umbenennen von Snapshots
** Die sekundäre Bereitstellung des Protokollverzeichnisses des SQL Plug-in-Hosts wird von SnapCenter nicht unterstützt. Sie sollten die Konfiguration manuell entweder mit der ONTAP CLI oder mit System Manager durchführen.


|===




== Unterstützte Applikationen und Datenbanken

SnapCenter unterstützt den Schutz verschiedener Applikationen und Datenbanken. Ausführliche Informationen zu den unterstützten Anwendungen und Datenbanken finden Sie unter https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^].

SnapCenter unterstützt den Schutz von Oracle- und Microsoft SQL-Workloads in VMware Cloud auf AWS-Umgebungen (Software-Defined Data Center) von Amazon Web Services. https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["Weitere Informationen"^].
