---
permalink: release-notes/release-notes.html 
sidebar: sidebar 
keywords: release notes, snapcenter 
summary: Liefert wichtige Informationen zu dieser Version von SnapCenter Server und den SnapCenter Plug-in-Paketen, einschließlich behoer Probleme, bekannter Probleme, Vorsichtsmaßnahmen und Einschränkungen. 
---
= Versionshinweise
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Informationen zu den neuen und verbesserten Funktionen in SnapCenter 6.2, 6.2.1 und 6.2.2.

Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter link:what's-new-in-snapcenter622.html["Was ist neu in SnapCenter 6.2.2"].

Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter link:what's-new-in-snapcenter621.html["Was ist neu in SnapCenter 6.2.1"].

Eine vollständige Liste der neuen Funktionen und Verbesserungen finden Sie unter link:what's-new-in-snapcenter62.html["Was ist neu in SnapCenter 6.2"].

Einzelheiten zu bekannten Problemen, Einschränkungen, behobenen Problemen sowie neuen und geänderten Befehlen finden Sie in den  https://library.netapp.com/ecm/ecm_download_file/ECMLP3359467["SnapCenter Software 6.2.2 Versionshinweise"^]. Sie müssen sich mit Ihrem NetApp Konto anmelden oder ein Konto erstellen, um auf die Versionshinweise zuzugreifen.
