---
permalink: release-notes/upgrade-path.html 
sidebar: sidebar 
keywords: upgrade paths, supported, upgrade to SnapCenter 
summary: Die von SnapCenter unterstützten Upgrade-Pfade 
---
= Unterstützte Upgrade-Pfade für SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Upgrade-Pfad verhilft Ihnen zu einem Bild davon, von welchen älteren SnapCenter Versionen Sie ein Upgrade auf die neueste SnapCenter Version durchführen können und welche Plug-ins-Versionen unterstützt werden.

|===
| Wenn Sie sich auf SnapCenter Server-Version befinden... | Sie können ein Upgrade des SnapCenter-Servers direkt auf... | Unterstützte Plug-in-Versionen 


.2+| 4.9 | 5.0  a| 
* 4.9
* 5.0




| 6,0  a| 
* 6,0




.2+| 5.0  a| 
6,0
 a| 
* 5.0
* 6,0




| 6.0.1  a| 
* 6.0.1




| 6,0 | 6.0.1  a| 
* 6,0
* 6.0.1


|===

IMPORTANT: Wenn Sie beispielsweise SnapCenter Version 4.9 verwenden und auf 6.0 aktualisieren möchten, sollten Sie zuerst ein Upgrade auf 5.0 durchführen und dann ein Rolling Upgrade auf 6.0 durchführen.

Informationen zum Upgrade des SnapCenter Plug-ins für VMware vSphere finden Sie unter https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_upgrade.html["Aktualisieren Sie das SnapCenter Plug-in für VMware vSphere"^].
