---
permalink: 'release-notes/what"s-new-in-snapcenter601.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0.1 
summary: Die Version 6.0.1 der SnapCenter Software enthält mehrere neue Funktionen und Verbesserungen. 
---
= Neuerungen bei SnapCenter 6.0.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Version 6.0.1 der SnapCenter Software enthält mehrere neue Funktionen und Verbesserungen.

|===
| Aktualisierung | Beschreibung 


| link:https://docs.netapp.com/us-en/snapcenter/protect-azure/protect-applications-azure-netapp-files.html["Unterstützung von Azure NetApp Files-Backups"]  a| 
Sie können jetzt SnapCenter verwenden, um ein Backup oder Klonen von Applikationen auf Azure NetApp Files in Azure Blob Storage (Objektspeicher) zu erstellen.



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["Unterstützung für Hochverfügbarkeit von SnapCenter unter Linux"]  a| 
Die Unterstützung für HA-Konfiguration für SnapCenter ist nun auch auf Linux Systeme verfügbar. Für diese Konfiguration können Sie die Standardlastverteiler verwenden:

* F5 Load Balancer
* Microsoft Network Load Balancing (NLB)
* Amazon Web Services (AWS)
* Elastischer Lastausgleich (ELB)
* Azure Load Balancer




| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-scheduled-backup-jobs["Möglichkeit zum Management geplanter Backup-Jobs"]  a| 
Sie können jetzt einen Schwellenwert für Ihre geplanten Jobs festlegen, um die Anzahl der Backups zu kontrollieren, die Sie je nach Konfiguration der Systemhardware zu einem bestimmten Zeitpunkt ausführen möchten.



| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-stale-jobs["Möglichkeit zum Managen veralteter Jobs"]  a| 
Sie können jetzt einen vordefinierten Zeitplan festlegen, um veraltete Jobs zu bereinigen, die länger als 72 Stunden anstehen.



| Datensicherungsfunktionen für IBM DB2, Oracle Application und Storage Plug-in auf AIX enthalten  a| 
Unterstützt Datensicherung von IBM DB2, Oracle Application und Storage Plug-in auf AIX.

|===