---
permalink: 'release-notes/what"s-new-in-snapcenter60.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0 
summary: Die Version 6.0 der SnapCenter Software enthält mehrere neue Funktionen und Verbesserungen. 
---
= Neuerungen bei SnapCenter 6.0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Version 6.0 der SnapCenter Software enthält mehrere neue Funktionen und Verbesserungen.

|===
| Aktualisierung | Beschreibung 


| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html#snapcenter-plug-ins["Unterstützung von Plug-ins für Enterprise-Workloads mit NetApp Unterstützung"]  a| 
SnapCenter bietet Plug-ins für das Management von Workloads wie PostgreSQL, MySQL und IBM DB2. Sie können die Workloads automatisch ermitteln, sichern, wiederherstellen, mounten und klonen.

SnapCenter bietet auch Plug-ins für das Management von Workloads wie SAP ASE, SAP MaxDB, MongoDB, Oracle Applikationen und ONTAP Storage. Sie können die Workloads sichern, wiederherstellen und klonen.



| link:https://docs.netapp.com/us-en/snapcenter/install/install_snapcenter_server_linux.html["Unterstützung für die Linux-Version von SnapCenter für Cloud- und On-Premises-Workloads"]  a| 
Für Linux-Versionen wie Red hat Enterprise Linux (RHEL), Oracle Linux und SUSE Linux Enterprise Server (SLES) sind jetzt separate SnapCenter-Binärdateien verfügbar.

* Unterstützt Azure NetApp Files, Amazon FSX für NetApp ONTAP, Cloud Volumes ONTAP und ONTAP Storage.
* Separate Binärdateien für Linux-Versionen wie Red hat Enterprise Linux (RHEL), Oracle Linux und SUSE Linux Enterprise Server (SLES).
* Unterstützung klassischer Datenbanken wie SAP HANA, Oracle, IBM DB2, SAP ASE, SAP MaxDB.
* Sie unterstützt moderne Workloads wie PostgreSQL, MySQL und MongoDB.
* Unterstützt Plug-ins für ONTAP Volumes und Linux-Filesysteme zum Schutz von nicht unterstützten und selbst entwickelten Applikationen.




| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html["Unterstützung für SnapMirror Active Sync"]  a| 
Mit SnapCenter können Sie nun die Funktionen der SnapMirror Active Sync konfigurieren und SAN Workloads für Datenbanken und VMware VMs effizient sichern, wiederherstellen und klonen. Dies gewährleistet ein transparentes Applikations-Failover und Business Continuity.



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_create_and_manage_smb_shares.html["Unterstützung von Microsoft SQL Server über SMB3"]  a| 
Mit SnapCenter können Sie jetzt Microsoft SQL Server Datenbanken schützen, die über das SMB3-Protokoll in ONTAP, Azure NetApp Files, Amazon FSX for NetApp ONTAP und Cloud Volumes ONTAP implementiert werden.



| link:https://docs.netapp.com/us-en/snapcenter/protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html#storage-types-supported-on-linux["Unterstützung von NVMe/TCP"]  a| 
SnapCenter unterstützt jetzt das NVMe-over-TCP-Protokoll für das Backup und Recovery von Applikationen und Filesystemen.



| Unterstützung von VMware vSphere Virtual Volumes (VVols)  a| 
Mit SnapCenter können Sie Ihre auf VVols implementierten Datenbanken und Filesysteme sichern.

|===