---
permalink: 'release-notes/what"s-new-in-snapcenter601.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0.1 
summary: Die Version 6.0.1 der SnapCenter Software enthält mehrere neue Funktionen und Verbesserungen. 
---
= Neuerungen bei SnapCenter 6.0.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Version 6.0.1 der SnapCenter Software enthält mehrere neue Funktionen und Verbesserungen.

|===
| Aktualisierung | Beschreibung 


| link:https://docs.netapp.com/us-en/snapcenter/protect-azure/protect-applications-azure-netapp-files.html["Unterstützung von Azure NetApp Files-Backups"]  a| 
SnapCenter unterstützt die Backup-Funktion Azure NetApp Files, die die Datensicherungsfunktionen von Azure NetApp Files durch die Bereitstellung einer vollständig gemanagten Backup-Lösung für langfristiges Recovery, Archivierung und Compliance erweitert.



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["Unterstützung für Hochverfügbarkeit von SnapCenter unter Linux"]  a| 
Konfigurieren Sie die Hochverfügbarkeit in SnapCenter unter Windows oder Linux entweder mit dem F5 Load Balancer, dem Microsoft Network Load Balancing (NLB), dem Amazon Web Services (AWS) Elastic Load Balancing (ELB) oder dem Azure Load Balancer.



| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-scheduled-backup-jobs["Unterstützung für das Management geplanter Backup-Jobs"]  a| 
Ermöglicht das Festlegen eines Schwellenwerts für die Anzahl der geplanten Jobs, die zu einem bestimmten Zeitpunkt ausgeführt werden können. So können Sie die Anzahl der Backups steuern, die basierend auf der Hardwarekonfiguration des Systems ausgeführt werden sollen.



| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-stale-jobs["Unterstützung für das Management veralteter Jobs"]  a| 
Ermöglicht die Bereinigung veralteter Jobs, die länger als 72 Stunden nicht mehr gespeichert sind.



| Unterstützung für IBM DB2, Oracle Application und Storage Plug-in auf AIX  a| 
Unterstützt Datensicherung von IBM DB2, Oracle Application und Storage Plug-in auf AIX

|===